// SPDX-License-Identifier: Apache-2.0

package executor

import (
	"fmt"
	"regexp"
	"sort"
	"strings"

	"github.com/mendixlabs/mxcli/mdl/ast"
	"github.com/mendixlabs/mxcli/mdl/backend"
	mdlerrors "github.com/mendixlabs/mxcli/mdl/errors"
	"github.com/mendixlabs/mxcli/mdl/types"
	"github.com/mendixlabs/mxcli/model"
	"github.com/mendixlabs/mxcli/sdk/pages"
)

// defaultSlotContainer is the MDLContainer name that receives default (non-containerized) child widgets.
const defaultSlotContainer = "template"

// =============================================================================
// Pluggable Widget Engine — Core Types
// =============================================================================

// WidgetDefGeneratorVersion is the schema/logic version of GenerateDefJSON's
// output. Bump it whenever the def.json generation changes in a way that
// affects emitted BSON (new fields like mdlAliases / acceptedChildTypes,
// changed defaults, new routing). Project-local `.mxcli/widgets/*.def.json`
// files stamp this value; `exec` auto-refreshes any whose stamp is behind,
// so an mxcli upgrade doesn't silently emit stale BSON from defs that were
// generated by an older build (the .mpk hasn't changed, only our logic has).
//
// Version history:
//
//	1 — pre-v0.12.0 (unstamped; treated as 0)
//	2 — v0.12.0: mdlAliases, acceptedChildTypes, attrChoice=auto, column
//	    convention fallbacks
//	3 — v0.12.0: propertyVisibility (VideoPlayer/Timeline hidden-property
//	    TextTemplate nulling, #574)
//	4 — v0.12.0: DataGrid column `width` ← `ColumnWidth` alias (dgDyn CE0463
//	    regression from the keyword-path consolidation)
//	5 — bundled multi-widget .mpk support: a def is now emitted for every
//	    widget in a package (e.g. Charts.mpk → BarChart/PieChart/…), not just
//	    the first. Bump forces existing projects to regenerate and pick up the
//	    previously-missing widgets (#679).
//	6 — DataGrid column `columnClass` ← `DynamicCellClass` alias. Bump forces
//	    existing projects to regenerate so the per-cell dynamic class is no
//	    longer silently dropped on write (Bug 10a).
//	7 — object-list ItemProperties now record their widget.xml `dataSource`
//	    binding, so the engine can emit an empty Forms$ClientTemplate for a
//	    VISIBLE texttemplate sub-property (chart series staticName / active
//	    static·/dynamic· names) instead of a null that trips CE0463 (Bug 9a).
//	8 — object-list ItemProperties record their enumeration member keys
//	    (enumValues), so `check` can flag an invalid enum value (MDL-WIDGET08)
//	    instead of Studio Pro silently defaulting it (e.g. a Maps marker
//	    locationType outside {address, latlng}).
//	9 — HeatMap scaleColors `colour` ← `ColorValue` alias. Bump forces existing
//	    projects to regenerate so a scale colour is no longer silently dropped
//	    on write (Bug 10a class).
//	10 — widget-level named-property aliases + emitted `seriesName` texttemplate
//	    for PieChart/HeatMap (item 1b): `ValueAttribute`→`seriesValueAttribute`,
//	    `SeriesName`→`seriesName`. Bump forces regeneration to carry the aliases.
//	11 — emit a texttemplate PropertyMapping for EVERY top-level texttemplate
//	    property (not just hand-aliased ones), so captions like Badge `value`,
//	    TreeNode `headerCaption`, and Timeline `title`/`description` are authorable
//	    instead of being silently dropped (MDL-WIDGET01). Bump forces existing
//	    projects to regenerate their widget defs with the new mappings.
//	12 — merge the hand-authored property-visibility fallback with the
//	    editorConfig-extracted rules instead of overwriting, so compound/ternary
//	    guards the static extractor skips (e.g. Timeline title/description hidden
//	    when customVisualization) still null their hidden textTemplates (CE0463).
//	13 — emit an `action` PropertyMapping for `type="action"` properties that MDL
//	    can author (`onClick`→the widget Action, `onChange`→OnChange). Previously
//	    no action operation was ever generated, so the writer had no mapping and
//	    silently dropped a widget-level action (e.g. DataGrid2 `onClick`). Bump
//	    forces existing projects to regenerate their defs with the action mapping.
//	14 — populate KnownProperties with every declared property that has no mapping
//	    in the generated def, so the checker warns "recognized but not persisted"
//	    instead of silently dropping or falsely rejecting it (general guard for the
//	    ledger #67 class). Bump forces regeneration to carry the new field.
//	15 — match an action slot after stripping one `Event`/`Action` suffix, so
//	    Mendix's own suffixed slots map (Combobox `onChangeEvent`). Version 13
//	    matched the bare keys only, so `OnChange:` on a combobox emitted no
//	    mapping and was dropped with no error (FINDINGS #14). Bump forces
//	    regeneration so existing projects pick up the suffixed slots.
//	16 — lift the object-list-nested hide rules from editorConfig.js, and fix the
//	    polarity of a comparison guard read from a `||` connector or a ternary's
//	    else branch (it was recorded as `eq` where the code means `ne`). Without
//	    the nested rules an Accordion group's `initialCollapsedState` could be set
//	    to a value the widget hides, which mxbuild rejects with CE0463 and which
//	    makes `mx create-module-package` refuse the module (upstream #931). Bump
//	    forces existing projects to regenerate their defs with both.
const WidgetDefGeneratorVersion = 17

// WidgetDefinition describes how to construct a pluggable widget from MDL syntax.
// Loaded from embedded JSON definition files (*.def.json).
type WidgetDefinition struct {
	WidgetID           string                       `json:"widgetId"`
	MDLName            string                       `json:"mdlName"`
	WidgetKind         string                       `json:"widgetKind,omitempty"` // "pluggable" (React) or "custom" (legacy Dojo)
	TemplateFile       string                       `json:"templateFile"`
	DefaultEditable    string                       `json:"defaultEditable"`
	GeneratorVersion   int                          `json:"generatorVersion,omitempty"` // WidgetDefGeneratorVersion at generation time; 0/absent = pre-stamp
	PropertyMappings   []PropertyMapping            `json:"propertyMappings,omitempty"`
	ChildSlots         []ChildSlotMapping           `json:"childSlots,omitempty"`
	ObjectLists        []ObjectListMapping          `json:"objectLists,omitempty"`
	PropertyVisibility []types.WidgetVisibilityRule `json:"propertyVisibility,omitempty"`
	Modes              []WidgetMode                 `json:"modes,omitempty"`
	// KnownProperties lists real widget properties that the .def.json does not
	// (yet) map to a write path. `check` recognizes them so they aren't flagged
	// as unknown, but the engine does not persist them — setting a non-default
	// value yields an MDL-WIDGET04 warning rather than a false MDL-WIDGET01
	// error. Validation-only; never written to BSON. See issue #643.
	KnownProperties []string `json:"knownProperties,omitempty"`
}

// PropertyMapping maps an MDL source (attribute, association, literal, etc.)
// to a pluggable widget property key via a named operation.
type PropertyMapping struct {
	PropertyKey string `json:"propertyKey"`
	Source      string `json:"source,omitempty"`
	Value       string `json:"value,omitempty"`
	Operation   string `json:"operation"`
	Default     string `json:"default,omitempty"`
	// Description is the human-readable text from the .mpk's widget XML
	// (PropertyDef.Description). Populated by GenerateDefJSON; surfaced by
	// the LSP on property hover. Optional — older .def.json files without
	// this field still load fine.
	Description string `json:"description,omitempty"`
	// MdlAliases lists alternative MDL property names that resolve to this
	// widget-level property. Used for named attribute/texttemplate properties
	// where the friendly MDL keyword differs from the schema key (e.g. a
	// PieChart's `ValueAttribute:` fills `seriesValueAttribute`). Without an
	// alias, a widget with several attribute-typed properties can't route the
	// right MDL value to each — the generic single `Attribute:` keyword is
	// ambiguous. Mirrors ItemPropertyMapping.MdlAliases.
	MdlAliases []string `json:"mdlAliases,omitempty"`
}

// WidgetMode defines a conditional configuration variant for a widget.
// For example, ComboBox has "enumeration" and "association" modes.
// Modes are evaluated in order; the first matching condition wins.
// A mode with no condition acts as the default fallback.
type WidgetMode struct {
	Name             string             `json:"name,omitempty"`
	Condition        string             `json:"condition,omitempty"`
	Description      string             `json:"description,omitempty"`
	PropertyMappings []PropertyMapping  `json:"propertyMappings"`
	ChildSlots       []ChildSlotMapping `json:"childSlots,omitempty"`
}

// ChildSlotMapping maps an MDL child container (e.g., TEMPLATE, FILTER) to a
// widget property that holds child widgets.
type ChildSlotMapping struct {
	PropertyKey  string `json:"propertyKey"`
	MDLContainer string `json:"mdlContainer"`
	Operation    string `json:"operation"`
}

// ObjectListMapping maps an MDL child block keyword (e.g., GROUP, ITEM, SERIES)
// to a pluggable widget property whose value is a list of structured objects
// (Type: "Object" + IsList: true in the widget XML).
//
// Each list item has its own sub-property tree, expressed via ItemProperties.
// ItemProperties supports the same operation kinds as top-level PropertyMapping
// and ChildSlotMapping (primitive, attribute, datasource, widgets, texttemplate,
// expression, action), as well as nested object lists.
type ObjectListMapping struct {
	PropertyKey    string                `json:"propertyKey"`
	MDLContainer   string                `json:"mdlContainer"`
	ItemProperties []ItemPropertyMapping `json:"itemProperties,omitempty"`
	ItemSlots      []ItemSlotMapping     `json:"itemSlots,omitempty"`
}

// ItemPropertyMapping maps a property of one object-list item (e.g. headerText
// of an Accordion group) to its operation kind. Mirrors PropertyMapping but
// scoped to the list item rather than the top-level widget.
//
// MdlAliases lists alternative MDL property names that resolve to this same
// schema property. Used for editorial conventions where the MDL keyword
// differs from the .mpk schema name (e.g. DataGrid column `Caption:` maps
// to schema property `header`).
type ItemPropertyMapping struct {
	PropertyKey string   `json:"propertyKey"`
	Source      string   `json:"source,omitempty"`
	Value       string   `json:"value,omitempty"`
	Operation   string   `json:"operation"`
	Default     string   `json:"default,omitempty"`
	Description string   `json:"description,omitempty"`
	MdlAliases  []string `json:"mdlAliases,omitempty"`
	// EnumValues lists the valid member keys for an enumeration sub-property
	// (e.g. a Maps marker `locationType` accepts address/latlng). `check` flags
	// a value outside this set (MDL-WIDGET08) — Studio Pro silently defaults an
	// invalid enum value, which is why chart/Maps sub-properties fail quietly.
	EnumValues []string `json:"enumValues,omitempty"`
	// DataSource is the widget.xml `dataSource="..."` binding, if any (e.g. a
	// chart series `staticTooltipHoverText` is bound to `staticDataSource`). It
	// drives object-list-item visibility: a texttemplate sub-property is
	// "visible" — and must serialize an empty Forms$ClientTemplate rather than a
	// null (else CE0463) — when it has no dataSource binding OR its bound
	// datasource is configured on the item. Chart series (9a).
	DataSource string `json:"dataSource,omitempty"`
}

// ItemSlotMapping maps a widget child slot inside one object-list item
// (e.g. headerContent of an Accordion group, content of a DataGrid column).
// Mirrors ChildSlotMapping but scoped to the list item.
//
// AcceptedChildTypes lists MDL widget Type keywords (lowercase) that route
// to this slot when they appear directly inside the item body without an
// explicit MDLContainer wrapper. Used for editorial conventions where the
// user types `column foo { textfilter ... }` and expects the textfilter
// in the column's `filter` slot — not the default `content` slot.
type ItemSlotMapping struct {
	PropertyKey        string   `json:"propertyKey"`
	MDLContainer       string   `json:"mdlContainer"`
	Operation          string   `json:"operation"`
	AcceptedChildTypes []string `json:"acceptedChildTypes,omitempty"`
}

// BuildContext carries resolved values from MDL parsing for use by operations.
type BuildContext struct {
	AttributePath  string
	AttributePaths []string // For operations that process multiple attributes
	AssocPath      string
	EntityName     string
	PrimitiveVal   string
	DataSource     pages.DataSource
	Action         pages.ClientAction // Domain-typed client action
	// ClientParams carries the `contentparams:` bindings for a `{1}`-style
	// template, resolved while the AST widget is still in hand. applyOperation
	// does not receive the AST, and a numeric placeholder written without its
	// parameters is CE0720 (#928).
	ClientParams []*pages.ClientTemplateParameter
	pageBuilder  *pageBuilder
}

// =============================================================================
// Pluggable Widget Engine
// =============================================================================

// PluggableWidgetEngine builds CustomWidget instances from WidgetDefinition + AST.
type PluggableWidgetEngine struct {
	backend     backend.WidgetBuilderBackend
	pageBuilder *pageBuilder

	// outerEntityContext is the entity context as it stood when the current
	// widget's Build started, before any of its own DataSource mappings moved
	// pageBuilder.entityContext to the widget's own data (e.g. a ComboBox's
	// option list). A property that names something on the *containing* data —
	// an association the widget binds — must be qualified against this, not
	// against the widget's own datasource entity. (issuetracker #19)
	outerEntityContext string

	// currentDef is the widget definition of the build in progress. resolveMapping
	// consults it to tell the widget's PRIMARY attribute property from its others
	// (#238); nil outside a build.
	currentDef *WidgetDefinition

	// currentModeDataSourceCount is how many PropertyMappings in the selected
	// mode's mappings have Source == "DataSource". resolveMapping's "DataSource"
	// case consults it to decide whether an unnamed generic `DataSource:` is a
	// safe fallback for a mapping the script left unnamed: safe for a
	// single-datasource widget, wrong for a multi-source one, where falling back
	// would silently duplicate one datasource's binding into every unnamed slot.
	currentModeDataSourceCount int
}

// NewPluggableWidgetEngine creates a new engine with the given backend and page builder.
func NewPluggableWidgetEngine(b backend.WidgetBuilderBackend, pb *pageBuilder) *PluggableWidgetEngine {
	return &PluggableWidgetEngine{
		backend:     b,
		pageBuilder: pb,
	}
}

// Build constructs a CustomWidget from a definition and AST widget node.
func (e *PluggableWidgetEngine) Build(def *WidgetDefinition, w *ast.WidgetV3) (*pages.CustomWidget, error) {
	// Save and restore entity context (DataSource mappings may change it)
	oldEntityContext := e.pageBuilder.entityContext
	oldContextVar := e.pageBuilder.contextVarName
	oldContextKnown := e.pageBuilder.contextKnown
	defer func() {
		e.pageBuilder.entityContext = oldEntityContext
		e.pageBuilder.contextVarName = oldContextVar
		e.pageBuilder.contextKnown = oldContextKnown
	}()

	// Remember the containing context for properties that name members of it
	// rather than of this widget's own data. Saved/restored for nested widgets.
	oldOuterEntityContext := e.outerEntityContext
	e.outerEntityContext = oldEntityContext
	defer func() { e.outerEntityContext = oldOuterEntityContext }()

	// The definition being built, for mapping decisions that need to see the
	// widget's OTHER mappings (which attribute property a bare `Attribute:`
	// fills). Saved/restored like the context above, for nested widgets.
	oldDef := e.currentDef
	e.currentDef = def
	defer func() { e.currentDef = oldDef }()

	// 1. Load template via backend
	builder, err := e.backend.LoadWidgetTemplate(def.WidgetID, e.pageBuilder.getProjectPath())
	if err != nil {
		return nil, mdlerrors.NewBackend("load "+def.MDLName+" template", err)
	}
	if builder == nil {
		return nil, mdlerrors.NewNotFound("template", def.MDLName)
	}

	propertyTypeIDs := builder.PropertyTypeIDs()

	// 2. Select mode and get mappings/slots
	mappings, slots, err := e.selectMappings(def, w)
	if err != nil {
		return nil, err
	}

	oldModeDataSourceCount := e.currentModeDataSourceCount
	e.currentModeDataSourceCount = 0
	for _, m := range mappings {
		if m.Source == "DataSource" {
			e.currentModeDataSourceCount++
		}
	}
	defer func() { e.currentModeDataSourceCount = oldModeDataSourceCount }()

	// 3. Apply property mappings.
	//
	// A property the widget's editorConfig hides under the current configuration
	// is written at its DECLARED DEFAULT. Measured on a Studio Pro-authored File
	// Uploader 2.5.0: all 34 declared properties are stored, the hidden ones at
	// their default, so "hidden" means default-valued, not absent.
	//
	// Writing the default rather than merely skipping the mapping is the whole
	// point: skipping leaves the widget TEMPLATE's captured value, and a template
	// holds whatever the widget it was extracted from was set to. Image's is
	// width/height 48 against a declared default of 100, which made every Image
	// mxcli authored fail with CE0463 — see hiddenUnnamedProperties. Where no
	// default can be looked up (a datasource has none) the mapping is skipped,
	// exactly as before.
	//
	// This only ever fires for a property the script did NOT name — an MDL
	// keyword shared by several properties (File Uploader routes both
	// `associatedFiles` and `associatedImages` from `DataSource:`, gated on
	// `uploadMode`). Naming a hidden property outright is still an error, raised
	// by MDL-WIDGET10 at check time rather than silently dropped here (#956).
	//
	// builder.PrimitiveValues() is read HERE, before any mapping is applied, so
	// it is the template's captured configuration — the values an unmapped
	// property will actually be stored with. A rule keyed on one of those has to
	// be evaluated against them; see hiddenUnnamedProperties.
	hiddenSkip := e.hiddenUnnamedProperties(def, w,
		widgetPropertyDefaults(e.pageBuilder.getProjectPath(), def.WidgetID),
		builder.PrimitiveValues())
	for _, mapping := range mappings {
		if reset, hidden := hiddenSkip[strings.ToLower(mapping.PropertyKey)]; hidden {
			if reset != "" && mapping.Operation == "primitive" {
				builder.SetPrimitive(mapping.PropertyKey, reset)
			}
			continue
		}
		ctx, err := e.resolveMapping(mapping, w)
		if err != nil {
			return nil, mdlerrors.NewBackend("resolve mapping for "+mapping.PropertyKey, err)
		}

		if err := e.applyOperation(builder, mapping.Operation, mapping.PropertyKey, ctx); err != nil {
			return nil, err
		}
	}
	// A hidden property that MDL cannot name gets its declared default too. The
	// loop above visits property MAPPINGS — which is what gives a property an MDL
	// keyword — so it reached `width` and `height` and never `maxHeight`, whose
	// value stayed at whatever the template captured. That single field is the
	// whole of the CE0463 on a copied Atlas layout: one line differing in 1480,
	// mxcli's 0 against the package's declared 250 (mxcli-ledger §142).
	//
	// The set of properties that must be default-valued is the widget's to decide,
	// not mxcli's; making it a subset of what MDL has words for was the mistake.
	for propKey, reset := range unmappedHiddenResets(def, e.visibilityRules(def), hiddenSkip) {
		builder.SetPrimitive(propKey, reset)
	}

	// 4. Auto datasource: map AST DataSource to first DataSource-type property.
	// This must run before child slots so that entityContext is available
	// for child widgets that depend on the parent's data source.
	dsHandledByMapping := false
	for _, m := range mappings {
		if m.Source == "DataSource" {
			dsHandledByMapping = true
			break
		}
	}
	if !dsHandledByMapping {
		if ds := w.GetDataSource(); ds != nil {
			for propKey, entry := range propertyTypeIDs {
				if entry.ValueType == "DataSource" {
					dataSource, entityName, err := e.pageBuilder.buildDataSourceV3(ds)
					if err != nil {
						return nil, mdlerrors.NewBackend("auto datasource for "+propKey, err)
					}
					builder.SetDataSource(propKey, dataSource)
					if entityName != "" {
						e.pageBuilder.entityContext = entityName
						e.pageBuilder.contextVarName = contextVarFor(ds)
						e.pageBuilder.contextKnown = true
					}
					break
				}
			}
		}
	}

	// 4.0 Refuse a child none of the passes below can place. Each of them skips
	// what it does not recognise, so without this the child is built and thrown
	// away — a page that writes, builds and renders without the widget the
	// author put there. See widget_unrouted_children.go.
	if err := refuseUnroutedChildren(def, w); err != nil {
		return nil, err
	}

	// 4.1 Apply child slots (.def.json) — skip children whose keyword belongs
	// to an objectLists mapping (handled by applyObjectLists below).
	objectListContainers := make(map[string]bool, len(def.ObjectLists))
	for _, ol := range def.ObjectLists {
		objectListContainers[strings.ToUpper(ol.MDLContainer)] = true
	}
	if err := e.applyChildSlots(builder, slots, w, propertyTypeIDs, objectListContainers); err != nil {
		return nil, err
	}

	// 4.1b Apply object-list child blocks (.def.json `objectLists`).
	// Children whose Type matches an objectLists[].MDLContainer are routed
	// through the object-list builder rather than treated as nested widgets.
	if err := e.applyObjectLists(builder, def.ObjectLists, w); err != nil {
		return nil, err
	}

	// 4.3 Auto child slots: match AST children to Widgets-type template properties.
	handledSlotKeys := make(map[string]bool)
	for _, s := range slots {
		handledSlotKeys[s.PropertyKey] = true
	}
	// objectListContainers (computed above before applyChildSlots) is reused
	// here so the auto-widgets-discovery passes below skip object-list children.
	var widgetsPropKeys []string
	for propKey, entry := range propertyTypeIDs {
		if entry.ValueType == "Widgets" && !handledSlotKeys[propKey] {
			widgetsPropKeys = append(widgetsPropKeys, propKey)
		}
	}
	sort.Strings(widgetsPropKeys)
	// Phase 1: Named matching — match children by name against property keys
	matchedChildren := make(map[int]bool)
	// Mark object-list children as already handled — applyObjectLists owns them.
	for i, child := range w.Children {
		if objectListContainers[strings.ToUpper(child.Type)] {
			matchedChildren[i] = true
		}
	}
	for _, propKey := range widgetsPropKeys {
		upperKey := strings.ToUpper(propKey)
		for i, child := range w.Children {
			if matchedChildren[i] {
				continue
			}
			if strings.ToUpper(child.Name) == upperKey {
				var childWidgets []pages.Widget
				for _, slotChild := range child.Children {
					widget, err := e.pageBuilder.buildWidgetV3(slotChild)
					if err != nil {
						return nil, err
					}
					if widget != nil {
						childWidgets = append(childWidgets, widget)
					}
				}
				if len(childWidgets) > 0 {
					builder.SetChildWidgets(propKey, childWidgets)
					handledSlotKeys[propKey] = true
				}
				matchedChildren[i] = true
				break
			}
		}
	}
	// Phase 2: Default slot — unmatched direct children go to first unmatched Widgets property.
	defSlotContainers := make(map[string]bool)
	for _, s := range slots {
		defSlotContainers[strings.ToUpper(s.MDLContainer)] = true
	}
	var defaultWidgets []pages.Widget
	for i, child := range w.Children {
		if matchedChildren[i] {
			continue
		}
		if len(slots) > 0 {
			continue // applyChildSlots handles both container and direct children
		}
		if defSlotContainers[strings.ToUpper(child.Type)] {
			continue
		}
		widget, err := e.pageBuilder.buildWidgetV3(child)
		if err != nil {
			return nil, err
		}
		if widget != nil {
			defaultWidgets = append(defaultWidgets, widget)
		}
	}
	if len(defaultWidgets) > 0 {
		for _, propKey := range widgetsPropKeys {
			if !handledSlotKeys[propKey] {
				builder.SetChildWidgets(propKey, defaultWidgets)
				break
			}
		}
	}

	// 4.6 Apply explicit properties (not covered by .def.json mappings)
	mappedKeys := mappedWidgetPropertyNames(mappings, slots)
	for propName, propVal := range w.Properties {
		if mappedKeys[strings.ToLower(propName)] || isBuiltinPropName(propName) {
			continue
		}
		entry, ok := propertyTypeIDs[propName]
		if !ok {
			continue // not a known widget property key
		}
		// Convert non-string values (bool, int, float) to string for property setting
		var strVal string
		switch v := propVal.(type) {
		case string:
			strVal = v
		case bool:
			strVal = fmt.Sprintf("%t", v)
		case int:
			strVal = fmt.Sprintf("%d", v)
		case float64:
			strVal = fmt.Sprintf("%g", v)
		default:
			continue
		}

		// Route by ValueType when available
		switch entry.ValueType {
		case "Expression":
			builder.SetExpression(propName, strVal)
		case "TextTemplate":
			// `contentparams:` supplies the parameters for a `{1}`-style template.
			// Without this branch the numeric spelling had no route on a pluggable
			// widget — the template was written with an empty parameter list and
			// mxbuild answered CE0720. The named `{AttrName}` spelling keeps its
			// own path, which derives parameters from the entity context. (#928)
			if params := e.pageBuilder.buildClientTemplateParams(w.GetContentParams()); len(params) > 0 &&
				numericTemplatePlaceholderRe.MatchString(strVal) {
				builder.SetTextTemplateWithClientParams(propName, strVal, params)
				break
			}
			entityCtx := e.pageBuilder.entityContext
			builder.SetTextTemplateWithParams(propName, strVal, entityCtx)
		case "Attribute":
			attrPath := ""
			if strings.Count(strVal, ".") >= 2 {
				attrPath = strVal
			} else if e.pageBuilder.entityContext != "" {
				attrPath = e.pageBuilder.resolveAttributePath(strVal)
			}
			if attrPath != "" {
				builder.SetAttribute(propName, attrPath)
			}
		default:
			// Known non-attribute types: always use primitive
			if entry.ValueType != "" && entry.ValueType != "Attribute" {
				builder.SetPrimitive(propName, strVal)
				continue
			}
			// Legacy routing for properties without ValueType info
			if strings.Count(strVal, ".") >= 2 {
				builder.SetAttribute(propName, strVal)
			} else if e.pageBuilder.entityContext != "" && !strings.ContainsAny(strVal, " '\"") {
				builder.SetAttribute(propName, e.pageBuilder.resolveAttributePath(strVal))
			} else {
				builder.SetPrimitive(propName, strVal)
			}
		}
	}

	// 4.9 Auto-populate required empty object lists
	builder.EnsureRequiredObjectLists()

	// 4.10 Apply property-visibility rules: a TextTemplate property that the
	// widget's editorConfig.js hides under the current configuration must emit
	// TextTemplate: null, not the template's populated default (CE0463, #574).
	// Rules come from the .def.json (hand-authored/generated); when it carries
	// none — as for built-in widgets like DataGrid2, which the .def.json
	// generator skips — lift them on the fly from the installed .mpk's
	// editorConfig.js (#574 Phase 2), so version-specific applicability is
	// honoured without a hand-maintained table.
	visibility := def.PropertyVisibility
	if len(visibility) == 0 {
		visibility = resolveWidgetVisibilityRules(e.pageBuilder.getProjectPath(), def.WidgetID)
	}
	if len(visibility) > 0 {
		builder.ApplyPropertyVisibility(visibility)
	}

	// 5. Build CustomWidget
	widgetID := model.ID(types.GenerateID())
	cw := builder.Finalize(widgetID, w.Name, w.GetLabel(), def.DefaultEditable)

	if err := e.pageBuilder.registerWidgetName(w.Name, cw.ID); err != nil {
		return nil, err
	}

	return cw, nil
}

// mappedWidgetPropertyNames returns every AST spelling consumed by the mapping
// pass. The explicit-property fallback must skip all of them or it will apply a
// named property twice, potentially under a different datasource context.
func mappedWidgetPropertyNames(mappings []PropertyMapping, slots []ChildSlotMapping) map[string]bool {
	mapped := make(map[string]bool)
	for _, mapping := range mappings {
		if mapping.Source != "" {
			mapped[strings.ToLower(mapping.Source)] = true
		}
		if mapping.PropertyKey != "" {
			mapped[strings.ToLower(mapping.PropertyKey)] = true
		}
		for _, alias := range mapping.MdlAliases {
			mapped[strings.ToLower(alias)] = true
		}
	}
	for _, slot := range slots {
		mapped[strings.ToLower(slot.MDLContainer)] = true
	}
	return mapped
}

// isPrimaryAttributeMapping reports whether mapping is the one a bare
// `Attribute:` should fill: the FIRST attribute-typed mapping in the definition,
// which is the widget's primary attribute (GenerateDefJSON preserves the widget
// XML's property order, and a widget declares its main attribute first —
// verified on Slider, RangeSlider, StarRating and ComboBox).
//
// A widget with exactly one attribute property is unaffected, which is the case
// the bare keyword was written for.
func (e *PluggableWidgetEngine) isPrimaryAttributeMapping(mapping PropertyMapping) bool {
	def := e.currentDef
	if def == nil {
		return true // no definition to compare against — behave as before
	}
	for _, m := range def.PropertyMappings {
		if m.Operation == "attribute" || m.Source == "Attribute" {
			return m.PropertyKey == mapping.PropertyKey
		}
	}
	return true
}

// hiddenUnnamedProperties returns the widget properties that are hidden under
// the widget's current configuration AND were not named by the script — i.e.
// reached only through an MDL keyword that several properties share. Writing
// into one of those is CE0463; writing into a hidden property the script named
// explicitly is reported by MDL-WIDGET10 instead, so it is deliberately not
// included here.
//
// The KEY's presence means "hidden". The VALUE is the property's DECLARED
// default, which the caller must write, or "" when no default could be looked
// up — mxcli does not invent one.
//
// Skipping the property instead leaves the widget TEMPLATE's captured value in
// place, and a template captures whatever the widget it was extracted from
// happened to be set to. For the Image widget that is width/height 48 against a
// declared default of 100, so every Image mxcli authored failed the build with
// CE0463 — while mxcli's own MDL-WIDGET10 said, in as many words, that a hidden
// `width` must be "100" (mxcli-formula1 FINDINGS §69/§142). The invariant is
// default-VALUED, not skipped; the two only coincide when the template is
// already at the default.
//
// defaults is the declared-default map from widgetPropertyDefaults — the same
// source MDL-WIDGET10 reads, so the writer and the checker cannot disagree about
// what a default is, which is how this shipped.
//
// stored is the TEMPLATE's captured configuration, read before any mapping was
// applied. It is what answers a rule keyed on a property MDL cannot name; see
// the fallback chain below.
//
// Rules come from the .def.json, falling back to a live lift from the installed
// .mpk (the same two sources the visibility application uses).
func (e *PluggableWidgetEngine) hiddenUnnamedProperties(def *WidgetDefinition, w *ast.WidgetV3, defaults, stored map[string]string) map[string]string {
	rules := e.visibilityRules(def)
	if len(rules) == 0 {
		return nil
	}
	values, explicit := widgetValueMap(w, def)
	out := map[string]string{}
	for _, rule := range rules {
		if rule.Nested() || rule.HiddenWhen == nil {
			continue
		}
		key := strings.ToLower(rule.PropertyKey)
		if explicit[key] {
			continue // named by the script — MDL-WIDGET10's business, not ours
		}
		condKey := strings.ToLower(rule.HiddenWhen.PropertyKey)
		condVal, known := values[condKey]
		if !known || condVal == "" {
			// widgetValueMap only knows properties the definition MAPS, because a
			// mapping is what gives a property an MDL keyword. A rule whose
			// condition is an UNMAPPED property was therefore always
			// indeterminable and never fired — which is how `maxHeight` (hidden
			// when `maxHeightUnit` is "none") kept the template's value and
			// produced the one differing field in 1480 on a copied Atlas layout
			// (mxcli-ledger §142).
			//
			// The TEMPLATE's captured value is the answer, and the declared
			// default is NOT: the question is whether the property will be hidden
			// in the document about to be WRITTEN, and an unmapped property is
			// written with whatever the template holds. The two differ exactly
			// where it matters — Image declares `maxHeightUnit` "pixels" and the
			// template captured "none", so reading the default concluded
			// "visible" and left `maxHeight` at the template's 0 against a
			// declared 250, which is the whole of §142's CE0463. Both are
			// fallbacks and not preferences: a value the script set, or a
			// mapping's own default, still wins above.
			if v, ok := stored[rule.HiddenWhen.PropertyKey]; ok && v != "" {
				condVal, known = v, true
			} else {
				condVal, known = defaults[defaultsKey("", rule.HiddenWhen.PropertyKey)]
			}
			if !known || condVal == "" {
				continue // still indeterminable — never guess
			}
		}
		if firesUnder(rule, condVal, values, stored, defaults) {
			out[key] = defaults[defaultsKey("", rule.PropertyKey)]
		}
	}
	return out
}

// firesUnder evaluates every term of a rule's conjunction, resolving each the
// same way the first term was resolved above: the widget's mapped values, then
// the stored template, then the declared default. firstVal is the already
// resolved value of the first term, so that work is not repeated.
//
// A term that stays indeterminable makes the whole rule not fire — the
// serializer never guesses, which is why an unresolvable condition leaves the
// template's value alone.
func firesUnder(rule types.WidgetVisibilityRule, firstVal string, values, stored, defaults map[string]string) bool {
	first := true
	fires, determinable := rule.Fires(func(c types.WidgetVisibilityCondition) (string, bool) {
		if first {
			first = false
			return firstVal, true
		}
		if v, ok := values[c.PropertyKey]; ok && v != "" {
			return v, true
		}
		if v, ok := stored[c.PropertyKey]; ok && v != "" {
			return v, true
		}
		v, ok := defaults[defaultsKey("", c.PropertyKey)]
		if !ok || v == "" {
			return "", false
		}
		return v, true
	})
	return determinable && fires
}

// visibilityRules is the widget's editorConfig visibility rules: from the
// .def.json when it carries them, otherwise a live lift from the installed .mpk.
// Both consumers must use the same list — reading the .def.json field directly
// gets an EMPTY one for every widget whose rules are lifted, which is most of
// them, and a lookup keyed on it then silently finds nothing.
func (e *PluggableWidgetEngine) visibilityRules(def *WidgetDefinition) []types.WidgetVisibilityRule {
	if len(def.PropertyVisibility) > 0 {
		return def.PropertyVisibility
	}
	return resolveWidgetVisibilityRules(e.pageBuilder.getProjectPath(), def.WidgetID)
}

// unmappedHiddenResets returns the hidden properties that the property-mapping
// loop will not reach, keyed by the property key as the widget declares it (the
// hidden map is lower-cased; a builder needs the real spelling, which is what
// rules carries).
//
// Only properties with a declared default are returned — where none could be
// looked up there is nothing to write, and mxcli does not invent one. That is
// also what keeps #956's File Uploader datasource pruning unchanged: a
// datasource has no default.
//
// The mapped ones are excluded rather than merged: the loop already writes them,
// and writing a second value for one property is its own defect.
func unmappedHiddenResets(def *WidgetDefinition, rules []types.WidgetVisibilityRule, hidden map[string]string) map[string]string {
	if len(hidden) == 0 {
		return nil
	}
	mapped := make(map[string]bool, len(def.PropertyMappings))
	for _, m := range def.PropertyMappings {
		mapped[strings.ToLower(m.PropertyKey)] = true
	}
	for _, mode := range def.Modes {
		for _, m := range mode.PropertyMappings {
			mapped[strings.ToLower(m.PropertyKey)] = true
		}
	}
	out := map[string]string{}
	for _, rule := range rules {
		key := strings.ToLower(rule.PropertyKey)
		if mapped[key] {
			continue
		}
		reset, isHidden := hidden[key]
		if !isHidden || reset == "" {
			continue
		}
		out[rule.PropertyKey] = reset
	}
	return out
}

// templateAttrPlaceholderRe matches `{AttrName}` placeholders in a text
// template. Numeric parameter references (`{1}`) don't match and pass through
// verbatim.
var templateAttrPlaceholderRe = regexp.MustCompile(`\{[A-Za-z][A-Za-z0-9_]*\}`)

// applyOperation dispatches a named operation to the corresponding builder method.
func (e *PluggableWidgetEngine) applyOperation(builder backend.WidgetObjectBuilder, opName string, propKey string, ctx *BuildContext) error {
	switch opName {
	case "attribute":
		builder.SetAttribute(propKey, ctx.AttributePath)
	case "association":
		builder.SetAssociation(propKey, ctx.AssocPath, ctx.EntityName)
	case "primitive":
		builder.SetPrimitive(propKey, ctx.PrimitiveVal)
	case "selection":
		builder.SetSelection(propKey, ctx.PrimitiveVal)
	case "image":
		// An image collection entry, by its three-part qualified name. The
		// value arrives through the generic source branch, so it is in
		// PrimitiveVal like any other scalar — only the key it lands on differs.
		builder.SetImage(propKey, ctx.PrimitiveVal)
	case "expression":
		builder.SetExpression(propKey, ctx.PrimitiveVal)
	case "datasource":
		builder.SetDataSource(propKey, ctx.DataSource)
	case "widgets":
		// ctx doesn't carry child widgets for this path — handled by applyChildSlots
	case "texttemplate":
		// No MDL value provided: keep the template's default ClientTemplate
		// (the widget's shipped caption, or null where the widget's editorConfig
		// hides it) rather than overwriting it with an empty template. This lets
		// GenerateDefJSON emit a mapping for every texttemplate property (so any
		// caption is authorable) without nulling the defaults of the ones the user
		// leaves unset.
		if ctx.PrimitiveVal == "" {
			return nil
		}
		// A `{AttrName}` placeholder needs ClientTemplate parameters resolved
		// against the entity context — plain SetTextTemplate would emit the
		// braces literally, which Studio Pro's translatable-text parser rejects
		// ("Brace should be followed by a number of digits"). Placeholder-less
		// text keeps the SetTextTemplate path so backend output is unchanged.
		// `contentparams:` supplies the parameters for a `{1}`-style template.
		// The explicit-property pass has routed this since #928; the MAPPING pass
		// did not, so the same text authored through a mapped property key was
		// written with an empty parameter list and mxbuild answered CE0720. The
		// gap was unreachable while such text was being dropped altogether
		// (#254) — fixing the drop is what exposes it.
		switch {
		case len(ctx.ClientParams) > 0 && numericTemplatePlaceholderRe.MatchString(ctx.PrimitiveVal):
			builder.SetTextTemplateWithClientParams(propKey, ctx.PrimitiveVal, ctx.ClientParams)
		case templateAttrPlaceholderRe.MatchString(ctx.PrimitiveVal):
			builder.SetTextTemplateWithParams(propKey, ctx.PrimitiveVal, e.pageBuilder.entityContext)
		default:
			builder.SetTextTemplate(propKey, ctx.PrimitiveVal)
		}
	case "action":
		builder.SetAction(propKey, ctx.Action)
	case "attributeObjects":
		builder.SetAttributeObjects(propKey, ctx.AttributePaths)
	default:
		return mdlerrors.NewValidationf("unknown operation %q for property %s", opName, propKey)
	}
	return nil
}

// selectMappings selects the active PropertyMappings and ChildSlotMappings based on mode.
func (e *PluggableWidgetEngine) selectMappings(def *WidgetDefinition, w *ast.WidgetV3) ([]PropertyMapping, []ChildSlotMapping, error) {
	if len(def.Modes) == 0 {
		return def.PropertyMappings, def.ChildSlots, nil
	}

	var fallback *WidgetMode
	var fallbackCount int
	for i := range def.Modes {
		mode := &def.Modes[i]
		if mode.Condition == "" {
			fallbackCount++
			if fallback == nil {
				fallback = mode
			}
			continue
		}
		if e.evaluateCondition(mode.Condition, w, mode.PropertyMappings) {
			return mode.PropertyMappings, mode.ChildSlots, nil
		}
	}

	if fallback != nil {
		if fallbackCount > 1 {
			return nil, nil, mdlerrors.NewValidationf("widget %s has %d modes without conditions; only one default mode is allowed", def.MDLName, fallbackCount)
		}
		return fallback.PropertyMappings, fallback.ChildSlots, nil
	}

	return nil, nil, mdlerrors.NewValidationf("no matching mode for widget %s", def.MDLName)
}

// evaluateCondition checks a built-in condition string against the AST widget.
func (e *PluggableWidgetEngine) evaluateCondition(condition string, w *ast.WidgetV3, mappings []PropertyMapping) bool {
	switch {
	case condition == "hasDataSource":
		if w.GetDataSource() != nil {
			return true
		}
		// A mode that owns a named datasource mapping must activate when that
		// property's structured datasource is present. Looking at every AST
		// DataSourceV3 would misclassify named action slots: microflow/nanoflow
		// actions share that parser shape and are converted only by their mapping.
		for _, mapping := range mappings {
			if strings.EqualFold(mapping.Operation, "datasource") && namedDataSourceValue(mapping, w) != nil {
				return true
			}
		}
		return false
	case condition == "hasAttribute":
		return w.GetAttribute() != ""
	case strings.HasPrefix(condition, "hasProp:"):
		propName := strings.TrimPrefix(condition, "hasProp:")
		return w.GetStringProp(propName) != ""
	default:
		return false
	}
}

// namedPropValue returns the MDL value written for a mapping's property, matched
// by its PropertyKey or any registered MdlAlias (case-insensitive, via
// lookupProperty). Returns "" when the user didn't set it. Used to route several
// same-typed widget-level properties (e.g. a chart's ValueAttribute vs
// SortAttribute) to the right MDL keyword.
func namedPropValue(mapping PropertyMapping, w *ast.WidgetV3) string {
	if v, ok := lookupProperty(w.Properties, mapping.PropertyKey); ok {
		return stringifyAny(v)
	}
	for _, alias := range mapping.MdlAliases {
		if v, ok := lookupProperty(w.Properties, alias); ok {
			return stringifyAny(v)
		}
	}
	return ""
}

// namedDataSourceValue returns a datasource authored using the widget schema's
// own property key (or one of its aliases), for example:
//
//	primarySource: microflow Demo.DS_Primary
//	secondarySource: microflow Demo.DS_Secondary
//
// Keeping this separate from namedPropValue is important: stringifyAny would
// turn the structured datasource AST into text and lose its source type,
// arguments and constraints.
func namedDataSourceValue(mapping PropertyMapping, w *ast.WidgetV3) *ast.DataSourceV3 {
	if v, ok := lookupProperty(w.Properties, mapping.PropertyKey); ok {
		if ds, ok := v.(*ast.DataSourceV3); ok {
			return ds
		}
	}
	for _, alias := range mapping.MdlAliases {
		if v, ok := lookupProperty(w.Properties, alias); ok {
			if ds, ok := v.(*ast.DataSourceV3); ok {
				return ds
			}
		}
	}
	return nil
}

// resolveMapping resolves a PropertyMapping's source into a BuildContext.
func (e *PluggableWidgetEngine) resolveMapping(mapping PropertyMapping, w *ast.WidgetV3) (*BuildContext, error) {
	ctx := &BuildContext{pageBuilder: e.pageBuilder}

	if mapping.Value != "" {
		ctx.PrimitiveVal = mapping.Value
		// AST overrides the def.json default: when the user explicitly sets the
		// property in MDL (e.g. `PageSize: 25`), that value wins over the
		// schema default ("20"). Without this, user-set primitive properties
		// silently fall back to defaults.
		if astVal, ok := lookupProperty(w.Properties, mapping.PropertyKey); ok {
			ctx.PrimitiveVal = stringifyAny(astVal)
		}
		return ctx, nil
	}

	source := mapping.Source
	if source == "" {
		// A named action slot: no Source, addressed by the widget's own property
		// key. This is how every action slot but the click and change ones is
		// authored — `createFileAction: microflow M.ACT_CreateFile` (#956).
		if mapping.Operation == "action" {
			act, err := namedActionSlotValue(w, mapping.PropertyKey)
			if err != nil {
				return nil, err
			}
			if act != nil {
				built, err := e.pageBuilder.buildClientActionV3(act)
				if err != nil {
					return nil, mdlerrors.NewBackend("build action for "+mapping.PropertyKey, err)
				}
				ctx.Action = built
			}
		}
		return ctx, nil
	}

	switch source {
	case "Attribute":
		// Named widget-level attribute (e.g. PieChart `ValueAttribute` →
		// `seriesValueAttribute`): look up by the property's own name/aliases so
		// several attribute properties route correctly, and resolve against the
		// widget datasource entity (set by the DataSource mapping, which
		// GenerateDefJSON orders first). Fall back to the generic single
		// `Attribute:` keyword for single-attribute widgets (ComboBox, filters).
		attr := namedPropValue(mapping, w)
		if attr == "" && e.isPrimaryAttributeMapping(mapping) {
			// The bare `Attribute:` keyword names ONE attribute — the widget's
			// primary one. Applying it to every attribute-typed mapping wrote the
			// same AttributeRef into all of them: a Slider's `Attribute: Score`
			// landed on valueAttribute AND minAttribute, maxAttribute and
			// stepAttribute, which Studio Pro leaves unset unless the matching
			// *ValueType is "attribute" — and a value in a pruned slot is CE0463
			// (issue #238).
			//
			// The Slider is where this surfaced because its editorConfig computes
			// the hidden list from lookup tables —
			// `hidePropertiesIn(t,e,[].concat(n(v[e.minValueType]), …))` — with no
			// string literal to lift, so the visibility extractor produces NO rule
			// for those three and the hidden-property guard cannot catch it.
			// Not writing them in the first place does not depend on that data.
			attr = w.GetAttribute()
		}
		if attr != "" {
			// An association named where an attribute belongs cannot be stored;
			// refuse it here rather than writing a dangling AttributeRef (#830).
			if err := e.pageBuilder.rejectAssociationAsAttribute(
				attr, e.pageBuilder.entityContext,
				fmt.Sprintf("widget `%s` property `%s`", w.Name, mapping.PropertyKey),
			); err != nil {
				return nil, err
			}
			ctx.AttributePath = e.pageBuilder.resolveAttributePath(attr)
		}

	case "TextTemplate":
		// A required widget-level caption authored by a named MDL property
		// (e.g. PieChart `SeriesName: '...'` → `seriesName`). applyOperation
		// "texttemplate" writes ctx.PrimitiveVal as the ClientTemplate text.
		if v := namedPropValue(mapping, w); v != "" {
			ctx.PrimitiveVal = v
			if numericTemplatePlaceholderRe.MatchString(v) {
				ctx.ClientParams = e.pageBuilder.buildClientTemplateParams(w.GetContentParams())
			}
		}

	case "Attributes":
		if attrs := w.GetAttributes(); len(attrs) > 0 {
			ctx.AttributePaths = make([]string, 0, len(attrs))
			for _, attr := range attrs {
				ctx.AttributePaths = append(ctx.AttributePaths, e.pageBuilder.resolveAttributePath(attr))
			}
		}

	case "DataSource":
		// A widget may expose several independently named datasources. Prefer the
		// value authored for this mapping; keep the generic `datasource:` clause
		// as the backward-compatible fallback, but only for single-datasource
		// widgets. A mode with several DataSource mappings has no single
		// datasource the generic clause could mean, so falling back there would
		// silently copy one binding into every unnamed slot; each must be
		// addressed by its own schema key instead.
		ds := namedDataSourceValue(mapping, w)
		if ds == nil && e.currentModeDataSourceCount <= 1 {
			ds = w.GetDataSource()
		}
		if ds != nil {
			dataSource, entityName, err := e.pageBuilder.buildDataSourceV3(ds)
			if err != nil {
				return nil, mdlerrors.NewBackend("build datasource", err)
			}
			ctx.DataSource = dataSource
			ctx.EntityName = entityName
			if entityName != "" {
				e.pageBuilder.entityContext = entityName
				e.pageBuilder.contextVarName = contextVarFor(ds)
				e.pageBuilder.contextKnown = true
				if w.Name != "" {
					e.pageBuilder.paramEntityNames[w.Name] = entityName
				}
			}
		}

	case "Selection":
		val := w.GetSelection()
		if val == "" && mapping.Default != "" {
			val = mapping.Default
		}
		ctx.PrimitiveVal = val

	case "CaptionAttribute":
		if captionAttr := w.GetStringProp("CaptionAttribute"); captionAttr != "" {
			if !strings.Contains(captionAttr, ".") && e.pageBuilder.entityContext != "" {
				captionAttr = e.pageBuilder.entityContext + "." + captionAttr
			}
			ctx.AttributePath = captionAttr
		}

	case "Association":
		// Accept either the explicit `Association:` keyword or the generic
		// `attribute:` keyword for the reference the widget binds (e.g. a ComboBox
		// in association mode). Before this, only `attribute:` was read, so a
		// natural `combobox (Association: Mod.A_B, …)` silently dropped the binding
		// and failed the build with CE0642. (traceops #23)
		attr := w.GetStringProp("Association")
		if attr == "" {
			attr = w.GetAttribute()
		}
		if attr != "" {
			// The association belongs to the CONTAINING entity, not to this
			// widget's option list. A `DataSource:` mapping listed before this
			// one has already moved entityContext to the option entity, so
			// qualifying a bare name against it produced a reference into the
			// wrong module — `System.Issue_Assignee` for a ComboBox over
			// `System.User`, which fails CE1613 "The selected association … no
			// longer exists". (issuetracker #19)
			outer := e.outerEntityContext
			if outer == "" {
				outer = e.pageBuilder.entityContext
			}
			ctx.AssocPath = e.pageBuilder.resolveAssociationPathIn(attr, outer)
		}
		ctx.EntityName = e.pageBuilder.entityContext
		if ctx.AssocPath != "" && ctx.EntityName == "" {
			return nil, mdlerrors.NewValidationf("association %q requires an entity context (add a DataSource mapping before Association)", ctx.AssocPath)
		}

	case "OnClick":
		if action := w.GetAction(); action != nil {
			act, err := e.pageBuilder.buildClientActionV3(action)
			if err != nil {
				return nil, mdlerrors.NewBackend("build action", err)
			}
			ctx.Action = act
		}

	case "OnChange":
		if action := w.GetOnChange(); action != nil {
			act, err := e.pageBuilder.buildClientActionV3(action)
			if err != nil {
				return nil, mdlerrors.NewBackend("build action", err)
			}
			ctx.Action = act
		}

	default:
		val := w.GetStringProp(source)
		if val == "" {
			// Non-string AST values (e.g. `DesktopColumns: 3`, parsed as an int)
			// are invisible to GetStringProp; read them generically so numeric
			// properties aren't silently dropped to the schema default.
			if astVal, ok := lookupProperty(w.Properties, source); ok {
				val = stringifyAny(astVal)
			}
		}
		if val == "" && mapping.Default != "" {
			val = mapping.Default
		}
		ctx.PrimitiveVal = val
	}

	return ctx, nil
}

// applyObjectLists handles the def.json `objectLists` mappings. For each
// child of the AST widget whose Type matches an objectLists[].MDLContainer,
// it builds an ObjectListItemSpec by walking the child's properties and
// nested children, then hands the collected specs to the backend's
// SetObjectList for serialization.
func (e *PluggableWidgetEngine) applyObjectLists(builder backend.WidgetObjectBuilder, lists []ObjectListMapping, w *ast.WidgetV3) error {
	if len(lists) == 0 {
		return nil
	}
	// Index containers by uppercase keyword for matching against AST child Type.
	byContainer := make(map[string]*ObjectListMapping, len(lists))
	for i := range lists {
		byContainer[strings.ToUpper(lists[i].MDLContainer)] = &lists[i]
	}

	itemsByPropKey := make(map[string][]backend.ObjectListItemSpec)
	for _, child := range w.Children {
		mapping, ok := byContainer[strings.ToUpper(child.Type)]
		if !ok {
			continue
		}
		spec, err := e.buildObjectListItem(mapping, child)
		if err != nil {
			return err
		}
		itemsByPropKey[mapping.PropertyKey] = append(itemsByPropKey[mapping.PropertyKey], spec)
	}

	// Drive Set in def.json order so output is deterministic.
	for _, list := range lists {
		items := itemsByPropKey[list.PropertyKey]
		if len(items) == 0 {
			continue
		}
		builder.SetObjectList(list.PropertyKey, items)
	}
	return nil
}

// buildObjectListItem converts one AST child node (e.g. a `group panel1 (...)
// { ... }`) into an ObjectListItemSpec by:
//   - matching widget properties against ItemProperties (scalar dispatch)
//   - matching nested AST children against ItemSlots (widgets-typed slots)
//
// isChartSeriesContainer reports whether an object-list container keyword is a
// Mendix Charts series (SERIES for Bar/Column/Area/Pie; LINE for Line/Bubble/
// TimeSeries). Only these carry the static·/dynamic· dataSet-gated texttemplate
// sub-properties whose empty-ClientTemplate-when-visible rule differs from other
// object lists (Accordion groups, DataGrid columns). Chart series (9a).
func isChartSeriesContainer(container string) bool {
	switch strings.ToUpper(container) {
	case "SERIES", "LINE":
		return true
	}
	return false
}

// chartSeriesTextTemplateVisible reports whether a chart series' texttemplate
// sub-property is visible for the item's current dataSet mode + configured
// datasources, mirroring the widget's editorConfig `hideNestedPropertiesIn`
// gate. A visible-but-unset texttemplate must serialize an empty ClientTemplate
// (not null) or Studio Pro flags CE0463:
//   - the property's mode (static·/dynamic· name prefix) must match dataSet;
//   - a datasource-bound property (e.g. staticTooltipHoverText → staticDataSource)
//     is visible only when that datasource is configured on the item.
//
// An unbound property (e.g. staticName) is visible whenever its mode matches.
func chartSeriesTextTemplateVisible(ip ItemPropertyMapping, dataSetMode string, configuredDataSources map[string]pages.DataSource) bool {
	mode := "static"
	if strings.HasPrefix(strings.ToLower(ip.PropertyKey), "dynamic") {
		mode = "dynamic"
	}
	if dataSetMode == "" {
		dataSetMode = "static"
	}
	if !strings.EqualFold(dataSetMode, mode) {
		return false // hidden by the dataSet gate
	}
	if ip.DataSource != "" {
		_, configured := configuredDataSources[ip.DataSource]
		return configured
	}
	return true
}

// chartSeriesTextTemplateHiddenByItemConfig reports whether a chart-series
// textTemplate sub-property is hidden by the widget's editorConfig based on OTHER
// item-level property values (beyond the dataSet gate). These mirror the
// `hideNestedPropertiesIn` rules in the chart editorConfig.js:
//
//	markerColor  visible only when lineStyle == "lineWithMarkers"  (default "line")
//	fillColor    visible only when enableFillArea is truthy          (default true)
//
// Without this, a hidden sub-property's empty-ClientTemplate default (which
// chartSeriesTextTemplateVisible would otherwise emit) trips CE0463 — e.g.
// markerColor on a default "line" TimeSeries/LineChart series. Absent keys use the
// schema default.
func chartSeriesTextTemplateHiddenByItemConfig(propertyKey string, itemConfig map[string]string) bool {
	switch propertyKey {
	case "markerColor":
		lineStyle := itemConfig["lineStyle"]
		if lineStyle == "" {
			lineStyle = "line"
		}
		return lineStyle != "lineWithMarkers"
	case "fillColor":
		enableFillArea := itemConfig["enableFillArea"]
		if enableFillArea == "" {
			enableFillArea = "true" // schema default
		}
		return !isTruthyPrimitive(enableFillArea)
	}
	return false
}

// isTruthyPrimitive reports whether a primitive string value is truthy (non-empty,
// not "false"/"0"). Mirrors the editorConfig's boolean gate semantics.
func isTruthyPrimitive(v string) bool {
	return v != "" && v != "false" && v != "0"
}

// seriesDataSourceMatchesMode reports whether a chart-series datasource property
// key (staticDataSource / dynamicDataSource) is the one active for the given
// dataSet mode — used to route the friendly `DataSource:` alias. Chart series (9a).
func seriesDataSourceMatchesMode(propertyKey, dataSetMode string) bool {
	if dataSetMode == "" {
		dataSetMode = "static"
	}
	mode := "static"
	if strings.HasPrefix(strings.ToLower(propertyKey), "dynamic") {
		mode = "dynamic"
	}
	return strings.EqualFold(dataSetMode, mode)
}

func (e *PluggableWidgetEngine) buildObjectListItem(mapping *ObjectListMapping, child *ast.WidgetV3) (backend.ObjectListItemSpec, error) {
	spec := backend.ObjectListItemSpec{}
	// Track whether the user explicitly set Sortable / ShowContentAs in MDL —
	// drives the attribute-less and custom-content fallbacks below.
	_, sortableExplicit := lookupProperty(child.Properties, "Sortable")
	_, showContentAsExplicit := lookupProperty(child.Properties, "ShowContentAs")

	// Save/restore the page builder's entity context: an object-list item may
	// bring its OWN datasource (e.g. a chart `series`' staticDataSource), against
	// which the item's attribute sub-properties (staticXAttribute / staticY…)
	// must resolve — not the parent widget's context. Chart series (9a).
	savedEntityContext := e.pageBuilder.entityContext
	defer func() { e.pageBuilder.entityContext = savedEntityContext }()

	// A chart series' texttemplate visibility (and the DataSource: alias below)
	// depend on its dataSet mode (static/dynamic); default to static when unset,
	// matching the schema.
	itemDataSetMode := "static"
	if v, ok := lookupProperty(child.Properties, "dataSet"); ok {
		if s := stringifyAny(v); s != "" {
			itemDataSetMode = s
		}
	}

	// itemConfig holds the user-set item-level values that gate the visibility of
	// OTHER sub-properties in the widget's editorConfig (chart series: lineStyle
	// gates markerColor, enableFillArea gates fillColor). Absent keys fall back to
	// the schema default inside chartSeriesTextTemplateHiddenByItemConfig.
	itemConfig := map[string]string{}
	for _, key := range []string{"lineStyle", "enableFillArea"} {
		if v, ok := lookupProperty(child.Properties, key); ok {
			itemConfig[key] = stringifyAny(v)
		}
	}

	// Pre-resolve any datasource-typed sub-property the MDL set, so attribute
	// sub-properties later in the loop resolve against the item's own entity
	// regardless of schema property order. The built DataSource is emitted in
	// the main loop's "datasource" case.
	prebuiltDataSources := make(map[string]pages.DataSource)
	for _, ip := range mapping.ItemProperties {
		if ip.Operation != "datasource" {
			continue
		}
		raw, ok := lookupProperty(child.Properties, ip.PropertyKey)
		if !ok {
			for _, alias := range ip.MdlAliases {
				if raw, ok = lookupProperty(child.Properties, alias); ok {
					break
				}
			}
		}
		// Friendly `DataSource:` alias inside a chart series routes to the
		// mode-appropriate datasource property (staticDataSource when
		// dataSet=static, dynamicDataSource when dynamic) — matching how the
		// top-level widget datasource is written. Chart series (9a).
		if !ok && isChartSeriesContainer(mapping.MDLContainer) && seriesDataSourceMatchesMode(ip.PropertyKey, itemDataSetMode) {
			raw, ok = lookupProperty(child.Properties, "DataSource")
		}
		if !ok {
			continue
		}
		ds, ok := raw.(*ast.DataSourceV3)
		if !ok {
			continue
		}
		dataSource, entityName, err := e.pageBuilder.buildDataSourceV3(ds)
		if err != nil {
			return spec, mdlerrors.NewBackend("datasource for object-list item property "+ip.PropertyKey, err)
		}
		prebuiltDataSources[ip.PropertyKey] = dataSource
		if entityName != "" {
			e.pageBuilder.entityContext = entityName
		}
	}

	// Scalar item properties: ItemProperties carries the operation kind per
	// sub-property key. Look up the value in the AST child's properties bag.
	for _, ip := range mapping.ItemProperties {
		// Property names in MDL are case-insensitive — find a match by lower-cased key.
		// Try the schema name first, then fall back to MDL aliases (e.g. Caption → header).
		// matchedAlias tracks which name actually hit, so we can find the matching
		// `<name>Params` companion (e.g. Caption → CaptionParams).
		raw, ok := lookupProperty(child.Properties, ip.PropertyKey)
		matchedAlias := ip.PropertyKey
		if !ok {
			for _, alias := range ip.MdlAliases {
				if raw, ok = lookupProperty(child.Properties, alias); ok {
					matchedAlias = alias
					break
				}
			}
		}
		if !ok {
			// MDL didn't set the property; if the .def.json schema carries a
			// non-empty primitive default, apply it. Without this, the engine
			// falls back to the embedded template's WidgetObject value, which
			// is the Mendix 11.6 snapshot and may drift from the project's
			// installed .mpk (e.g. column minWidth: template says "linked",
			// current schema says "auto").
			if ip.Operation == "primitive" && ip.Value != "" {
				spec.Properties = append(spec.Properties, backend.ObjectListItemProperty{
					PropertyKey:  ip.PropertyKey,
					Operation:    "primitive",
					PrimitiveVal: ip.Value,
				})
			}
			// A datasource resolved in the pre-pass via the friendly `DataSource:`
			// alias has no direct child.Properties[<schemaKey>] entry, so emit it
			// here from the pre-built map. Chart series (9a).
			if ds, dsOK := prebuiltDataSources[ip.PropertyKey]; dsOK && ds != nil {
				spec.Properties = append(spec.Properties, backend.ObjectListItemProperty{
					PropertyKey: ip.PropertyKey,
					Operation:   "datasource",
					DataSource:  ds,
				})
			}
			// A VISIBLE-but-unset texttemplate sub-property of a chart series must
			// serialize as an empty Forms$ClientTemplate, not null, or Studio Pro
			// flags CE0463. Visibility follows the widget's editorConfig dataSet
			// gate + dataSource binding. Scoped to chart series so non-chart
			// object lists (Accordion groups, DataGrid columns) are untouched. (9a)
			if ip.Operation == "texttemplate" && isChartSeriesContainer(mapping.MDLContainer) &&
				chartSeriesTextTemplateVisible(ip, itemDataSetMode, prebuiltDataSources) &&
				!chartSeriesTextTemplateHiddenByItemConfig(ip.PropertyKey, itemConfig) {
				spec.Properties = append(spec.Properties, backend.ObjectListItemProperty{
					PropertyKey:   ip.PropertyKey,
					Operation:     "texttemplate",
					EmptyTemplate: true,
				})
			}
			continue
		}
		strVal := stringifyAny(raw)
		prop := backend.ObjectListItemProperty{
			PropertyKey: ip.PropertyKey,
			Operation:   ip.Operation,
		}
		switch ip.Operation {
		case "primitive":
			prop.PrimitiveVal = strVal
		case "expression":
			prop.Expression = strVal
		case "texttemplate":
			prop.TextTemplate = strVal
			prop.EntityContext = e.pageBuilder.entityContext
			// Look up the matching params companion in the AST. Convention:
			// when MDL writes `Caption: '{1}'` it pairs with `CaptionParams:
			// [{1} = attr]`. The companion key is the matched name (alias or
			// schema name) + "Params".
			// lookupProperty, not a direct index: MDL property names are
			// case-insensitive everywhere else, and matchedAlias is the SCHEMA
			// key (`buttonCaption`) while the script — and DESCRIBE — write the
			// widget's own casing (`ButtonCaptionParams`). A direct index found
			// the companion only when the two happened to agree, which is why
			// this worked for a DataGrid column's `CaptionParams` and silently
			// dropped a File Uploader custom button's, leaving a `{1}` with no
			// parameter and failing the build with CE0720 (#956).
			if paramsRaw, ok := lookupProperty(child.Properties, matchedAlias+"Params"); ok {
				if astParams, ok := paramsRaw.([]ast.ParamAssignmentV3); ok && len(astParams) > 0 {
					prop.Parameters = e.pageBuilder.buildClientTemplateParams(astParams)
				}
			}
		case "attribute":
			// An attribute navigated over associations (e.g. Order_Customer/Name)
			// resolves to a final attribute + association steps (AttributeRef.EntityRef);
			// a flat path is left as-is. Mirrors the DynamicText contentparam path.
			if finalQN, steps, ok := e.pageBuilder.resolveAssociationAttributePath(strVal); ok {
				prop.AttributePath = finalQN
				prop.AttributeRefSteps = steps
			} else if e.pageBuilder.entityContext != "" {
				// A bare ASSOCIATION name here is not representable — it would be
				// written as an AttributeRef and fail CE1613 (issue #830).
				if err := e.pageBuilder.rejectAssociationAsAttribute(
					strVal, e.pageBuilder.entityContext,
					fmt.Sprintf("%s `%s` property `%s`", mapping.MDLContainer, child.Name, ip.PropertyKey),
				); err != nil {
					return spec, err
				}
				prop.AttributePath = e.pageBuilder.resolveAttributePath(strVal)
			} else {
				prop.AttributePath = strVal
			}
		case "datasource":
			// Emit the datasource pre-resolved above (which also set the item's
			// entity context for the attribute sub-props). Chart series (9a).
			ds, ok := prebuiltDataSources[ip.PropertyKey]
			if !ok || ds == nil {
				continue
			}
			prop.DataSource = ds
		case "action":
			// An action on an object-list ITEM: a chart series'
			// staticOnClickAction, a popupmenu item's action, a maps marker's
			// onClick, an accordion group's onToggleCollapsed (#956).
			//
			// Read it through namedActionSlotValue — the same reader the
			// top-level named slots use — rather than off the AST's fixed Action
			// slot. `microflow M.X` in a property position parses as a
			// *DataSourceV3 (dataSourceExprV3 wins in widgetPropertyV3), so a
			// direct read would miss the form people actually write, and would
			// take the datasource branch of this very switch on the way past.
			//
			// matchedAlias, not ip.PropertyKey: the outer lookup already fell
			// back to an MDL alias, and re-reading under the schema key would
			// find nothing.
			act, err := namedActionSlotValue(child, matchedAlias)
			if err != nil {
				return spec, err
			}
			if act == nil {
				continue
			}
			built, err := e.pageBuilder.buildClientActionV3(act)
			if err != nil {
				return spec, mdlerrors.NewBackend(
					"build action for object-list item property "+ip.PropertyKey, err)
			}
			if built == nil {
				// An unset slot must stay unset: writing a NoAction over it
				// would clear whatever the widget had.
				continue
			}
			prop.Action = built
		default:
			// Remaining unsupported sub-property kinds still need richer AST
			// context than the child's property bag.
			continue
		}
		spec.Properties = append(spec.Properties, prop)
	}

	// DataGrid column header convention: when the user provides no Caption,
	// fall back to the bound attribute name — or, for a custom-content column
	// with no attribute, the column's own name. Mirrors buildDataGrid2ColumnObject
	// in datagrid_builder.go. Without this, an empty/absent column header trips
	// Studio Pro's CE0463 (ledger #54). Only applies to items whose template has
	// a `header` slot (datagrid columns), never to header-less object-list items
	// like chart series.
	hasHeaderSlot := false
	for _, ip := range mapping.ItemProperties {
		if strings.EqualFold(ip.PropertyKey, "header") {
			hasHeaderSlot = true
			break
		}
	}
	applyColumnHeaderFallback(&spec, child.Name, hasHeaderSlot)

	// DataGrid column sortable convention: attribute-less columns (typical
	// "Actions" custom-content columns) default to sortable=false, since
	// Studio Pro errors on sortable=true without an Attribute. The keyword
	// path applies the same fallback (see datagrid_builder.go line 545+).
	applyColumnSortableFallback(&spec, sortableExplicit)

	// Widgets-typed slots: ItemSlots gives us per-slot keyword conventions.
	// For object-list items the most common shape today is direct child
	// widgets (no inner container). Match nested AST children in three
	// passes:
	//   (a) MDLContainer name match (e.g. HEADERCONTENT block inside group)
	//   (b) AcceptedChildTypes match (e.g. textfilter inside a column body
	//       routes to the column's filter slot)
	//   (c) Anything else → default Widgets-typed slot (usually content)
	if len(child.Children) > 0 {
		spec.ChildWidgets = make(map[string][]pages.Widget)
		// Index slot containers + accepted child types by uppercase keyword.
		slotByContainer := make(map[string]string)
		acceptedTypeToSlot := make(map[string]string)
		for _, slot := range mapping.ItemSlots {
			slotByContainer[strings.ToUpper(slot.MDLContainer)] = slot.PropertyKey
			for _, t := range slot.AcceptedChildTypes {
				acceptedTypeToSlot[strings.ToUpper(t)] = slot.PropertyKey
			}
		}

		// Pass (a): explicit container blocks → matched slot.
		// Pass (b): widget Type matches an AcceptedChildTypes entry → that slot.
		// Pass (c): everything else routes via the default slot.
		var unmatched []*ast.WidgetV3
		for _, gc := range child.Children {
			gcTypeUpper := strings.ToUpper(gc.Type)
			if propKey, ok := slotByContainer[gcTypeUpper]; ok {
				for _, slotChild := range gc.Children {
					widget, err := e.pageBuilder.buildWidgetV3(slotChild)
					if err != nil {
						return spec, err
					}
					if widget != nil {
						spec.ChildWidgets[propKey] = append(spec.ChildWidgets[propKey], widget)
					}
				}
				continue
			}
			if propKey, ok := acceptedTypeToSlot[gcTypeUpper]; ok {
				widget, err := e.pageBuilder.buildWidgetV3(gc)
				if err != nil {
					return spec, err
				}
				if widget != nil {
					spec.ChildWidgets[propKey] = append(spec.ChildWidgets[propKey], widget)
				}
				continue
			}
			unmatched = append(unmatched, gc)
		}

		// Pass (c): unmatched widgets → default Widgets-typed slot.
		if len(unmatched) > 0 {
			defaultKey := defaultItemSlotKey(mapping)
			if defaultKey != "" {
				for _, gc := range unmatched {
					widget, err := e.pageBuilder.buildWidgetV3(gc)
					if err != nil {
						return spec, err
					}
					if widget != nil {
						spec.ChildWidgets[defaultKey] = append(spec.ChildWidgets[defaultKey], widget)
					}
				}
			}
		}
	}

	// DataGrid column showContentAs convention: when child widgets landed in
	// the `content` slot without an explicit ShowContentAs in MDL, auto-infer
	// customContent. Mirrors hasCustomContent in datagrid_builder.go. Must
	// run after the child-routing pass so spec.ChildWidgets is populated.
	applyColumnShowContentAsFallback(&spec, showContentAsExplicit, len(spec.ChildWidgets["content"]) > 0)

	return spec, nil
}

// defaultItemSlotKey picks a "default" widgets-typed slot for an object-list
// item: the slot keyed "content" if present, otherwise the first slot.
// Returns "" if there are no widgets-typed slots.
// applyColumnHeaderFallback synthesizes a texttemplate spec for the `header`
// property when the spec has an attribute binding but no header text. Mirrors
// the keyword path's `if caption == "" { caption = col.Attribute }` fallback
// in datagrid_builder.go. The check is conservative: only fires when the
// header slot is genuinely empty, so it's safe to call for any object-list
// item kind.
func applyColumnHeaderFallback(spec *backend.ObjectListItemSpec, columnName string, hasHeaderSlot bool) {
	// Only items whose template has a `header` slot (datagrid columns) get a
	// header fallback; header-less object-list items (chart series, accordion
	// groups) are left untouched.
	if !hasHeaderSlot {
		return
	}
	headerIdx := -1
	headerEmpty := false
	var attrPath string
	for i, p := range spec.Properties {
		switch p.PropertyKey {
		case "header":
			headerIdx = i
			// An explicit `Caption: ''` reaches here as a texttemplate with no
			// text and no params. Studio Pro rejects an empty column header with
			// CE0463 "widget definition changed" (ledger #54) — the same failure
			// an absent header would cause without this fallback. Treat empty as
			// absent so the fallback applies either way.
			headerEmpty = p.Operation == "texttemplate" && p.TextTemplate == "" && len(p.Parameters) == 0
		case "attribute":
			attrPath = p.AttributePath
		}
	}
	// A present, non-empty header needs nothing.
	if headerIdx >= 0 && !headerEmpty {
		return
	}
	// Fallback header text: the bound attribute's leaf name (Module.Entity.Attr →
	// Attr), or — for a custom-content / action column with no attribute — the
	// column's own name. Every datagrid column needs a NON-empty header; an empty
	// or absent one is CE0463 (ledger #54), and a custom-content column has no
	// attribute to derive one from, so the column name is the sensible default.
	fallback := attrPath
	if idx := strings.LastIndex(fallback, "."); idx >= 0 {
		fallback = fallback[idx+1:]
	}
	if fallback == "" {
		fallback = columnName
	}
	if fallback == "" {
		return
	}
	if headerIdx >= 0 {
		// Fill the empty header in place rather than appending a duplicate.
		spec.Properties[headerIdx].Operation = "texttemplate"
		spec.Properties[headerIdx].TextTemplate = fallback
		spec.Properties[headerIdx].EntityContext = ""
		return
	}
	spec.Properties = append(spec.Properties, backend.ObjectListItemProperty{
		PropertyKey:   "header",
		Operation:     "texttemplate",
		TextTemplate:  fallback,
		EntityContext: "", // literal text — no template params to resolve
	})
}

// applyColumnShowContentAsFallback forces showContentAs to "customContent"
// when the column has child widgets in its `content` slot but no explicit
// ShowContentAs in MDL. Mirrors the keyword path's `hasCustomContent :=
// len(contentWidgets) > 0` heuristic (datagrid_builder.go line 257). Studio
// Pro errors on `Show: Attribute` when no Attribute is set; auto-inferring
// customContent from the presence of cell-content widgets matches what
// users expect: `column foo { actionbutton x }` means "the cell renders
// the button".
func applyColumnShowContentAsFallback(spec *backend.ObjectListItemSpec, showContentAsExplicit bool, hasContentWidgets bool) {
	if showContentAsExplicit || !hasContentWidgets {
		return
	}
	for i, p := range spec.Properties {
		if p.PropertyKey == "showContentAs" {
			spec.Properties[i].PrimitiveVal = "customContent"
			return
		}
	}
	spec.Properties = append(spec.Properties, backend.ObjectListItemProperty{
		PropertyKey:  "showContentAs",
		Operation:    "primitive",
		PrimitiveVal: "customContent",
	})
}

// applyColumnSortableFallback forces `sortable` to "false" on attribute-less
// DataGrid columns (the typical "Actions" custom-content column). Studio Pro
// flags `sortable=true` + no Attribute as an authoring error (`An attribute
// is required when column sorting is enabled`); the keyword path defaults
// sortable to false when col.Attribute is empty
// (see datagrid_builder.go line 545+).
//
// Conservative: only fires when the user didn't explicitly set Sortable in
// MDL — an explicit `Sortable: true` on an attribute-less column is left
// alone (the user's mistake, surfaced by mx check).
func applyColumnSortableFallback(spec *backend.ObjectListItemSpec, sortableExplicit bool) {
	if sortableExplicit {
		return
	}
	var hasAttribute bool
	var sortableIdx = -1
	for i, p := range spec.Properties {
		switch p.PropertyKey {
		case "attribute":
			if p.AttributePath != "" {
				hasAttribute = true
			}
		case "sortable":
			sortableIdx = i
		}
	}
	if hasAttribute {
		return
	}
	if sortableIdx >= 0 {
		spec.Properties[sortableIdx].PrimitiveVal = "false"
		return
	}
	spec.Properties = append(spec.Properties, backend.ObjectListItemProperty{
		PropertyKey:  "sortable",
		Operation:    "primitive",
		PrimitiveVal: "false",
	})
}

func defaultItemSlotKey(mapping *ObjectListMapping) string {
	if len(mapping.ItemSlots) == 0 {
		return ""
	}
	for _, s := range mapping.ItemSlots {
		if s.PropertyKey == "content" {
			return s.PropertyKey
		}
	}
	return mapping.ItemSlots[0].PropertyKey
}

// lookupProperty does a case-insensitive lookup against an AST property map.
// MDL property names ignore case (e.g. `HeaderText` and `headerText` both match).
func lookupProperty(props map[string]any, key string) (any, bool) {
	if v, ok := props[key]; ok {
		return v, true
	}
	lower := strings.ToLower(key)
	for k, v := range props {
		if strings.ToLower(k) == lower {
			return v, true
		}
	}
	return nil, false
}

// stringifyAny converts a property value of arbitrary type to its string form
// for use in Set* methods. Returns "" for unknown types.
func stringifyAny(v any) string {
	switch x := v.(type) {
	case string:
		return x
	case bool:
		return fmt.Sprintf("%t", x)
	case int:
		return fmt.Sprintf("%d", x)
	case float64:
		return fmt.Sprintf("%g", x)
	}
	return ""
}

// applyChildSlots processes child slot mappings, building child widgets and embedding them.
// objectListContainers is the set of MDLContainer keywords (uppercase) that
// belong to objectLists mappings — those children are skipped here because
// applyObjectLists handles them.
func (e *PluggableWidgetEngine) applyChildSlots(builder backend.WidgetObjectBuilder, slots []ChildSlotMapping, w *ast.WidgetV3, propertyTypeIDs map[string]pages.PropertyTypeIDEntry, objectListContainers map[string]bool) error {
	if len(slots) == 0 {
		return nil
	}

	slotContainers := make(map[string]*ChildSlotMapping, len(slots))
	for i := range slots {
		slotContainers[slots[i].MDLContainer] = &slots[i]
	}

	slotWidgets := make(map[string][]pages.Widget)
	var defaultWidgets []pages.Widget

	for _, child := range w.Children {
		// Skip children whose keyword belongs to an object-list mapping.
		if objectListContainers[strings.ToUpper(child.Type)] {
			continue
		}
		lowerType := strings.ToLower(child.Type)
		slot, ok := slotContainers[lowerType]
		if !ok && lowerType == "container" {
			// Support the natural `container <slotName> { ... }` authoring form
			// (e.g. TreeNode `container children`, Timeline `container customTitle`)
			// by routing the container to the slot whose keyword matches its NAME.
			// The bare-keyword form (`children { ... }`, gallery `template tpl1 { ... }`)
			// still matches by Type above. This mirrors the object-list item-slot
			// matcher, which already routes by the container's name.
			slot, ok = slotContainers[strings.ToLower(child.Name)]
		}
		if ok {
			for _, slotChild := range child.Children {
				widget, err := e.pageBuilder.buildWidgetV3(slotChild)
				if err != nil {
					return err
				}
				if widget != nil {
					slotWidgets[slot.PropertyKey] = append(slotWidgets[slot.PropertyKey], widget)
				}
			}
		} else {
			widget, err := e.pageBuilder.buildWidgetV3(child)
			if err != nil {
				return err
			}
			if widget != nil {
				defaultWidgets = append(defaultWidgets, widget)
			}
		}
	}

	for _, slot := range slots {
		children := slotWidgets[slot.PropertyKey]
		if len(children) == 0 && len(defaultWidgets) > 0 && slot.MDLContainer == defaultSlotContainer {
			children = defaultWidgets
			defaultWidgets = nil
		}
		if len(children) == 0 {
			continue
		}

		ctx := &BuildContext{}
		if slot.Operation != "widgets" {
			return mdlerrors.NewValidationf("childSlots operation must be %q, got %q for property %s", "widgets", slot.Operation, slot.PropertyKey)
		}
		if err := e.applyOperation(builder, slot.Operation, slot.PropertyKey, ctx); err != nil {
			return err
		}
		// SetChildWidgets directly — applyOperation skips "widgets" since ctx doesn't carry children
		builder.SetChildWidgets(slot.PropertyKey, children)
	}

	return nil
}

// isBuiltinPropName returns true for property names that are handled by
// dedicated MDL keywords (DataSource, Attribute, etc.) rather than by
// the explicit property pass.
// numericTemplatePlaceholderRe matches Mendix's own `{1}` placeholder form, the
// one that needs explicit ClientTemplate parameters. `{AttrName}` is mxcli's
// convenience spelling and is resolved separately against the entity context.
var numericTemplatePlaceholderRe = regexp.MustCompile(`\{[0-9]+\}`)

func isBuiltinPropName(name string) bool {
	switch name {
	// OnChange belongs beside Action: both are dedicated MDL keywords resolved
	// by resolveMapping, neither is a widget storage key. Its absence meant
	// `OnChange:` fell through to the storage-name check and collided with the
	// widgets whose slot is spelled exactly `onChange` — Slider, RangeSlider and
	// StarRating — which were told to "use `OnChange:` instead" of `OnChange:`,
	// and could not have their only action slot authored at all (#956).
	case "DataSource", "Attribute", "Label", "Caption", "Action", "OnChange",
		"Selection", "Class", "Style", "DynamicClasses", "Editable", "Visible",
		"WidgetType", "DesignProperties", "Association", "CaptionAttribute",
		"Content", "RenderMode", "ContentParams", "CaptionParams",
		"ButtonStyle", "DesktopWidth", "DesktopColumns", "TabletColumns",
		"PhoneColumns", "PageSize", "Pagination", "PagingPosition",
		"ShowPagingButtons", "Attributes", "FilterType", "Width", "Height",
		"Tooltip", "Name":
		return true
	}
	return false
}
