// SPDX-License-Identifier: Apache-2.0

package executor

import (
	"fmt"
	"regexp"
	"sort"
	"strings"

	"github.com/mendixlabs/mxcli/mdl/ast"
	"github.com/mendixlabs/mxcli/mdl/backend"
	mdlerrors "github.com/mendixlabs/mxcli/mdl/errors"
	"github.com/mendixlabs/mxcli/mdl/types"
	"github.com/mendixlabs/mxcli/model"
	"github.com/mendixlabs/mxcli/sdk/pages"
)

// defaultSlotContainer is the MDLContainer name that receives default (non-containerized) child widgets.
const defaultSlotContainer = "template"

// =============================================================================
// Pluggable Widget Engine — Core Types
// =============================================================================

// WidgetDefGeneratorVersion is the schema/logic version of GenerateDefJSON's
// output. Bump it whenever the def.json generation changes in a way that
// affects emitted BSON (new fields like mdlAliases / acceptedChildTypes,
// changed defaults, new routing). Project-local `.mxcli/widgets/*.def.json`
// files stamp this value; `exec` auto-refreshes any whose stamp is behind,
// so an mxcli upgrade doesn't silently emit stale BSON from defs that were
// generated by an older build (the .mpk hasn't changed, only our logic has).
//
// Version history:
//
//	1 — pre-v0.12.0 (unstamped; treated as 0)
//	2 — v0.12.0: mdlAliases, acceptedChildTypes, attrChoice=auto, column
//	    convention fallbacks
//	3 — v0.12.0: propertyVisibility (VideoPlayer/Timeline hidden-property
//	    TextTemplate nulling, #574)
//	4 — v0.12.0: DataGrid column `width` ← `ColumnWidth` alias (dgDyn CE0463
//	    regression from the keyword-path consolidation)
//	5 — bundled multi-widget .mpk support: a def is now emitted for every
//	    widget in a package (e.g. Charts.mpk → BarChart/PieChart/…), not just
//	    the first. Bump forces existing projects to regenerate and pick up the
//	    previously-missing widgets (#679).
//	6 — DataGrid column `columnClass` ← `DynamicCellClass` alias. Bump forces
//	    existing projects to regenerate so the per-cell dynamic class is no
//	    longer silently dropped on write (Bug 10a).
//	7 — object-list ItemProperties now record their widget.xml `dataSource`
//	    binding, so the engine can emit an empty Forms$ClientTemplate for a
//	    VISIBLE texttemplate sub-property (chart series staticName / active
//	    static·/dynamic· names) instead of a null that trips CE0463 (Bug 9a).
//	8 — object-list ItemProperties record their enumeration member keys
//	    (enumValues), so `check` can flag an invalid enum value (MDL-WIDGET08)
//	    instead of Studio Pro silently defaulting it (e.g. a Maps marker
//	    locationType outside {address, latlng}).
const WidgetDefGeneratorVersion = 8

// WidgetDefinition describes how to construct a pluggable widget from MDL syntax.
// Loaded from embedded JSON definition files (*.def.json).
type WidgetDefinition struct {
	WidgetID           string                       `json:"widgetId"`
	MDLName            string                       `json:"mdlName"`
	WidgetKind         string                       `json:"widgetKind,omitempty"` // "pluggable" (React) or "custom" (legacy Dojo)
	TemplateFile       string                       `json:"templateFile"`
	DefaultEditable    string                       `json:"defaultEditable"`
	GeneratorVersion   int                          `json:"generatorVersion,omitempty"` // WidgetDefGeneratorVersion at generation time; 0/absent = pre-stamp
	PropertyMappings   []PropertyMapping            `json:"propertyMappings,omitempty"`
	ChildSlots         []ChildSlotMapping           `json:"childSlots,omitempty"`
	ObjectLists        []ObjectListMapping          `json:"objectLists,omitempty"`
	PropertyVisibility []types.WidgetVisibilityRule `json:"propertyVisibility,omitempty"`
	Modes              []WidgetMode                 `json:"modes,omitempty"`
	// KnownProperties lists real widget properties that the .def.json does not
	// (yet) map to a write path. `check` recognizes them so they aren't flagged
	// as unknown, but the engine does not persist them — setting a non-default
	// value yields an MDL-WIDGET04 warning rather than a false MDL-WIDGET01
	// error. Validation-only; never written to BSON. See issue #643.
	KnownProperties []string `json:"knownProperties,omitempty"`
}

// PropertyMapping maps an MDL source (attribute, association, literal, etc.)
// to a pluggable widget property key via a named operation.
type PropertyMapping struct {
	PropertyKey string `json:"propertyKey"`
	Source      string `json:"source,omitempty"`
	Value       string `json:"value,omitempty"`
	Operation   string `json:"operation"`
	Default     string `json:"default,omitempty"`
	// Description is the human-readable text from the .mpk's widget XML
	// (PropertyDef.Description). Populated by GenerateDefJSON; surfaced by
	// the LSP on property hover. Optional — older .def.json files without
	// this field still load fine.
	Description string `json:"description,omitempty"`
}

// WidgetMode defines a conditional configuration variant for a widget.
// For example, ComboBox has "enumeration" and "association" modes.
// Modes are evaluated in order; the first matching condition wins.
// A mode with no condition acts as the default fallback.
type WidgetMode struct {
	Name             string             `json:"name,omitempty"`
	Condition        string             `json:"condition,omitempty"`
	Description      string             `json:"description,omitempty"`
	PropertyMappings []PropertyMapping  `json:"propertyMappings"`
	ChildSlots       []ChildSlotMapping `json:"childSlots,omitempty"`
}

// ChildSlotMapping maps an MDL child container (e.g., TEMPLATE, FILTER) to a
// widget property that holds child widgets.
type ChildSlotMapping struct {
	PropertyKey  string `json:"propertyKey"`
	MDLContainer string `json:"mdlContainer"`
	Operation    string `json:"operation"`
}

// ObjectListMapping maps an MDL child block keyword (e.g., GROUP, ITEM, SERIES)
// to a pluggable widget property whose value is a list of structured objects
// (Type: "Object" + IsList: true in the widget XML).
//
// Each list item has its own sub-property tree, expressed via ItemProperties.
// ItemProperties supports the same operation kinds as top-level PropertyMapping
// and ChildSlotMapping (primitive, attribute, datasource, widgets, texttemplate,
// expression, action), as well as nested object lists.
type ObjectListMapping struct {
	PropertyKey    string                `json:"propertyKey"`
	MDLContainer   string                `json:"mdlContainer"`
	ItemProperties []ItemPropertyMapping `json:"itemProperties,omitempty"`
	ItemSlots      []ItemSlotMapping     `json:"itemSlots,omitempty"`
}

// ItemPropertyMapping maps a property of one object-list item (e.g. headerText
// of an Accordion group) to its operation kind. Mirrors PropertyMapping but
// scoped to the list item rather than the top-level widget.
//
// MdlAliases lists alternative MDL property names that resolve to this same
// schema property. Used for editorial conventions where the MDL keyword
// differs from the .mpk schema name (e.g. DataGrid column `Caption:` maps
// to schema property `header`).
type ItemPropertyMapping struct {
	PropertyKey string   `json:"propertyKey"`
	Source      string   `json:"source,omitempty"`
	Value       string   `json:"value,omitempty"`
	Operation   string   `json:"operation"`
	Default     string   `json:"default,omitempty"`
	Description string   `json:"description,omitempty"`
	MdlAliases  []string `json:"mdlAliases,omitempty"`
	// EnumValues lists the valid member keys for an enumeration sub-property
	// (e.g. a Maps marker `locationType` accepts address/latlng). `check` flags
	// a value outside this set (MDL-WIDGET08) — Studio Pro silently defaults an
	// invalid enum value, which is why chart/Maps sub-properties fail quietly.
	EnumValues []string `json:"enumValues,omitempty"`
	// DataSource is the widget.xml `dataSource="..."` binding, if any (e.g. a
	// chart series `staticTooltipHoverText` is bound to `staticDataSource`). It
	// drives object-list-item visibility: a texttemplate sub-property is
	// "visible" — and must serialize an empty Forms$ClientTemplate rather than a
	// null (else CE0463) — when it has no dataSource binding OR its bound
	// datasource is configured on the item. Chart series (9a).
	DataSource string `json:"dataSource,omitempty"`
}

// ItemSlotMapping maps a widget child slot inside one object-list item
// (e.g. headerContent of an Accordion group, content of a DataGrid column).
// Mirrors ChildSlotMapping but scoped to the list item.
//
// AcceptedChildTypes lists MDL widget Type keywords (lowercase) that route
// to this slot when they appear directly inside the item body without an
// explicit MDLContainer wrapper. Used for editorial conventions where the
// user types `column foo { textfilter ... }` and expects the textfilter
// in the column's `filter` slot — not the default `content` slot.
type ItemSlotMapping struct {
	PropertyKey        string   `json:"propertyKey"`
	MDLContainer       string   `json:"mdlContainer"`
	Operation          string   `json:"operation"`
	AcceptedChildTypes []string `json:"acceptedChildTypes,omitempty"`
}

// BuildContext carries resolved values from MDL parsing for use by operations.
type BuildContext struct {
	AttributePath  string
	AttributePaths []string // For operations that process multiple attributes
	AssocPath      string
	EntityName     string
	PrimitiveVal   string
	DataSource     pages.DataSource
	Action         pages.ClientAction // Domain-typed client action
	pageBuilder    *pageBuilder
}

// =============================================================================
// Pluggable Widget Engine
// =============================================================================

// PluggableWidgetEngine builds CustomWidget instances from WidgetDefinition + AST.
type PluggableWidgetEngine struct {
	backend     backend.WidgetBuilderBackend
	pageBuilder *pageBuilder
}

// NewPluggableWidgetEngine creates a new engine with the given backend and page builder.
func NewPluggableWidgetEngine(b backend.WidgetBuilderBackend, pb *pageBuilder) *PluggableWidgetEngine {
	return &PluggableWidgetEngine{
		backend:     b,
		pageBuilder: pb,
	}
}

// Build constructs a CustomWidget from a definition and AST widget node.
func (e *PluggableWidgetEngine) Build(def *WidgetDefinition, w *ast.WidgetV3) (*pages.CustomWidget, error) {
	// Save and restore entity context (DataSource mappings may change it)
	oldEntityContext := e.pageBuilder.entityContext
	defer func() { e.pageBuilder.entityContext = oldEntityContext }()

	// 1. Load template via backend
	builder, err := e.backend.LoadWidgetTemplate(def.WidgetID, e.pageBuilder.getProjectPath())
	if err != nil {
		return nil, mdlerrors.NewBackend("load "+def.MDLName+" template", err)
	}
	if builder == nil {
		return nil, mdlerrors.NewNotFound("template", def.MDLName)
	}

	propertyTypeIDs := builder.PropertyTypeIDs()

	// 2. Select mode and get mappings/slots
	mappings, slots, err := e.selectMappings(def, w)
	if err != nil {
		return nil, err
	}

	// 3. Apply property mappings
	for _, mapping := range mappings {
		ctx, err := e.resolveMapping(mapping, w)
		if err != nil {
			return nil, mdlerrors.NewBackend("resolve mapping for "+mapping.PropertyKey, err)
		}

		if err := e.applyOperation(builder, mapping.Operation, mapping.PropertyKey, ctx); err != nil {
			return nil, err
		}
	}

	// 4. Auto datasource: map AST DataSource to first DataSource-type property.
	// This must run before child slots so that entityContext is available
	// for child widgets that depend on the parent's data source.
	dsHandledByMapping := false
	for _, m := range mappings {
		if m.Source == "DataSource" {
			dsHandledByMapping = true
			break
		}
	}
	if !dsHandledByMapping {
		if ds := w.GetDataSource(); ds != nil {
			for propKey, entry := range propertyTypeIDs {
				if entry.ValueType == "DataSource" {
					dataSource, entityName, err := e.pageBuilder.buildDataSourceV3(ds)
					if err != nil {
						return nil, mdlerrors.NewBackend("auto datasource for "+propKey, err)
					}
					builder.SetDataSource(propKey, dataSource)
					if entityName != "" {
						e.pageBuilder.entityContext = entityName
					}
					break
				}
			}
		}
	}

	// 4.1 Apply child slots (.def.json) — skip children whose keyword belongs
	// to an objectLists mapping (handled by applyObjectLists below).
	objectListContainers := make(map[string]bool, len(def.ObjectLists))
	for _, ol := range def.ObjectLists {
		objectListContainers[strings.ToUpper(ol.MDLContainer)] = true
	}
	if err := e.applyChildSlots(builder, slots, w, propertyTypeIDs, objectListContainers); err != nil {
		return nil, err
	}

	// 4.1b Apply object-list child blocks (.def.json `objectLists`).
	// Children whose Type matches an objectLists[].MDLContainer are routed
	// through the object-list builder rather than treated as nested widgets.
	if err := e.applyObjectLists(builder, def.ObjectLists, w); err != nil {
		return nil, err
	}

	// 4.3 Auto child slots: match AST children to Widgets-type template properties.
	handledSlotKeys := make(map[string]bool)
	for _, s := range slots {
		handledSlotKeys[s.PropertyKey] = true
	}
	// objectListContainers (computed above before applyChildSlots) is reused
	// here so the auto-widgets-discovery passes below skip object-list children.
	var widgetsPropKeys []string
	for propKey, entry := range propertyTypeIDs {
		if entry.ValueType == "Widgets" && !handledSlotKeys[propKey] {
			widgetsPropKeys = append(widgetsPropKeys, propKey)
		}
	}
	sort.Strings(widgetsPropKeys)
	// Phase 1: Named matching — match children by name against property keys
	matchedChildren := make(map[int]bool)
	// Mark object-list children as already handled — applyObjectLists owns them.
	for i, child := range w.Children {
		if objectListContainers[strings.ToUpper(child.Type)] {
			matchedChildren[i] = true
		}
	}
	for _, propKey := range widgetsPropKeys {
		upperKey := strings.ToUpper(propKey)
		for i, child := range w.Children {
			if matchedChildren[i] {
				continue
			}
			if strings.ToUpper(child.Name) == upperKey {
				var childWidgets []pages.Widget
				for _, slotChild := range child.Children {
					widget, err := e.pageBuilder.buildWidgetV3(slotChild)
					if err != nil {
						return nil, err
					}
					if widget != nil {
						childWidgets = append(childWidgets, widget)
					}
				}
				if len(childWidgets) > 0 {
					builder.SetChildWidgets(propKey, childWidgets)
					handledSlotKeys[propKey] = true
				}
				matchedChildren[i] = true
				break
			}
		}
	}
	// Phase 2: Default slot — unmatched direct children go to first unmatched Widgets property.
	defSlotContainers := make(map[string]bool)
	for _, s := range slots {
		defSlotContainers[strings.ToUpper(s.MDLContainer)] = true
	}
	var defaultWidgets []pages.Widget
	for i, child := range w.Children {
		if matchedChildren[i] {
			continue
		}
		if len(slots) > 0 {
			continue // applyChildSlots handles both container and direct children
		}
		if defSlotContainers[strings.ToUpper(child.Type)] {
			continue
		}
		widget, err := e.pageBuilder.buildWidgetV3(child)
		if err != nil {
			return nil, err
		}
		if widget != nil {
			defaultWidgets = append(defaultWidgets, widget)
		}
	}
	if len(defaultWidgets) > 0 {
		for _, propKey := range widgetsPropKeys {
			if !handledSlotKeys[propKey] {
				builder.SetChildWidgets(propKey, defaultWidgets)
				break
			}
		}
	}

	// 4.6 Apply explicit properties (not covered by .def.json mappings)
	mappedKeys := make(map[string]bool)
	for _, m := range mappings {
		if m.Source != "" {
			mappedKeys[m.Source] = true
		}
	}
	for _, s := range slots {
		mappedKeys[s.MDLContainer] = true
	}
	for propName, propVal := range w.Properties {
		if mappedKeys[propName] || isBuiltinPropName(propName) {
			continue
		}
		entry, ok := propertyTypeIDs[propName]
		if !ok {
			continue // not a known widget property key
		}
		// Convert non-string values (bool, int, float) to string for property setting
		var strVal string
		switch v := propVal.(type) {
		case string:
			strVal = v
		case bool:
			strVal = fmt.Sprintf("%t", v)
		case int:
			strVal = fmt.Sprintf("%d", v)
		case float64:
			strVal = fmt.Sprintf("%g", v)
		default:
			continue
		}

		// Route by ValueType when available
		switch entry.ValueType {
		case "Expression":
			builder.SetExpression(propName, strVal)
		case "TextTemplate":
			entityCtx := e.pageBuilder.entityContext
			builder.SetTextTemplateWithParams(propName, strVal, entityCtx)
		case "Attribute":
			attrPath := ""
			if strings.Count(strVal, ".") >= 2 {
				attrPath = strVal
			} else if e.pageBuilder.entityContext != "" {
				attrPath = e.pageBuilder.resolveAttributePath(strVal)
			}
			if attrPath != "" {
				builder.SetAttribute(propName, attrPath)
			}
		default:
			// Known non-attribute types: always use primitive
			if entry.ValueType != "" && entry.ValueType != "Attribute" {
				builder.SetPrimitive(propName, strVal)
				continue
			}
			// Legacy routing for properties without ValueType info
			if strings.Count(strVal, ".") >= 2 {
				builder.SetAttribute(propName, strVal)
			} else if e.pageBuilder.entityContext != "" && !strings.ContainsAny(strVal, " '\"") {
				builder.SetAttribute(propName, e.pageBuilder.resolveAttributePath(strVal))
			} else {
				builder.SetPrimitive(propName, strVal)
			}
		}
	}

	// 4.9 Auto-populate required empty object lists
	builder.EnsureRequiredObjectLists()

	// 4.10 Apply property-visibility rules: a TextTemplate property that the
	// widget's editorConfig.js hides under the current configuration must emit
	// TextTemplate: null, not the template's populated default (CE0463, #574).
	if len(def.PropertyVisibility) > 0 {
		builder.ApplyPropertyVisibility(def.PropertyVisibility)
	}

	// 5. Build CustomWidget
	widgetID := model.ID(types.GenerateID())
	cw := builder.Finalize(widgetID, w.Name, w.GetLabel(), def.DefaultEditable)

	if err := e.pageBuilder.registerWidgetName(w.Name, cw.ID); err != nil {
		return nil, err
	}

	return cw, nil
}

// templateAttrPlaceholderRe matches `{AttrName}` placeholders in a text
// template. Numeric parameter references (`{1}`) don't match and pass through
// verbatim.
var templateAttrPlaceholderRe = regexp.MustCompile(`\{[A-Za-z][A-Za-z0-9_]*\}`)

// applyOperation dispatches a named operation to the corresponding builder method.
func (e *PluggableWidgetEngine) applyOperation(builder backend.WidgetObjectBuilder, opName string, propKey string, ctx *BuildContext) error {
	switch opName {
	case "attribute":
		builder.SetAttribute(propKey, ctx.AttributePath)
	case "association":
		builder.SetAssociation(propKey, ctx.AssocPath, ctx.EntityName)
	case "primitive":
		builder.SetPrimitive(propKey, ctx.PrimitiveVal)
	case "selection":
		builder.SetSelection(propKey, ctx.PrimitiveVal)
	case "expression":
		builder.SetExpression(propKey, ctx.PrimitiveVal)
	case "datasource":
		builder.SetDataSource(propKey, ctx.DataSource)
	case "widgets":
		// ctx doesn't carry child widgets for this path — handled by applyChildSlots
	case "texttemplate":
		// A `{AttrName}` placeholder needs ClientTemplate parameters resolved
		// against the entity context — plain SetTextTemplate would emit the
		// braces literally, which Studio Pro's translatable-text parser rejects
		// ("Brace should be followed by a number of digits"). Placeholder-less
		// text keeps the SetTextTemplate path so backend output is unchanged.
		if templateAttrPlaceholderRe.MatchString(ctx.PrimitiveVal) {
			builder.SetTextTemplateWithParams(propKey, ctx.PrimitiveVal, e.pageBuilder.entityContext)
		} else {
			builder.SetTextTemplate(propKey, ctx.PrimitiveVal)
		}
	case "action":
		builder.SetAction(propKey, ctx.Action)
	case "attributeObjects":
		builder.SetAttributeObjects(propKey, ctx.AttributePaths)
	default:
		return mdlerrors.NewValidationf("unknown operation %q for property %s", opName, propKey)
	}
	return nil
}

// selectMappings selects the active PropertyMappings and ChildSlotMappings based on mode.
func (e *PluggableWidgetEngine) selectMappings(def *WidgetDefinition, w *ast.WidgetV3) ([]PropertyMapping, []ChildSlotMapping, error) {
	if len(def.Modes) == 0 {
		return def.PropertyMappings, def.ChildSlots, nil
	}

	var fallback *WidgetMode
	var fallbackCount int
	for i := range def.Modes {
		mode := &def.Modes[i]
		if mode.Condition == "" {
			fallbackCount++
			if fallback == nil {
				fallback = mode
			}
			continue
		}
		if e.evaluateCondition(mode.Condition, w) {
			return mode.PropertyMappings, mode.ChildSlots, nil
		}
	}

	if fallback != nil {
		if fallbackCount > 1 {
			return nil, nil, mdlerrors.NewValidationf("widget %s has %d modes without conditions; only one default mode is allowed", def.MDLName, fallbackCount)
		}
		return fallback.PropertyMappings, fallback.ChildSlots, nil
	}

	return nil, nil, mdlerrors.NewValidationf("no matching mode for widget %s", def.MDLName)
}

// evaluateCondition checks a built-in condition string against the AST widget.
func (e *PluggableWidgetEngine) evaluateCondition(condition string, w *ast.WidgetV3) bool {
	switch {
	case condition == "hasDataSource":
		return w.GetDataSource() != nil
	case condition == "hasAttribute":
		return w.GetAttribute() != ""
	case strings.HasPrefix(condition, "hasProp:"):
		propName := strings.TrimPrefix(condition, "hasProp:")
		return w.GetStringProp(propName) != ""
	default:
		return false
	}
}

// resolveMapping resolves a PropertyMapping's source into a BuildContext.
func (e *PluggableWidgetEngine) resolveMapping(mapping PropertyMapping, w *ast.WidgetV3) (*BuildContext, error) {
	ctx := &BuildContext{pageBuilder: e.pageBuilder}

	if mapping.Value != "" {
		ctx.PrimitiveVal = mapping.Value
		// AST overrides the def.json default: when the user explicitly sets the
		// property in MDL (e.g. `PageSize: 25`), that value wins over the
		// schema default ("20"). Without this, user-set primitive properties
		// silently fall back to defaults.
		if astVal, ok := lookupProperty(w.Properties, mapping.PropertyKey); ok {
			ctx.PrimitiveVal = stringifyAny(astVal)
		}
		return ctx, nil
	}

	source := mapping.Source
	if source == "" {
		return ctx, nil
	}

	switch source {
	case "Attribute":
		if attr := w.GetAttribute(); attr != "" {
			ctx.AttributePath = e.pageBuilder.resolveAttributePath(attr)
		}

	case "Attributes":
		if attrs := w.GetAttributes(); len(attrs) > 0 {
			ctx.AttributePaths = make([]string, 0, len(attrs))
			for _, attr := range attrs {
				ctx.AttributePaths = append(ctx.AttributePaths, e.pageBuilder.resolveAttributePath(attr))
			}
		}

	case "DataSource":
		if ds := w.GetDataSource(); ds != nil {
			dataSource, entityName, err := e.pageBuilder.buildDataSourceV3(ds)
			if err != nil {
				return nil, mdlerrors.NewBackend("build datasource", err)
			}
			ctx.DataSource = dataSource
			ctx.EntityName = entityName
			if entityName != "" {
				e.pageBuilder.entityContext = entityName
				if w.Name != "" {
					e.pageBuilder.paramEntityNames[w.Name] = entityName
				}
			}
		}

	case "Selection":
		val := w.GetSelection()
		if val == "" && mapping.Default != "" {
			val = mapping.Default
		}
		ctx.PrimitiveVal = val

	case "CaptionAttribute":
		if captionAttr := w.GetStringProp("CaptionAttribute"); captionAttr != "" {
			if !strings.Contains(captionAttr, ".") && e.pageBuilder.entityContext != "" {
				captionAttr = e.pageBuilder.entityContext + "." + captionAttr
			}
			ctx.AttributePath = captionAttr
		}

	case "Association":
		if attr := w.GetAttribute(); attr != "" {
			ctx.AssocPath = e.pageBuilder.resolveAssociationPath(attr)
		}
		ctx.EntityName = e.pageBuilder.entityContext
		if ctx.AssocPath != "" && ctx.EntityName == "" {
			return nil, mdlerrors.NewValidationf("association %q requires an entity context (add a DataSource mapping before Association)", ctx.AssocPath)
		}

	case "OnClick":
		if action := w.GetAction(); action != nil {
			act, err := e.pageBuilder.buildClientActionV3(action)
			if err != nil {
				return nil, mdlerrors.NewBackend("build action", err)
			}
			ctx.Action = act
		}

	default:
		val := w.GetStringProp(source)
		if val == "" {
			// Non-string AST values (e.g. `DesktopColumns: 3`, parsed as an int)
			// are invisible to GetStringProp; read them generically so numeric
			// properties aren't silently dropped to the schema default.
			if astVal, ok := lookupProperty(w.Properties, source); ok {
				val = stringifyAny(astVal)
			}
		}
		if val == "" && mapping.Default != "" {
			val = mapping.Default
		}
		ctx.PrimitiveVal = val
	}

	return ctx, nil
}

// applyObjectLists handles the def.json `objectLists` mappings. For each
// child of the AST widget whose Type matches an objectLists[].MDLContainer,
// it builds an ObjectListItemSpec by walking the child's properties and
// nested children, then hands the collected specs to the backend's
// SetObjectList for serialization.
func (e *PluggableWidgetEngine) applyObjectLists(builder backend.WidgetObjectBuilder, lists []ObjectListMapping, w *ast.WidgetV3) error {
	if len(lists) == 0 {
		return nil
	}
	// Index containers by uppercase keyword for matching against AST child Type.
	byContainer := make(map[string]*ObjectListMapping, len(lists))
	for i := range lists {
		byContainer[strings.ToUpper(lists[i].MDLContainer)] = &lists[i]
	}

	itemsByPropKey := make(map[string][]backend.ObjectListItemSpec)
	for _, child := range w.Children {
		mapping, ok := byContainer[strings.ToUpper(child.Type)]
		if !ok {
			continue
		}
		spec, err := e.buildObjectListItem(mapping, child)
		if err != nil {
			return err
		}
		itemsByPropKey[mapping.PropertyKey] = append(itemsByPropKey[mapping.PropertyKey], spec)
	}

	// Drive Set in def.json order so output is deterministic.
	for _, list := range lists {
		items := itemsByPropKey[list.PropertyKey]
		if len(items) == 0 {
			continue
		}
		builder.SetObjectList(list.PropertyKey, items)
	}
	return nil
}

// buildObjectListItem converts one AST child node (e.g. a `group panel1 (...)
// { ... }`) into an ObjectListItemSpec by:
//   - matching widget properties against ItemProperties (scalar dispatch)
//   - matching nested AST children against ItemSlots (widgets-typed slots)
//
// isChartSeriesContainer reports whether an object-list container keyword is a
// Mendix Charts series (SERIES for Bar/Column/Area/Pie; LINE for Line/Bubble/
// TimeSeries). Only these carry the static·/dynamic· dataSet-gated texttemplate
// sub-properties whose empty-ClientTemplate-when-visible rule differs from other
// object lists (Accordion groups, DataGrid columns). Chart series (9a).
func isChartSeriesContainer(container string) bool {
	switch strings.ToUpper(container) {
	case "SERIES", "LINE":
		return true
	}
	return false
}

// chartSeriesTextTemplateVisible reports whether a chart series' texttemplate
// sub-property is visible for the item's current dataSet mode + configured
// datasources, mirroring the widget's editorConfig `hideNestedPropertiesIn`
// gate. A visible-but-unset texttemplate must serialize an empty ClientTemplate
// (not null) or Studio Pro flags CE0463:
//   - the property's mode (static·/dynamic· name prefix) must match dataSet;
//   - a datasource-bound property (e.g. staticTooltipHoverText → staticDataSource)
//     is visible only when that datasource is configured on the item.
//
// An unbound property (e.g. staticName) is visible whenever its mode matches.
func chartSeriesTextTemplateVisible(ip ItemPropertyMapping, dataSetMode string, configuredDataSources map[string]pages.DataSource) bool {
	mode := "static"
	if strings.HasPrefix(strings.ToLower(ip.PropertyKey), "dynamic") {
		mode = "dynamic"
	}
	if dataSetMode == "" {
		dataSetMode = "static"
	}
	if !strings.EqualFold(dataSetMode, mode) {
		return false // hidden by the dataSet gate
	}
	if ip.DataSource != "" {
		_, configured := configuredDataSources[ip.DataSource]
		return configured
	}
	return true
}

// seriesDataSourceMatchesMode reports whether a chart-series datasource property
// key (staticDataSource / dynamicDataSource) is the one active for the given
// dataSet mode — used to route the friendly `DataSource:` alias. Chart series (9a).
func seriesDataSourceMatchesMode(propertyKey, dataSetMode string) bool {
	if dataSetMode == "" {
		dataSetMode = "static"
	}
	mode := "static"
	if strings.HasPrefix(strings.ToLower(propertyKey), "dynamic") {
		mode = "dynamic"
	}
	return strings.EqualFold(dataSetMode, mode)
}

func (e *PluggableWidgetEngine) buildObjectListItem(mapping *ObjectListMapping, child *ast.WidgetV3) (backend.ObjectListItemSpec, error) {
	spec := backend.ObjectListItemSpec{}
	// Track whether the user explicitly set Sortable / ShowContentAs in MDL —
	// drives the attribute-less and custom-content fallbacks below.
	_, sortableExplicit := lookupProperty(child.Properties, "Sortable")
	_, showContentAsExplicit := lookupProperty(child.Properties, "ShowContentAs")

	// Save/restore the page builder's entity context: an object-list item may
	// bring its OWN datasource (e.g. a chart `series`' staticDataSource), against
	// which the item's attribute sub-properties (staticXAttribute / staticY…)
	// must resolve — not the parent widget's context. Chart series (9a).
	savedEntityContext := e.pageBuilder.entityContext
	defer func() { e.pageBuilder.entityContext = savedEntityContext }()

	// A chart series' texttemplate visibility (and the DataSource: alias below)
	// depend on its dataSet mode (static/dynamic); default to static when unset,
	// matching the schema.
	itemDataSetMode := "static"
	if v, ok := lookupProperty(child.Properties, "dataSet"); ok {
		if s := stringifyAny(v); s != "" {
			itemDataSetMode = s
		}
	}

	// Pre-resolve any datasource-typed sub-property the MDL set, so attribute
	// sub-properties later in the loop resolve against the item's own entity
	// regardless of schema property order. The built DataSource is emitted in
	// the main loop's "datasource" case.
	prebuiltDataSources := make(map[string]pages.DataSource)
	for _, ip := range mapping.ItemProperties {
		if ip.Operation != "datasource" {
			continue
		}
		raw, ok := lookupProperty(child.Properties, ip.PropertyKey)
		if !ok {
			for _, alias := range ip.MdlAliases {
				if raw, ok = lookupProperty(child.Properties, alias); ok {
					break
				}
			}
		}
		// Friendly `DataSource:` alias inside a chart series routes to the
		// mode-appropriate datasource property (staticDataSource when
		// dataSet=static, dynamicDataSource when dynamic) — matching how the
		// top-level widget datasource is written. Chart series (9a).
		if !ok && isChartSeriesContainer(mapping.MDLContainer) && seriesDataSourceMatchesMode(ip.PropertyKey, itemDataSetMode) {
			raw, ok = lookupProperty(child.Properties, "DataSource")
		}
		if !ok {
			continue
		}
		ds, ok := raw.(*ast.DataSourceV3)
		if !ok {
			continue
		}
		dataSource, entityName, err := e.pageBuilder.buildDataSourceV3(ds)
		if err != nil {
			return spec, mdlerrors.NewBackend("datasource for object-list item property "+ip.PropertyKey, err)
		}
		prebuiltDataSources[ip.PropertyKey] = dataSource
		if entityName != "" {
			e.pageBuilder.entityContext = entityName
		}
	}

	// Scalar item properties: ItemProperties carries the operation kind per
	// sub-property key. Look up the value in the AST child's properties bag.
	for _, ip := range mapping.ItemProperties {
		// Property names in MDL are case-insensitive — find a match by lower-cased key.
		// Try the schema name first, then fall back to MDL aliases (e.g. Caption → header).
		// matchedAlias tracks which name actually hit, so we can find the matching
		// `<name>Params` companion (e.g. Caption → CaptionParams).
		raw, ok := lookupProperty(child.Properties, ip.PropertyKey)
		matchedAlias := ip.PropertyKey
		if !ok {
			for _, alias := range ip.MdlAliases {
				if raw, ok = lookupProperty(child.Properties, alias); ok {
					matchedAlias = alias
					break
				}
			}
		}
		if !ok {
			// MDL didn't set the property; if the .def.json schema carries a
			// non-empty primitive default, apply it. Without this, the engine
			// falls back to the embedded template's WidgetObject value, which
			// is the Mendix 11.6 snapshot and may drift from the project's
			// installed .mpk (e.g. column minWidth: template says "linked",
			// current schema says "auto").
			if ip.Operation == "primitive" && ip.Value != "" {
				spec.Properties = append(spec.Properties, backend.ObjectListItemProperty{
					PropertyKey:  ip.PropertyKey,
					Operation:    "primitive",
					PrimitiveVal: ip.Value,
				})
			}
			// A datasource resolved in the pre-pass via the friendly `DataSource:`
			// alias has no direct child.Properties[<schemaKey>] entry, so emit it
			// here from the pre-built map. Chart series (9a).
			if ds, dsOK := prebuiltDataSources[ip.PropertyKey]; dsOK && ds != nil {
				spec.Properties = append(spec.Properties, backend.ObjectListItemProperty{
					PropertyKey: ip.PropertyKey,
					Operation:   "datasource",
					DataSource:  ds,
				})
			}
			// A VISIBLE-but-unset texttemplate sub-property of a chart series must
			// serialize as an empty Forms$ClientTemplate, not null, or Studio Pro
			// flags CE0463. Visibility follows the widget's editorConfig dataSet
			// gate + dataSource binding. Scoped to chart series so non-chart
			// object lists (Accordion groups, DataGrid columns) are untouched. (9a)
			if ip.Operation == "texttemplate" && isChartSeriesContainer(mapping.MDLContainer) &&
				chartSeriesTextTemplateVisible(ip, itemDataSetMode, prebuiltDataSources) {
				spec.Properties = append(spec.Properties, backend.ObjectListItemProperty{
					PropertyKey:   ip.PropertyKey,
					Operation:     "texttemplate",
					EmptyTemplate: true,
				})
			}
			continue
		}
		strVal := stringifyAny(raw)
		prop := backend.ObjectListItemProperty{
			PropertyKey: ip.PropertyKey,
			Operation:   ip.Operation,
		}
		switch ip.Operation {
		case "primitive":
			prop.PrimitiveVal = strVal
		case "expression":
			prop.Expression = strVal
		case "texttemplate":
			prop.TextTemplate = strVal
			prop.EntityContext = e.pageBuilder.entityContext
			// Look up the matching params companion in the AST. Convention:
			// when MDL writes `Caption: '{1}'` it pairs with `CaptionParams:
			// [{1} = attr]`. The companion key is the matched name (alias or
			// schema name) + "Params".
			if paramsRaw, ok := child.Properties[matchedAlias+"Params"]; ok {
				if astParams, ok := paramsRaw.([]ast.ParamAssignmentV3); ok && len(astParams) > 0 {
					prop.Parameters = e.pageBuilder.buildClientTemplateParams(astParams)
				}
			}
		case "attribute":
			// An attribute navigated over associations (e.g. Order_Customer/Name)
			// resolves to a final attribute + association steps (AttributeRef.EntityRef);
			// a flat path is left as-is. Mirrors the DynamicText contentparam path.
			if finalQN, steps, ok := e.pageBuilder.resolveAssociationAttributePath(strVal); ok {
				prop.AttributePath = finalQN
				prop.AttributeRefSteps = steps
			} else if e.pageBuilder.entityContext != "" {
				prop.AttributePath = e.pageBuilder.resolveAttributePath(strVal)
			} else {
				prop.AttributePath = strVal
			}
		case "datasource":
			// Emit the datasource pre-resolved above (which also set the item's
			// entity context for the attribute sub-props). Chart series (9a).
			ds, ok := prebuiltDataSources[ip.PropertyKey]
			if !ok || ds == nil {
				continue
			}
			prop.DataSource = ds
		default:
			// Remaining unsupported sub-property kinds (action) still need richer
			// AST context than the child's property bag.
			// TODO(#538 follow-up): action expressions inside object-list item
			// property positions (e.g. chart series staticOnClickAction).
			continue
		}
		spec.Properties = append(spec.Properties, prop)
	}

	// DataGrid column header convention: when the user provides no Caption
	// but does bind an Attribute, fall back to the attribute name as the
	// header text. Mirrors buildDataGrid2ColumnObject in datagrid_builder.go
	// (line 491-494). Without this, an attribute column with no Caption
	// emits an empty header that Studio Pro flags as definition drift.
	applyColumnHeaderFallback(&spec)

	// DataGrid column sortable convention: attribute-less columns (typical
	// "Actions" custom-content columns) default to sortable=false, since
	// Studio Pro errors on sortable=true without an Attribute. The keyword
	// path applies the same fallback (see datagrid_builder.go line 545+).
	applyColumnSortableFallback(&spec, sortableExplicit)

	// Widgets-typed slots: ItemSlots gives us per-slot keyword conventions.
	// For object-list items the most common shape today is direct child
	// widgets (no inner container). Match nested AST children in three
	// passes:
	//   (a) MDLContainer name match (e.g. HEADERCONTENT block inside group)
	//   (b) AcceptedChildTypes match (e.g. textfilter inside a column body
	//       routes to the column's filter slot)
	//   (c) Anything else → default Widgets-typed slot (usually content)
	if len(child.Children) > 0 {
		spec.ChildWidgets = make(map[string][]pages.Widget)
		// Index slot containers + accepted child types by uppercase keyword.
		slotByContainer := make(map[string]string)
		acceptedTypeToSlot := make(map[string]string)
		for _, slot := range mapping.ItemSlots {
			slotByContainer[strings.ToUpper(slot.MDLContainer)] = slot.PropertyKey
			for _, t := range slot.AcceptedChildTypes {
				acceptedTypeToSlot[strings.ToUpper(t)] = slot.PropertyKey
			}
		}

		// Pass (a): explicit container blocks → matched slot.
		// Pass (b): widget Type matches an AcceptedChildTypes entry → that slot.
		// Pass (c): everything else routes via the default slot.
		var unmatched []*ast.WidgetV3
		for _, gc := range child.Children {
			gcTypeUpper := strings.ToUpper(gc.Type)
			if propKey, ok := slotByContainer[gcTypeUpper]; ok {
				for _, slotChild := range gc.Children {
					widget, err := e.pageBuilder.buildWidgetV3(slotChild)
					if err != nil {
						return spec, err
					}
					if widget != nil {
						spec.ChildWidgets[propKey] = append(spec.ChildWidgets[propKey], widget)
					}
				}
				continue
			}
			if propKey, ok := acceptedTypeToSlot[gcTypeUpper]; ok {
				widget, err := e.pageBuilder.buildWidgetV3(gc)
				if err != nil {
					return spec, err
				}
				if widget != nil {
					spec.ChildWidgets[propKey] = append(spec.ChildWidgets[propKey], widget)
				}
				continue
			}
			unmatched = append(unmatched, gc)
		}

		// Pass (c): unmatched widgets → default Widgets-typed slot.
		if len(unmatched) > 0 {
			defaultKey := defaultItemSlotKey(mapping)
			if defaultKey != "" {
				for _, gc := range unmatched {
					widget, err := e.pageBuilder.buildWidgetV3(gc)
					if err != nil {
						return spec, err
					}
					if widget != nil {
						spec.ChildWidgets[defaultKey] = append(spec.ChildWidgets[defaultKey], widget)
					}
				}
			}
		}
	}

	// DataGrid column showContentAs convention: when child widgets landed in
	// the `content` slot without an explicit ShowContentAs in MDL, auto-infer
	// customContent. Mirrors hasCustomContent in datagrid_builder.go. Must
	// run after the child-routing pass so spec.ChildWidgets is populated.
	applyColumnShowContentAsFallback(&spec, showContentAsExplicit, len(spec.ChildWidgets["content"]) > 0)

	return spec, nil
}

// defaultItemSlotKey picks a "default" widgets-typed slot for an object-list
// item: the slot keyed "content" if present, otherwise the first slot.
// Returns "" if there are no widgets-typed slots.
// applyColumnHeaderFallback synthesizes a texttemplate spec for the `header`
// property when the spec has an attribute binding but no header text. Mirrors
// the keyword path's `if caption == "" { caption = col.Attribute }` fallback
// in datagrid_builder.go. The check is conservative: only fires when the
// header slot is genuinely empty, so it's safe to call for any object-list
// item kind.
func applyColumnHeaderFallback(spec *backend.ObjectListItemSpec) {
	var hasHeader bool
	var attrPath string
	for _, p := range spec.Properties {
		switch p.PropertyKey {
		case "header":
			hasHeader = true
		case "attribute":
			attrPath = p.AttributePath
		}
	}
	if hasHeader || attrPath == "" {
		return
	}
	// Extract the leaf attribute name from a fully-qualified path
	// (Module.Entity.Attr → Attr).
	attrName := attrPath
	if idx := strings.LastIndex(attrName, "."); idx >= 0 {
		attrName = attrName[idx+1:]
	}
	spec.Properties = append(spec.Properties, backend.ObjectListItemProperty{
		PropertyKey:   "header",
		Operation:     "texttemplate",
		TextTemplate:  attrName,
		EntityContext: "", // literal text — no template params to resolve
	})
}

// applyColumnShowContentAsFallback forces showContentAs to "customContent"
// when the column has child widgets in its `content` slot but no explicit
// ShowContentAs in MDL. Mirrors the keyword path's `hasCustomContent :=
// len(contentWidgets) > 0` heuristic (datagrid_builder.go line 257). Studio
// Pro errors on `Show: Attribute` when no Attribute is set; auto-inferring
// customContent from the presence of cell-content widgets matches what
// users expect: `column foo { actionbutton x }` means "the cell renders
// the button".
func applyColumnShowContentAsFallback(spec *backend.ObjectListItemSpec, showContentAsExplicit bool, hasContentWidgets bool) {
	if showContentAsExplicit || !hasContentWidgets {
		return
	}
	for i, p := range spec.Properties {
		if p.PropertyKey == "showContentAs" {
			spec.Properties[i].PrimitiveVal = "customContent"
			return
		}
	}
	spec.Properties = append(spec.Properties, backend.ObjectListItemProperty{
		PropertyKey:  "showContentAs",
		Operation:    "primitive",
		PrimitiveVal: "customContent",
	})
}

// applyColumnSortableFallback forces `sortable` to "false" on attribute-less
// DataGrid columns (the typical "Actions" custom-content column). Studio Pro
// flags `sortable=true` + no Attribute as an authoring error (`An attribute
// is required when column sorting is enabled`); the keyword path defaults
// sortable to false when col.Attribute is empty
// (see datagrid_builder.go line 545+).
//
// Conservative: only fires when the user didn't explicitly set Sortable in
// MDL — an explicit `Sortable: true` on an attribute-less column is left
// alone (the user's mistake, surfaced by mx check).
func applyColumnSortableFallback(spec *backend.ObjectListItemSpec, sortableExplicit bool) {
	if sortableExplicit {
		return
	}
	var hasAttribute bool
	var sortableIdx = -1
	for i, p := range spec.Properties {
		switch p.PropertyKey {
		case "attribute":
			if p.AttributePath != "" {
				hasAttribute = true
			}
		case "sortable":
			sortableIdx = i
		}
	}
	if hasAttribute {
		return
	}
	if sortableIdx >= 0 {
		spec.Properties[sortableIdx].PrimitiveVal = "false"
		return
	}
	spec.Properties = append(spec.Properties, backend.ObjectListItemProperty{
		PropertyKey:  "sortable",
		Operation:    "primitive",
		PrimitiveVal: "false",
	})
}

func defaultItemSlotKey(mapping *ObjectListMapping) string {
	if len(mapping.ItemSlots) == 0 {
		return ""
	}
	for _, s := range mapping.ItemSlots {
		if s.PropertyKey == "content" {
			return s.PropertyKey
		}
	}
	return mapping.ItemSlots[0].PropertyKey
}

// lookupProperty does a case-insensitive lookup against an AST property map.
// MDL property names ignore case (e.g. `HeaderText` and `headerText` both match).
func lookupProperty(props map[string]any, key string) (any, bool) {
	if v, ok := props[key]; ok {
		return v, true
	}
	lower := strings.ToLower(key)
	for k, v := range props {
		if strings.ToLower(k) == lower {
			return v, true
		}
	}
	return nil, false
}

// stringifyAny converts a property value of arbitrary type to its string form
// for use in Set* methods. Returns "" for unknown types.
func stringifyAny(v any) string {
	switch x := v.(type) {
	case string:
		return x
	case bool:
		return fmt.Sprintf("%t", x)
	case int:
		return fmt.Sprintf("%d", x)
	case float64:
		return fmt.Sprintf("%g", x)
	}
	return ""
}

// applyChildSlots processes child slot mappings, building child widgets and embedding them.
// objectListContainers is the set of MDLContainer keywords (uppercase) that
// belong to objectLists mappings — those children are skipped here because
// applyObjectLists handles them.
func (e *PluggableWidgetEngine) applyChildSlots(builder backend.WidgetObjectBuilder, slots []ChildSlotMapping, w *ast.WidgetV3, propertyTypeIDs map[string]pages.PropertyTypeIDEntry, objectListContainers map[string]bool) error {
	if len(slots) == 0 {
		return nil
	}

	slotContainers := make(map[string]*ChildSlotMapping, len(slots))
	for i := range slots {
		slotContainers[slots[i].MDLContainer] = &slots[i]
	}

	slotWidgets := make(map[string][]pages.Widget)
	var defaultWidgets []pages.Widget

	for _, child := range w.Children {
		// Skip children whose keyword belongs to an object-list mapping.
		if objectListContainers[strings.ToUpper(child.Type)] {
			continue
		}
		lowerType := strings.ToLower(child.Type)
		if slot, ok := slotContainers[lowerType]; ok {
			for _, slotChild := range child.Children {
				widget, err := e.pageBuilder.buildWidgetV3(slotChild)
				if err != nil {
					return err
				}
				if widget != nil {
					slotWidgets[slot.PropertyKey] = append(slotWidgets[slot.PropertyKey], widget)
				}
			}
		} else {
			widget, err := e.pageBuilder.buildWidgetV3(child)
			if err != nil {
				return err
			}
			if widget != nil {
				defaultWidgets = append(defaultWidgets, widget)
			}
		}
	}

	for _, slot := range slots {
		children := slotWidgets[slot.PropertyKey]
		if len(children) == 0 && len(defaultWidgets) > 0 && slot.MDLContainer == defaultSlotContainer {
			children = defaultWidgets
			defaultWidgets = nil
		}
		if len(children) == 0 {
			continue
		}

		ctx := &BuildContext{}
		if slot.Operation != "widgets" {
			return mdlerrors.NewValidationf("childSlots operation must be %q, got %q for property %s", "widgets", slot.Operation, slot.PropertyKey)
		}
		if err := e.applyOperation(builder, slot.Operation, slot.PropertyKey, ctx); err != nil {
			return err
		}
		// SetChildWidgets directly — applyOperation skips "widgets" since ctx doesn't carry children
		builder.SetChildWidgets(slot.PropertyKey, children)
	}

	return nil
}

// isBuiltinPropName returns true for property names that are handled by
// dedicated MDL keywords (DataSource, Attribute, etc.) rather than by
// the explicit property pass.
func isBuiltinPropName(name string) bool {
	switch name {
	case "DataSource", "Attribute", "Label", "Caption", "Action",
		"Selection", "Class", "Style", "DynamicClasses", "Editable", "Visible",
		"WidgetType", "DesignProperties", "Association", "CaptionAttribute",
		"Content", "RenderMode", "ContentParams", "CaptionParams",
		"ButtonStyle", "DesktopWidth", "DesktopColumns", "TabletColumns",
		"PhoneColumns", "PageSize", "Pagination", "PagingPosition",
		"ShowPagingButtons", "Attributes", "FilterType", "Width", "Height",
		"Tooltip", "Name":
		return true
	}
	return false
}
