//go:build ignore

// Command gen_unsupported generates unsupported_gen.go: a struct that
// implements every method of backend.FullBackend by returning a clear
// "not supported by MCP backend" error.
//
// The MCP backend embeds this base and overrides only the operations it
// actually supports (entity writes via PED, plus the reads those need
// delegated to a local .mpr). Everything else errors loudly rather than
// silently no-opping or — dangerously — writing to the on-disk .mpr while
// Studio Pro holds the model in memory.
//
// Regenerate with:  go generate ./mdl/backend/mcp/...
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"reflect"
	"sort"
	"strings"

	"github.com/JordtenBulte-OLC/mxcli/mdl/backend"
)

func main() {
	iface := reflect.TypeOf((*backend.FullBackend)(nil)).Elem()

	imports := map[string]string{} // pkgPath -> alias
	var methods []string

	for i := 0; i < iface.NumMethod(); i++ {
		m := iface.Method(i)
		methods = append(methods, renderMethod(m, imports))
	}
	sort.Strings(methods)

	var buf bytes.Buffer
	buf.WriteString("// Code generated by gen_unsupported.go; DO NOT EDIT.\n\n")
	buf.WriteString("package mcp\n\n")
	buf.WriteString("import (\n")
	var paths []string
	for p := range imports {
		paths = append(paths, p)
	}
	sort.Strings(paths)
	for _, p := range paths {
		fmt.Fprintf(&buf, "\t%s %q\n", imports[p], p)
	}
	buf.WriteString(")\n\n")
	buf.WriteString("// unsupportedBackend implements backend.FullBackend with every method\n")
	buf.WriteString("// returning errUnsupported. The MCP backend embeds it and overrides the\n")
	buf.WriteString("// operations it genuinely supports.\n")
	buf.WriteString("type unsupportedBackend struct{}\n\n")
	for _, mth := range methods {
		buf.WriteString(mth)
		buf.WriteString("\n")
	}

	out, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Fprintln(os.Stderr, buf.String())
		fmt.Fprintf(os.Stderr, "format: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile("unsupported_gen.go", out, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("generated unsupported_gen.go (%d methods)\n", len(methods))
}

var errorType = reflect.TypeOf((*error)(nil)).Elem()

func renderMethod(m reflect.Method, imports map[string]string) string {
	mt := m.Type

	// params
	var params []string
	for i := 0; i < mt.NumIn(); i++ {
		t := mt.In(i)
		ts := typeString(t, imports)
		if mt.IsVariadic() && i == mt.NumIn()-1 {
			ts = "..." + typeString(t.Elem(), imports)
		}
		params = append(params, fmt.Sprintf("_ %s", ts))
	}

	// results — name them so a naked return yields zero values; assign the
	// last error-typed result to errUnsupported.
	var results []string
	errIdx := -1
	for i := 0; i < mt.NumOut(); i++ {
		t := mt.Out(i)
		name := fmt.Sprintf("r%d", i)
		if t == errorType {
			name = fmt.Sprintf("err%d", i)
			errIdx = i
		}
		results = append(results, fmt.Sprintf("%s %s", name, typeString(t, imports)))
	}

	var b strings.Builder
	fmt.Fprintf(&b, "func (unsupportedBackend) %s(%s)", m.Name, strings.Join(params, ", "))
	switch len(results) {
	case 0:
		b.WriteString(" {\n")
	default:
		fmt.Fprintf(&b, " (%s) {\n", strings.Join(results, ", "))
	}
	if errIdx >= 0 {
		fmt.Fprintf(&b, "\terr%d = errUnsupported(%q)\n", errIdx, m.Name)
	}
	b.WriteString("\treturn\n}\n")
	return b.String()
}

// typeString renders t as Go source, recording any package imports needed.
func typeString(t reflect.Type, imports map[string]string) string {
	if t.PkgPath() != "" && t.Name() != "" {
		return pkgAlias(t.PkgPath(), imports) + "." + t.Name()
	}
	switch t.Kind() {
	case reflect.Ptr:
		return "*" + typeString(t.Elem(), imports)
	case reflect.Slice:
		return "[]" + typeString(t.Elem(), imports)
	case reflect.Array:
		return fmt.Sprintf("[%d]%s", t.Len(), typeString(t.Elem(), imports))
	case reflect.Map:
		return "map[" + typeString(t.Key(), imports) + "]" + typeString(t.Elem(), imports)
	case reflect.Chan:
		return "chan " + typeString(t.Elem(), imports)
	case reflect.Interface:
		if t.NumMethod() == 0 {
			return "any"
		}
		return t.String()
	case reflect.Func:
		return funcTypeString(t, imports)
	default:
		// builtins (string, int, bool, ...)
		return t.String()
	}
}

func funcTypeString(t reflect.Type, imports map[string]string) string {
	var in []string
	for i := 0; i < t.NumIn(); i++ {
		ts := typeString(t.In(i), imports)
		if t.IsVariadic() && i == t.NumIn()-1 {
			ts = "..." + typeString(t.In(i).Elem(), imports)
		}
		in = append(in, ts)
	}
	var out []string
	for i := 0; i < t.NumOut(); i++ {
		out = append(out, typeString(t.Out(i), imports))
	}
	s := "func(" + strings.Join(in, ", ") + ")"
	switch len(out) {
	case 0:
	case 1:
		s += " " + out[0]
	default:
		s += " (" + strings.Join(out, ", ") + ")"
	}
	return s
}

func pkgAlias(path string, imports map[string]string) string {
	if a, ok := imports[path]; ok {
		return a
	}
	seg := path
	if i := strings.LastIndex(path, "/"); i >= 0 {
		seg = path[i+1:]
	}
	alias := strings.ReplaceAll(seg, "-", "_")
	alias = strings.ReplaceAll(alias, ".", "_")
	// de-dup against existing aliases
	base := alias
	for n := 2; ; n++ {
		clash := false
		for _, a := range imports {
			if a == alias {
				clash = true
				break
			}
		}
		if !clash {
			break
		}
		alias = fmt.Sprintf("%s%d", base, n)
	}
	imports[path] = alias
	return alias
}
