// Code generated by gen_unsupported.go; DO NOT EDIT.

package mcp

import (
	backend "github.com/JordtenBulte-OLC/mxcli/mdl/backend"
	types "github.com/JordtenBulte-OLC/mxcli/mdl/types"
	model "github.com/JordtenBulte-OLC/mxcli/model"
	agenteditor "github.com/JordtenBulte-OLC/mxcli/sdk/agenteditor"
	domainmodel "github.com/JordtenBulte-OLC/mxcli/sdk/domainmodel"
	javaactions "github.com/JordtenBulte-OLC/mxcli/sdk/javaactions"
	microflows "github.com/JordtenBulte-OLC/mxcli/sdk/microflows"
	pages "github.com/JordtenBulte-OLC/mxcli/sdk/pages"
	security "github.com/JordtenBulte-OLC/mxcli/sdk/security"
	workflows "github.com/JordtenBulte-OLC/mxcli/sdk/workflows"
)

// unsupportedBackend implements backend.FullBackend with every method
// returning errUnsupported. The MCP backend embeds it and overrides the
// operations it genuinely supports.
type unsupportedBackend struct{}

func (unsupportedBackend) AddAttribute(_ model.ID, _ model.ID, _ *domainmodel.Attribute) (err0 error) {
	err0 = errUnsupported("AddAttribute")
	return
}

func (unsupportedBackend) AddDemoUser(_ model.ID, _ string, _ string, _ string, _ []string) (err0 error) {
	err0 = errUnsupported("AddDemoUser")
	return
}

func (unsupportedBackend) AddEntityAccessRule(_ backend.EntityAccessRuleParams) (err0 error) {
	err0 = errUnsupported("AddEntityAccessRule")
	return
}

func (unsupportedBackend) AddModuleRole(_ model.ID, _ string, _ string) (err0 error) {
	err0 = errUnsupported("AddModuleRole")
	return
}

func (unsupportedBackend) AddUserRole(_ model.ID, _ string, _ []string, _ bool) (err0 error) {
	err0 = errUnsupported("AddUserRole")
	return
}

func (unsupportedBackend) AlterUserRoleModuleRoles(_ model.ID, _ string, _ bool, _ []string) (err0 error) {
	err0 = errUnsupported("AlterUserRoleModuleRoles")
	return
}

func (unsupportedBackend) BuildCreateAttributeObject(_ string, _ string, _ string, _ string) (r0 any, err1 error) {
	err1 = errUnsupported("BuildCreateAttributeObject")
	return
}

func (unsupportedBackend) BuildFilterWidget(_ backend.FilterWidgetSpec, _ string) (r0 pages.Widget, err1 error) {
	err1 = errUnsupported("BuildFilterWidget")
	return
}

func (unsupportedBackend) Commit() (err0 error) {
	err0 = errUnsupported("Commit")
	return
}

func (unsupportedBackend) Connect(_ string) (err0 error) {
	err0 = errUnsupported("Connect")
	return
}

func (unsupportedBackend) ContentsDir() (r0 string) {
	return
}

func (unsupportedBackend) CreateAgentEditorAgent(_ *agenteditor.Agent) (err0 error) {
	err0 = errUnsupported("CreateAgentEditorAgent")
	return
}

func (unsupportedBackend) CreateAgentEditorConsumedMCPService(_ *agenteditor.ConsumedMCPService) (err0 error) {
	err0 = errUnsupported("CreateAgentEditorConsumedMCPService")
	return
}

func (unsupportedBackend) CreateAgentEditorKnowledgeBase(_ *agenteditor.KnowledgeBase) (err0 error) {
	err0 = errUnsupported("CreateAgentEditorKnowledgeBase")
	return
}

func (unsupportedBackend) CreateAgentEditorModel(_ *agenteditor.Model) (err0 error) {
	err0 = errUnsupported("CreateAgentEditorModel")
	return
}

func (unsupportedBackend) CreateAssociation(_ model.ID, _ *domainmodel.Association) (err0 error) {
	err0 = errUnsupported("CreateAssociation")
	return
}

func (unsupportedBackend) CreateBusinessEventService(_ *model.BusinessEventService) (err0 error) {
	err0 = errUnsupported("CreateBusinessEventService")
	return
}

func (unsupportedBackend) CreateConstant(_ *model.Constant) (err0 error) {
	err0 = errUnsupported("CreateConstant")
	return
}

func (unsupportedBackend) CreateConsumedODataService(_ *model.ConsumedODataService) (err0 error) {
	err0 = errUnsupported("CreateConsumedODataService")
	return
}

func (unsupportedBackend) CreateConsumedRestService(_ *model.ConsumedRestService) (err0 error) {
	err0 = errUnsupported("CreateConsumedRestService")
	return
}

func (unsupportedBackend) CreateCrossAssociation(_ model.ID, _ *domainmodel.CrossModuleAssociation) (err0 error) {
	err0 = errUnsupported("CreateCrossAssociation")
	return
}

func (unsupportedBackend) CreateDataTransformer(_ *model.DataTransformer) (err0 error) {
	err0 = errUnsupported("CreateDataTransformer")
	return
}

func (unsupportedBackend) CreateDatabaseConnection(_ *model.DatabaseConnection) (err0 error) {
	err0 = errUnsupported("CreateDatabaseConnection")
	return
}

func (unsupportedBackend) CreateEntity(_ model.ID, _ *domainmodel.Entity) (err0 error) {
	err0 = errUnsupported("CreateEntity")
	return
}

func (unsupportedBackend) CreateEnumeration(_ *model.Enumeration) (err0 error) {
	err0 = errUnsupported("CreateEnumeration")
	return
}

func (unsupportedBackend) CreateExportMapping(_ *model.ExportMapping) (err0 error) {
	err0 = errUnsupported("CreateExportMapping")
	return
}

func (unsupportedBackend) CreateFolder(_ *model.Folder) (err0 error) {
	err0 = errUnsupported("CreateFolder")
	return
}

func (unsupportedBackend) CreateImageCollection(_ *types.ImageCollection) (err0 error) {
	err0 = errUnsupported("CreateImageCollection")
	return
}

func (unsupportedBackend) CreateImportMapping(_ *model.ImportMapping) (err0 error) {
	err0 = errUnsupported("CreateImportMapping")
	return
}

func (unsupportedBackend) CreateJavaAction(_ *javaactions.JavaAction) (err0 error) {
	err0 = errUnsupported("CreateJavaAction")
	return
}

func (unsupportedBackend) CreateJavaScriptAction(_ *types.JavaScriptAction) (err0 error) {
	err0 = errUnsupported("CreateJavaScriptAction")
	return
}

func (unsupportedBackend) CreateJsonStructure(_ *types.JsonStructure) (err0 error) {
	err0 = errUnsupported("CreateJsonStructure")
	return
}

func (unsupportedBackend) CreateLayout(_ *pages.Layout) (err0 error) {
	err0 = errUnsupported("CreateLayout")
	return
}

func (unsupportedBackend) CreateMicroflow(_ *microflows.Microflow) (err0 error) {
	err0 = errUnsupported("CreateMicroflow")
	return
}

func (unsupportedBackend) CreateModule(_ *model.Module) (err0 error) {
	err0 = errUnsupported("CreateModule")
	return
}

func (unsupportedBackend) CreateNanoflow(_ *microflows.Nanoflow) (err0 error) {
	err0 = errUnsupported("CreateNanoflow")
	return
}

func (unsupportedBackend) CreatePage(_ *pages.Page) (err0 error) {
	err0 = errUnsupported("CreatePage")
	return
}

func (unsupportedBackend) CreatePublishedODataService(_ *model.PublishedODataService) (err0 error) {
	err0 = errUnsupported("CreatePublishedODataService")
	return
}

func (unsupportedBackend) CreatePublishedRestService(_ *model.PublishedRestService) (err0 error) {
	err0 = errUnsupported("CreatePublishedRestService")
	return
}

func (unsupportedBackend) CreateSnippet(_ *pages.Snippet) (err0 error) {
	err0 = errUnsupported("CreateSnippet")
	return
}

func (unsupportedBackend) CreateViewEntitySourceDocument(_ model.ID, _ string, _ string, _ string, _ string) (r0 model.ID, err1 error) {
	err1 = errUnsupported("CreateViewEntitySourceDocument")
	return
}

func (unsupportedBackend) CreateWorkflow(_ *workflows.Workflow) (err0 error) {
	err0 = errUnsupported("CreateWorkflow")
	return
}

func (unsupportedBackend) DeleteAgentEditorAgent(_ string) (err0 error) {
	err0 = errUnsupported("DeleteAgentEditorAgent")
	return
}

func (unsupportedBackend) DeleteAgentEditorConsumedMCPService(_ string) (err0 error) {
	err0 = errUnsupported("DeleteAgentEditorConsumedMCPService")
	return
}

func (unsupportedBackend) DeleteAgentEditorKnowledgeBase(_ string) (err0 error) {
	err0 = errUnsupported("DeleteAgentEditorKnowledgeBase")
	return
}

func (unsupportedBackend) DeleteAgentEditorModel(_ string) (err0 error) {
	err0 = errUnsupported("DeleteAgentEditorModel")
	return
}

func (unsupportedBackend) DeleteAssociation(_ model.ID, _ model.ID) (err0 error) {
	err0 = errUnsupported("DeleteAssociation")
	return
}

func (unsupportedBackend) DeleteAttribute(_ model.ID, _ model.ID, _ model.ID) (err0 error) {
	err0 = errUnsupported("DeleteAttribute")
	return
}

func (unsupportedBackend) DeleteBusinessEventService(_ model.ID) (err0 error) {
	err0 = errUnsupported("DeleteBusinessEventService")
	return
}

func (unsupportedBackend) DeleteConstant(_ model.ID) (err0 error) {
	err0 = errUnsupported("DeleteConstant")
	return
}

func (unsupportedBackend) DeleteConsumedODataService(_ model.ID) (err0 error) {
	err0 = errUnsupported("DeleteConsumedODataService")
	return
}

func (unsupportedBackend) DeleteConsumedRestService(_ model.ID) (err0 error) {
	err0 = errUnsupported("DeleteConsumedRestService")
	return
}

func (unsupportedBackend) DeleteCrossAssociation(_ model.ID, _ model.ID) (err0 error) {
	err0 = errUnsupported("DeleteCrossAssociation")
	return
}

func (unsupportedBackend) DeleteDataTransformer(_ model.ID) (err0 error) {
	err0 = errUnsupported("DeleteDataTransformer")
	return
}

func (unsupportedBackend) DeleteDatabaseConnection(_ model.ID) (err0 error) {
	err0 = errUnsupported("DeleteDatabaseConnection")
	return
}

func (unsupportedBackend) DeleteEntity(_ model.ID, _ model.ID) (err0 error) {
	err0 = errUnsupported("DeleteEntity")
	return
}

func (unsupportedBackend) DeleteEnumeration(_ model.ID) (err0 error) {
	err0 = errUnsupported("DeleteEnumeration")
	return
}

func (unsupportedBackend) DeleteExportMapping(_ model.ID) (err0 error) {
	err0 = errUnsupported("DeleteExportMapping")
	return
}

func (unsupportedBackend) DeleteFolder(_ model.ID) (err0 error) {
	err0 = errUnsupported("DeleteFolder")
	return
}

func (unsupportedBackend) DeleteImageCollection(_ string) (err0 error) {
	err0 = errUnsupported("DeleteImageCollection")
	return
}

func (unsupportedBackend) DeleteImportMapping(_ model.ID) (err0 error) {
	err0 = errUnsupported("DeleteImportMapping")
	return
}

func (unsupportedBackend) DeleteJavaAction(_ model.ID) (err0 error) {
	err0 = errUnsupported("DeleteJavaAction")
	return
}

func (unsupportedBackend) DeleteJavaScriptAction(_ model.ID) (err0 error) {
	err0 = errUnsupported("DeleteJavaScriptAction")
	return
}

func (unsupportedBackend) DeleteJavaScriptSourceFile(_ string, _ string) (err0 error) {
	err0 = errUnsupported("DeleteJavaScriptSourceFile")
	return
}

func (unsupportedBackend) DeleteJavaSourceFile(_ string, _ string) (err0 error) {
	err0 = errUnsupported("DeleteJavaSourceFile")
	return
}

func (unsupportedBackend) DeleteJsonStructure(_ string) (err0 error) {
	err0 = errUnsupported("DeleteJsonStructure")
	return
}

func (unsupportedBackend) DeleteLayout(_ model.ID) (err0 error) {
	err0 = errUnsupported("DeleteLayout")
	return
}

func (unsupportedBackend) DeleteMicroflow(_ model.ID) (err0 error) {
	err0 = errUnsupported("DeleteMicroflow")
	return
}

func (unsupportedBackend) DeleteModule(_ model.ID) (err0 error) {
	err0 = errUnsupported("DeleteModule")
	return
}

func (unsupportedBackend) DeleteModuleWithCleanup(_ model.ID, _ string) (err0 error) {
	err0 = errUnsupported("DeleteModuleWithCleanup")
	return
}

func (unsupportedBackend) DeleteNanoflow(_ model.ID) (err0 error) {
	err0 = errUnsupported("DeleteNanoflow")
	return
}

func (unsupportedBackend) DeletePage(_ model.ID) (err0 error) {
	err0 = errUnsupported("DeletePage")
	return
}

func (unsupportedBackend) DeletePublishedODataService(_ model.ID) (err0 error) {
	err0 = errUnsupported("DeletePublishedODataService")
	return
}

func (unsupportedBackend) DeletePublishedRestService(_ model.ID) (err0 error) {
	err0 = errUnsupported("DeletePublishedRestService")
	return
}

func (unsupportedBackend) DeleteSnippet(_ model.ID) (err0 error) {
	err0 = errUnsupported("DeleteSnippet")
	return
}

func (unsupportedBackend) DeleteViewEntitySourceDocument(_ model.ID) (err0 error) {
	err0 = errUnsupported("DeleteViewEntitySourceDocument")
	return
}

func (unsupportedBackend) DeleteViewEntitySourceDocumentByName(_ string, _ string) (err0 error) {
	err0 = errUnsupported("DeleteViewEntitySourceDocumentByName")
	return
}

func (unsupportedBackend) DeleteWorkflow(_ model.ID) (err0 error) {
	err0 = errUnsupported("DeleteWorkflow")
	return
}

func (unsupportedBackend) Disconnect() (err0 error) {
	err0 = errUnsupported("Disconnect")
	return
}

func (unsupportedBackend) ExportJSON() (r0 []uint8, err1 error) {
	err1 = errUnsupported("ExportJSON")
	return
}

func (unsupportedBackend) FindAllCustomWidgetTypes(_ string) (r0 []*types.RawCustomWidgetType, err1 error) {
	err1 = errUnsupported("FindAllCustomWidgetTypes")
	return
}

func (unsupportedBackend) FindAllViewEntitySourceDocumentIDs(_ string, _ string) (r0 []model.ID, err1 error) {
	err1 = errUnsupported("FindAllViewEntitySourceDocumentIDs")
	return
}

func (unsupportedBackend) FindCustomWidgetType(_ string) (r0 *types.RawCustomWidgetType, err1 error) {
	err1 = errUnsupported("FindCustomWidgetType")
	return
}

func (unsupportedBackend) FindViewEntitySourceDocumentID(_ string, _ string) (r0 model.ID, err1 error) {
	err1 = errUnsupported("FindViewEntitySourceDocumentID")
	return
}

func (unsupportedBackend) GetConstant(_ model.ID) (r0 *model.Constant, err1 error) {
	err1 = errUnsupported("GetConstant")
	return
}

func (unsupportedBackend) GetDomainModel(_ model.ID) (r0 *domainmodel.DomainModel, err1 error) {
	err1 = errUnsupported("GetDomainModel")
	return
}

func (unsupportedBackend) GetDomainModelByID(_ model.ID) (r0 *domainmodel.DomainModel, err1 error) {
	err1 = errUnsupported("GetDomainModelByID")
	return
}

func (unsupportedBackend) GetEnumeration(_ model.ID) (r0 *model.Enumeration, err1 error) {
	err1 = errUnsupported("GetEnumeration")
	return
}

func (unsupportedBackend) GetExportMappingByQualifiedName(_ string, _ string) (r0 *model.ExportMapping, err1 error) {
	err1 = errUnsupported("GetExportMappingByQualifiedName")
	return
}

func (unsupportedBackend) GetImportMappingByQualifiedName(_ string, _ string) (r0 *model.ImportMapping, err1 error) {
	err1 = errUnsupported("GetImportMappingByQualifiedName")
	return
}

func (unsupportedBackend) GetJsonStructureByQualifiedName(_ string, _ string) (r0 *types.JsonStructure, err1 error) {
	err1 = errUnsupported("GetJsonStructureByQualifiedName")
	return
}

func (unsupportedBackend) GetLayout(_ model.ID) (r0 *pages.Layout, err1 error) {
	err1 = errUnsupported("GetLayout")
	return
}

func (unsupportedBackend) GetMendixVersion() (r0 string, err1 error) {
	err1 = errUnsupported("GetMendixVersion")
	return
}

func (unsupportedBackend) GetMicroflow(_ model.ID) (r0 *microflows.Microflow, err1 error) {
	err1 = errUnsupported("GetMicroflow")
	return
}

func (unsupportedBackend) GetModule(_ model.ID) (r0 *model.Module, err1 error) {
	err1 = errUnsupported("GetModule")
	return
}

func (unsupportedBackend) GetModuleByName(_ string) (r0 *model.Module, err1 error) {
	err1 = errUnsupported("GetModuleByName")
	return
}

func (unsupportedBackend) GetModuleSecurity(_ model.ID) (r0 *security.ModuleSecurity, err1 error) {
	err1 = errUnsupported("GetModuleSecurity")
	return
}

func (unsupportedBackend) GetModuleSettings(_ model.ID) (r0 *types.ModuleSettings, err1 error) {
	err1 = errUnsupported("GetModuleSettings")
	return
}

func (unsupportedBackend) GetNanoflow(_ model.ID) (r0 *microflows.Nanoflow, err1 error) {
	err1 = errUnsupported("GetNanoflow")
	return
}

func (unsupportedBackend) GetNavigation() (r0 *types.NavigationDocument, err1 error) {
	err1 = errUnsupported("GetNavigation")
	return
}

func (unsupportedBackend) GetPage(_ model.ID) (r0 *pages.Page, err1 error) {
	err1 = errUnsupported("GetPage")
	return
}

func (unsupportedBackend) GetProjectRootID() (r0 string, err1 error) {
	err1 = errUnsupported("GetProjectRootID")
	return
}

func (unsupportedBackend) GetProjectSecurity() (r0 *security.ProjectSecurity, err1 error) {
	err1 = errUnsupported("GetProjectSecurity")
	return
}

func (unsupportedBackend) GetProjectSettings() (r0 *model.ProjectSettings, err1 error) {
	err1 = errUnsupported("GetProjectSettings")
	return
}

func (unsupportedBackend) GetRawMicroflowByName(_ string) (r0 []uint8, err1 error) {
	err1 = errUnsupported("GetRawMicroflowByName")
	return
}

func (unsupportedBackend) GetRawUnit(_ model.ID) (r0 map[string]any, err1 error) {
	err1 = errUnsupported("GetRawUnit")
	return
}

func (unsupportedBackend) GetRawUnitByName(_ string, _ string) (r0 *types.RawUnitInfo, err1 error) {
	err1 = errUnsupported("GetRawUnitByName")
	return
}

func (unsupportedBackend) GetRawUnitBytes(_ model.ID) (r0 []uint8, err1 error) {
	err1 = errUnsupported("GetRawUnitBytes")
	return
}

func (unsupportedBackend) GetScheduledEvent(_ model.ID) (r0 *model.ScheduledEvent, err1 error) {
	err1 = errUnsupported("GetScheduledEvent")
	return
}

func (unsupportedBackend) GetUnitTypes() (r0 map[string]int, err1 error) {
	err1 = errUnsupported("GetUnitTypes")
	return
}

func (unsupportedBackend) GetWorkflow(_ model.ID) (r0 *workflows.Workflow, err1 error) {
	err1 = errUnsupported("GetWorkflow")
	return
}

func (unsupportedBackend) InvalidateCache() {
	return
}

func (unsupportedBackend) IsConnected() (r0 bool) {
	return
}

func (unsupportedBackend) IsRule(_ string) (r0 bool, err1 error) {
	err1 = errUnsupported("IsRule")
	return
}

func (unsupportedBackend) ListAgentEditorAgents() (r0 []*agenteditor.Agent, err1 error) {
	err1 = errUnsupported("ListAgentEditorAgents")
	return
}

func (unsupportedBackend) ListAgentEditorConsumedMCPServices() (r0 []*agenteditor.ConsumedMCPService, err1 error) {
	err1 = errUnsupported("ListAgentEditorConsumedMCPServices")
	return
}

func (unsupportedBackend) ListAgentEditorKnowledgeBases() (r0 []*agenteditor.KnowledgeBase, err1 error) {
	err1 = errUnsupported("ListAgentEditorKnowledgeBases")
	return
}

func (unsupportedBackend) ListAgentEditorModels() (r0 []*agenteditor.Model, err1 error) {
	err1 = errUnsupported("ListAgentEditorModels")
	return
}

func (unsupportedBackend) ListAllUnitIDs() (r0 []string, err1 error) {
	err1 = errUnsupported("ListAllUnitIDs")
	return
}

func (unsupportedBackend) ListBuildingBlocks() (r0 []*pages.BuildingBlock, err1 error) {
	err1 = errUnsupported("ListBuildingBlocks")
	return
}

func (unsupportedBackend) ListBusinessEventServices() (r0 []*model.BusinessEventService, err1 error) {
	err1 = errUnsupported("ListBusinessEventServices")
	return
}

func (unsupportedBackend) ListConstants() (r0 []*model.Constant, err1 error) {
	err1 = errUnsupported("ListConstants")
	return
}

func (unsupportedBackend) ListConsumedODataServices() (r0 []*model.ConsumedODataService, err1 error) {
	err1 = errUnsupported("ListConsumedODataServices")
	return
}

func (unsupportedBackend) ListConsumedRestServices() (r0 []*model.ConsumedRestService, err1 error) {
	err1 = errUnsupported("ListConsumedRestServices")
	return
}

func (unsupportedBackend) ListDataTransformers() (r0 []*model.DataTransformer, err1 error) {
	err1 = errUnsupported("ListDataTransformers")
	return
}

func (unsupportedBackend) ListDatabaseConnections() (r0 []*model.DatabaseConnection, err1 error) {
	err1 = errUnsupported("ListDatabaseConnections")
	return
}

func (unsupportedBackend) ListDomainModels() (r0 []*domainmodel.DomainModel, err1 error) {
	err1 = errUnsupported("ListDomainModels")
	return
}

func (unsupportedBackend) ListEnumerations() (r0 []*model.Enumeration, err1 error) {
	err1 = errUnsupported("ListEnumerations")
	return
}

func (unsupportedBackend) ListExportMappings() (r0 []*model.ExportMapping, err1 error) {
	err1 = errUnsupported("ListExportMappings")
	return
}

func (unsupportedBackend) ListFolders() (r0 []*types.FolderInfo, err1 error) {
	err1 = errUnsupported("ListFolders")
	return
}

func (unsupportedBackend) ListImageCollections() (r0 []*types.ImageCollection, err1 error) {
	err1 = errUnsupported("ListImageCollections")
	return
}

func (unsupportedBackend) ListImportMappings() (r0 []*model.ImportMapping, err1 error) {
	err1 = errUnsupported("ListImportMappings")
	return
}

func (unsupportedBackend) ListJavaActions() (r0 []*types.JavaAction, err1 error) {
	err1 = errUnsupported("ListJavaActions")
	return
}

func (unsupportedBackend) ListJavaActionsFull() (r0 []*javaactions.JavaAction, err1 error) {
	err1 = errUnsupported("ListJavaActionsFull")
	return
}

func (unsupportedBackend) ListJavaScriptActions() (r0 []*types.JavaScriptAction, err1 error) {
	err1 = errUnsupported("ListJavaScriptActions")
	return
}

func (unsupportedBackend) ListJsonStructures() (r0 []*types.JsonStructure, err1 error) {
	err1 = errUnsupported("ListJsonStructures")
	return
}

func (unsupportedBackend) ListLayouts() (r0 []*pages.Layout, err1 error) {
	err1 = errUnsupported("ListLayouts")
	return
}

func (unsupportedBackend) ListMicroflows() (r0 []*microflows.Microflow, err1 error) {
	err1 = errUnsupported("ListMicroflows")
	return
}

func (unsupportedBackend) ListModuleSecurity() (r0 []*security.ModuleSecurity, err1 error) {
	err1 = errUnsupported("ListModuleSecurity")
	return
}

func (unsupportedBackend) ListModuleSettings() (r0 []*types.ModuleSettings, err1 error) {
	err1 = errUnsupported("ListModuleSettings")
	return
}

func (unsupportedBackend) ListModules() (r0 []*model.Module, err1 error) {
	err1 = errUnsupported("ListModules")
	return
}

func (unsupportedBackend) ListNanoflows() (r0 []*microflows.Nanoflow, err1 error) {
	err1 = errUnsupported("ListNanoflows")
	return
}

func (unsupportedBackend) ListNavigationDocuments() (r0 []*types.NavigationDocument, err1 error) {
	err1 = errUnsupported("ListNavigationDocuments")
	return
}

func (unsupportedBackend) ListPageTemplates() (r0 []*pages.PageTemplate, err1 error) {
	err1 = errUnsupported("ListPageTemplates")
	return
}

func (unsupportedBackend) ListPages() (r0 []*pages.Page, err1 error) {
	err1 = errUnsupported("ListPages")
	return
}

func (unsupportedBackend) ListPublishedODataServices() (r0 []*model.PublishedODataService, err1 error) {
	err1 = errUnsupported("ListPublishedODataServices")
	return
}

func (unsupportedBackend) ListPublishedRestServices() (r0 []*model.PublishedRestService, err1 error) {
	err1 = errUnsupported("ListPublishedRestServices")
	return
}

func (unsupportedBackend) ListRawUnits(_ string) (r0 []*types.RawUnitInfo, err1 error) {
	err1 = errUnsupported("ListRawUnits")
	return
}

func (unsupportedBackend) ListRawUnitsByType(_ string) (r0 []*types.RawUnit, err1 error) {
	err1 = errUnsupported("ListRawUnitsByType")
	return
}

func (unsupportedBackend) ListScheduledEvents() (r0 []*model.ScheduledEvent, err1 error) {
	err1 = errUnsupported("ListScheduledEvents")
	return
}

func (unsupportedBackend) ListSnippets() (r0 []*pages.Snippet, err1 error) {
	err1 = errUnsupported("ListSnippets")
	return
}

func (unsupportedBackend) ListUnits() (r0 []*types.UnitInfo, err1 error) {
	err1 = errUnsupported("ListUnits")
	return
}

func (unsupportedBackend) ListWorkflows() (r0 []*workflows.Workflow, err1 error) {
	err1 = errUnsupported("ListWorkflows")
	return
}

func (unsupportedBackend) LoadWidgetTemplate(_ string, _ string) (r0 backend.WidgetObjectBuilder, err1 error) {
	err1 = errUnsupported("LoadWidgetTemplate")
	return
}

func (unsupportedBackend) MoveConstant(_ *model.Constant) (err0 error) {
	err0 = errUnsupported("MoveConstant")
	return
}

func (unsupportedBackend) MoveDatabaseConnection(_ *model.DatabaseConnection) (err0 error) {
	err0 = errUnsupported("MoveDatabaseConnection")
	return
}

func (unsupportedBackend) MoveEntity(_ *domainmodel.Entity, _ model.ID, _ model.ID, _ string, _ string) (r0 []string, err1 error) {
	err1 = errUnsupported("MoveEntity")
	return
}

func (unsupportedBackend) MoveEnumeration(_ *model.Enumeration) (err0 error) {
	err0 = errUnsupported("MoveEnumeration")
	return
}

func (unsupportedBackend) MoveExportMapping(_ *model.ExportMapping) (err0 error) {
	err0 = errUnsupported("MoveExportMapping")
	return
}

func (unsupportedBackend) MoveFolder(_ model.ID, _ model.ID) (err0 error) {
	err0 = errUnsupported("MoveFolder")
	return
}

func (unsupportedBackend) MoveImportMapping(_ *model.ImportMapping) (err0 error) {
	err0 = errUnsupported("MoveImportMapping")
	return
}

func (unsupportedBackend) MoveMicroflow(_ *microflows.Microflow) (err0 error) {
	err0 = errUnsupported("MoveMicroflow")
	return
}

func (unsupportedBackend) MoveNanoflow(_ *microflows.Nanoflow) (err0 error) {
	err0 = errUnsupported("MoveNanoflow")
	return
}

func (unsupportedBackend) MovePage(_ *pages.Page) (err0 error) {
	err0 = errUnsupported("MovePage")
	return
}

func (unsupportedBackend) MoveSnippet(_ *pages.Snippet) (err0 error) {
	err0 = errUnsupported("MoveSnippet")
	return
}

func (unsupportedBackend) MoveViewEntitySourceDocument(_ string, _ model.ID, _ string) (err0 error) {
	err0 = errUnsupported("MoveViewEntitySourceDocument")
	return
}

func (unsupportedBackend) OpenPageForMutation(_ model.ID) (r0 backend.PageMutator, err1 error) {
	err1 = errUnsupported("OpenPageForMutation")
	return
}

func (unsupportedBackend) OpenWorkflowForMutation(_ model.ID) (r0 backend.WorkflowMutator, err1 error) {
	err1 = errUnsupported("OpenWorkflowForMutation")
	return
}

func (unsupportedBackend) ParseMicroflowBSON(_ []uint8, _ model.ID, _ model.ID) (r0 *microflows.Microflow, err1 error) {
	err1 = errUnsupported("ParseMicroflowBSON")
	return
}

func (unsupportedBackend) ParseMicroflowFromRaw(_ map[string]any, _ model.ID, _ model.ID) (r0 *microflows.Microflow) {
	return
}

func (unsupportedBackend) Path() (r0 string) {
	return
}

func (unsupportedBackend) ProjectVersion() (r0 *types.ProjectVersion) {
	return
}

func (unsupportedBackend) ReadJavaActionByName(_ string) (r0 *javaactions.JavaAction, err1 error) {
	err1 = errUnsupported("ReadJavaActionByName")
	return
}

func (unsupportedBackend) ReadJavaScriptActionByName(_ string) (r0 *types.JavaScriptAction, err1 error) {
	err1 = errUnsupported("ReadJavaScriptActionByName")
	return
}

func (unsupportedBackend) ReadJavaSourceFile(_ string, _ string) (r0 string, err1 error) {
	err1 = errUnsupported("ReadJavaSourceFile")
	return
}

func (unsupportedBackend) ReconcileMemberAccesses(_ model.ID, _ string) (r0 int, err1 error) {
	err1 = errUnsupported("ReconcileMemberAccesses")
	return
}

func (unsupportedBackend) RemoveDemoUser(_ model.ID, _ string) (err0 error) {
	err0 = errUnsupported("RemoveDemoUser")
	return
}

func (unsupportedBackend) RemoveEntityAccessRule(_ model.ID, _ string, _ []string) (r0 int, err1 error) {
	err1 = errUnsupported("RemoveEntityAccessRule")
	return
}

func (unsupportedBackend) RemoveFromAllowedRoles(_ model.ID, _ string) (r0 bool, err1 error) {
	err1 = errUnsupported("RemoveFromAllowedRoles")
	return
}

func (unsupportedBackend) RemoveModuleRole(_ model.ID, _ string) (err0 error) {
	err0 = errUnsupported("RemoveModuleRole")
	return
}

func (unsupportedBackend) RemoveModuleRoleFromAllUserRoles(_ model.ID, _ string) (r0 int, err1 error) {
	err1 = errUnsupported("RemoveModuleRoleFromAllUserRoles")
	return
}

func (unsupportedBackend) RemoveRoleFromAllEntities(_ model.ID, _ string) (r0 int, err1 error) {
	err1 = errUnsupported("RemoveRoleFromAllEntities")
	return
}

func (unsupportedBackend) RemoveUserRole(_ model.ID, _ string) (err0 error) {
	err0 = errUnsupported("RemoveUserRole")
	return
}

func (unsupportedBackend) RenameDocumentByName(_ string, _ string, _ string) (err0 error) {
	err0 = errUnsupported("RenameDocumentByName")
	return
}

func (unsupportedBackend) RenameJavaScriptSourceFile(_ string, _ string, _ string) (err0 error) {
	err0 = errUnsupported("RenameJavaScriptSourceFile")
	return
}

func (unsupportedBackend) RenameJavaSourceFile(_ string, _ string, _ string) (err0 error) {
	err0 = errUnsupported("RenameJavaSourceFile")
	return
}

func (unsupportedBackend) RenameReferences(_ string, _ string, _ bool) (r0 []types.RenameHit, err1 error) {
	err1 = errUnsupported("RenameReferences")
	return
}

func (unsupportedBackend) RevokeEntityMemberAccess(_ model.ID, _ string, _ []string, _ types.EntityAccessRevocation) (r0 int, err1 error) {
	err1 = errUnsupported("RevokeEntityMemberAccess")
	return
}

func (unsupportedBackend) SerializeClientAction(_ pages.ClientAction) (r0 any, err1 error) {
	err1 = errUnsupported("SerializeClientAction")
	return
}

func (unsupportedBackend) SerializeDataSource(_ pages.DataSource) (r0 any, err1 error) {
	err1 = errUnsupported("SerializeDataSource")
	return
}

func (unsupportedBackend) SerializeDataSourceToOpaque(_ pages.DataSource) (r0 any) {
	return
}

func (unsupportedBackend) SerializeWidget(_ pages.Widget) (r0 any, err1 error) {
	err1 = errUnsupported("SerializeWidget")
	return
}

func (unsupportedBackend) SerializeWidgetToOpaque(_ pages.Widget) (r0 any) {
	return
}

func (unsupportedBackend) SerializeWorkflowActivity(_ workflows.WorkflowActivity) (r0 any, err1 error) {
	err1 = errUnsupported("SerializeWorkflowActivity")
	return
}

func (unsupportedBackend) SetProjectDemoUsersEnabled(_ model.ID, _ bool) (err0 error) {
	err0 = errUnsupported("SetProjectDemoUsersEnabled")
	return
}

func (unsupportedBackend) SetProjectSecurityLevel(_ model.ID, _ string) (err0 error) {
	err0 = errUnsupported("SetProjectSecurityLevel")
	return
}

func (unsupportedBackend) UpdateAgentEditorAgent(_ *agenteditor.Agent) (err0 error) {
	err0 = errUnsupported("UpdateAgentEditorAgent")
	return
}

func (unsupportedBackend) UpdateAgentEditorConsumedMCPService(_ *agenteditor.ConsumedMCPService) (err0 error) {
	err0 = errUnsupported("UpdateAgentEditorConsumedMCPService")
	return
}

func (unsupportedBackend) UpdateAgentEditorKnowledgeBase(_ *agenteditor.KnowledgeBase) (err0 error) {
	err0 = errUnsupported("UpdateAgentEditorKnowledgeBase")
	return
}

func (unsupportedBackend) UpdateAgentEditorModel(_ *agenteditor.Model) (err0 error) {
	err0 = errUnsupported("UpdateAgentEditorModel")
	return
}

func (unsupportedBackend) UpdateAllowedRoles(_ model.ID, _ []string) (err0 error) {
	err0 = errUnsupported("UpdateAllowedRoles")
	return
}

func (unsupportedBackend) UpdateAttribute(_ model.ID, _ model.ID, _ *domainmodel.Attribute) (err0 error) {
	err0 = errUnsupported("UpdateAttribute")
	return
}

func (unsupportedBackend) UpdateBusinessEventService(_ *model.BusinessEventService) (err0 error) {
	err0 = errUnsupported("UpdateBusinessEventService")
	return
}

func (unsupportedBackend) UpdateConstant(_ *model.Constant) (err0 error) {
	err0 = errUnsupported("UpdateConstant")
	return
}

func (unsupportedBackend) UpdateConsumedODataService(_ *model.ConsumedODataService) (err0 error) {
	err0 = errUnsupported("UpdateConsumedODataService")
	return
}

func (unsupportedBackend) UpdateConsumedRestService(_ *model.ConsumedRestService) (err0 error) {
	err0 = errUnsupported("UpdateConsumedRestService")
	return
}

func (unsupportedBackend) UpdateDataTransformer(_ *model.DataTransformer) (err0 error) {
	err0 = errUnsupported("UpdateDataTransformer")
	return
}

func (unsupportedBackend) UpdateDatabaseConnection(_ *model.DatabaseConnection) (err0 error) {
	err0 = errUnsupported("UpdateDatabaseConnection")
	return
}

func (unsupportedBackend) UpdateDomainModel(_ *domainmodel.DomainModel) (err0 error) {
	err0 = errUnsupported("UpdateDomainModel")
	return
}

func (unsupportedBackend) UpdateEntity(_ model.ID, _ *domainmodel.Entity) (err0 error) {
	err0 = errUnsupported("UpdateEntity")
	return
}

func (unsupportedBackend) UpdateEnumeration(_ *model.Enumeration) (err0 error) {
	err0 = errUnsupported("UpdateEnumeration")
	return
}

func (unsupportedBackend) UpdateEnumerationRefsInAllDomainModels(_ string, _ string) (err0 error) {
	err0 = errUnsupported("UpdateEnumerationRefsInAllDomainModels")
	return
}

func (unsupportedBackend) UpdateExportMapping(_ *model.ExportMapping) (err0 error) {
	err0 = errUnsupported("UpdateExportMapping")
	return
}

func (unsupportedBackend) UpdateImageCollection(_ *types.ImageCollection) (err0 error) {
	err0 = errUnsupported("UpdateImageCollection")
	return
}

func (unsupportedBackend) UpdateImportMapping(_ *model.ImportMapping) (err0 error) {
	err0 = errUnsupported("UpdateImportMapping")
	return
}

func (unsupportedBackend) UpdateJavaAction(_ *javaactions.JavaAction) (err0 error) {
	err0 = errUnsupported("UpdateJavaAction")
	return
}

func (unsupportedBackend) UpdateJavaScriptAction(_ *types.JavaScriptAction) (err0 error) {
	err0 = errUnsupported("UpdateJavaScriptAction")
	return
}

func (unsupportedBackend) UpdateJsonStructure(_ *types.JsonStructure) (err0 error) {
	err0 = errUnsupported("UpdateJsonStructure")
	return
}

func (unsupportedBackend) UpdateLayout(_ *pages.Layout) (err0 error) {
	err0 = errUnsupported("UpdateLayout")
	return
}

func (unsupportedBackend) UpdateMicroflow(_ *microflows.Microflow) (err0 error) {
	err0 = errUnsupported("UpdateMicroflow")
	return
}

func (unsupportedBackend) UpdateModule(_ *model.Module) (err0 error) {
	err0 = errUnsupported("UpdateModule")
	return
}

func (unsupportedBackend) UpdateModuleSettings(_ *types.ModuleSettings) (err0 error) {
	err0 = errUnsupported("UpdateModuleSettings")
	return
}

func (unsupportedBackend) UpdateNanoflow(_ *microflows.Nanoflow) (err0 error) {
	err0 = errUnsupported("UpdateNanoflow")
	return
}

func (unsupportedBackend) UpdateNavigationProfile(_ model.ID, _ string, _ types.NavigationProfileSpec) (err0 error) {
	err0 = errUnsupported("UpdateNavigationProfile")
	return
}

func (unsupportedBackend) UpdateOqlQueriesForMovedEntity(_ string, _ string) (r0 int, err1 error) {
	err1 = errUnsupported("UpdateOqlQueriesForMovedEntity")
	return
}

func (unsupportedBackend) UpdatePage(_ *pages.Page) (err0 error) {
	err0 = errUnsupported("UpdatePage")
	return
}

func (unsupportedBackend) UpdateProjectSettings(_ *model.ProjectSettings) (err0 error) {
	err0 = errUnsupported("UpdateProjectSettings")
	return
}

func (unsupportedBackend) UpdatePublishedODataService(_ *model.PublishedODataService) (err0 error) {
	err0 = errUnsupported("UpdatePublishedODataService")
	return
}

func (unsupportedBackend) UpdatePublishedRestService(_ *model.PublishedRestService) (err0 error) {
	err0 = errUnsupported("UpdatePublishedRestService")
	return
}

func (unsupportedBackend) UpdatePublishedRestServiceRoles(_ model.ID, _ []string) (err0 error) {
	err0 = errUnsupported("UpdatePublishedRestServiceRoles")
	return
}

func (unsupportedBackend) UpdateQualifiedNameInAllUnits(_ string, _ string) (r0 int, err1 error) {
	err1 = errUnsupported("UpdateQualifiedNameInAllUnits")
	return
}

func (unsupportedBackend) UpdateRawUnit(_ string, _ []uint8) (err0 error) {
	err0 = errUnsupported("UpdateRawUnit")
	return
}

func (unsupportedBackend) UpdateSnippet(_ *pages.Snippet) (err0 error) {
	err0 = errUnsupported("UpdateSnippet")
	return
}

func (unsupportedBackend) UpdateWorkflow(_ *workflows.Workflow) (err0 error) {
	err0 = errUnsupported("UpdateWorkflow")
	return
}

func (unsupportedBackend) Version() (r0 types.MPRVersion) {
	return
}

func (unsupportedBackend) WriteJavaScriptSourceFile(_ string, _ string, _ string, _ []*types.JavaActionParameter, _ types.CodeActionReturnType) (err0 error) {
	err0 = errUnsupported("WriteJavaScriptSourceFile")
	return
}

func (unsupportedBackend) WriteJavaSourceFile(_ string, _ string, _ string, _ []*types.JavaActionParameter, _ types.CodeActionReturnType, _ []string, _ string) (err0 error) {
	err0 = errUnsupported("WriteJavaSourceFile")
	return
}
