//go:build ignore

// gen_unimplemented generates unimplemented_gen.go: a type that satisfies the
// whole backend.FullBackend surface by erroring on every method. The modelsdk
// Backend embeds it so any method it does not (yet) override fails loudly with
// "modelsdk engine: X not implemented" instead of silently no-op'ing (which is
// how the previously-embedded mock behaved — see ADR-0005 "guard, don't drop").
//
// Run via: go run ./mdl/backend/modelsdk/gen_unimplemented.go
package main

import (
	"fmt"
	"go/format"
	"os"
	"reflect"
	"strings"

	"github.com/JordtenBulte-OLC/mxcli/mdl/backend"
)

// imports the generated file needs — the union of packages whose types appear
// in any FullBackend method signature (kept in sync with mdl/backend/mock).
var imports = []string{
	"github.com/JordtenBulte-OLC/mxcli/mdl/backend",
	"github.com/JordtenBulte-OLC/mxcli/mdl/types",
	"github.com/JordtenBulte-OLC/mxcli/model",
	"github.com/JordtenBulte-OLC/mxcli/sdk/agenteditor",
	"github.com/JordtenBulte-OLC/mxcli/sdk/domainmodel",
	"github.com/JordtenBulte-OLC/mxcli/sdk/javaactions",
	"github.com/JordtenBulte-OLC/mxcli/sdk/microflows",
	"github.com/JordtenBulte-OLC/mxcli/sdk/pages",
	"github.com/JordtenBulte-OLC/mxcli/sdk/security",
	"github.com/JordtenBulte-OLC/mxcli/sdk/workflows",
}

func main() {
	t := reflect.TypeOf((*backend.FullBackend)(nil)).Elem()

	var b strings.Builder
	b.WriteString("// Code generated by gen_unimplemented.go. DO NOT EDIT.\n")
	b.WriteString("// Regenerate with: go run ./mdl/backend/modelsdk/gen_unimplemented.go\n\n")
	b.WriteString("package modelsdkbackend\n\n")
	b.WriteString("import (\n")
	for _, p := range imports {
		fmt.Fprintf(&b, "\t%q\n", p)
	}
	b.WriteString(")\n\n")
	b.WriteString("// unimplemented satisfies backend.FullBackend by erroring on every method.\n")
	b.WriteString("// Backend embeds it; its own overrides shadow the methods it implements,\n")
	b.WriteString("// so anything NOT overridden fails loudly rather than silently dropping data.\n")
	b.WriteString("type unimplemented struct{}\n\n")

	for i := 0; i < t.NumMethod(); i++ {
		m := t.Method(i)
		ft := m.Type

		var params []string
		for j := 0; j < ft.NumIn(); j++ {
			pt := ft.In(j)
			s := pt.String()
			if ft.IsVariadic() && j == ft.NumIn()-1 {
				s = "..." + pt.Elem().String()
			}
			params = append(params, "_ "+s)
		}

		var results []string
		errIdx := -1
		for j := 0; j < ft.NumOut(); j++ {
			rs := ft.Out(j).String()
			results = append(results, rs)
			if rs == "error" {
				errIdx = j
			}
		}

		sig := fmt.Sprintf("func (unimplemented) %s(%s)", m.Name, strings.Join(params, ", "))
		switch len(results) {
		case 0:
			// No way to signal failure; a no-result method on the backend would be
			// a pure command with no error channel. None exist today, but emit a
			// panic so a future one can't silently no-op.
			fmt.Fprintf(&b, "%s {\n\tpanic(errUnimplemented(%q))\n}\n\n", sig, m.Name)
			continue
		case 1:
			sig += " " + results[0]
		default:
			sig += " (" + strings.Join(results, ", ") + ")"
		}
		b.WriteString(sig + " {\n")

		var retvals []string
		for j, rs := range results {
			if j == errIdx {
				retvals = append(retvals, fmt.Sprintf("errUnimplemented(%q)", m.Name))
				continue
			}
			vn := fmt.Sprintf("r%d", j)
			fmt.Fprintf(&b, "\tvar %s %s\n", vn, rs)
			retvals = append(retvals, vn)
		}
		fmt.Fprintf(&b, "\treturn %s\n}\n\n", strings.Join(retvals, ", "))
	}

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		fmt.Fprintln(os.Stderr, b.String())
		panic(err)
	}
	if err := os.WriteFile("mdl/backend/modelsdk/unimplemented_gen.go", src, 0o644); err != nil {
		panic(err)
	}
	fmt.Printf("wrote unimplemented_gen.go (%d methods)\n", t.NumMethod())
}
