// Code generated by gen_unimplemented.go. DO NOT EDIT.
// Regenerate with: go run ./mdl/backend/modelsdk/gen_unimplemented.go

package modelsdkbackend

import (
	"github.com/JordtenBulte-OLC/mxcli/mdl/backend"
	"github.com/JordtenBulte-OLC/mxcli/mdl/types"
	"github.com/JordtenBulte-OLC/mxcli/model"
	"github.com/JordtenBulte-OLC/mxcli/sdk/agenteditor"
	"github.com/JordtenBulte-OLC/mxcli/sdk/domainmodel"
	"github.com/JordtenBulte-OLC/mxcli/sdk/javaactions"
	"github.com/JordtenBulte-OLC/mxcli/sdk/microflows"
	"github.com/JordtenBulte-OLC/mxcli/sdk/pages"
	"github.com/JordtenBulte-OLC/mxcli/sdk/security"
	"github.com/JordtenBulte-OLC/mxcli/sdk/workflows"
)

// unimplemented satisfies backend.FullBackend by erroring on every method.
// Backend embeds it; its own overrides shadow the methods it implements,
// so anything NOT overridden fails loudly rather than silently dropping data.
type unimplemented struct{}

func (unimplemented) AddAttribute(_ model.ID, _ model.ID, _ *domainmodel.Attribute) error {
	return errUnimplemented("AddAttribute")
}

func (unimplemented) AddDemoUser(_ model.ID, _ string, _ string, _ string, _ []string) error {
	return errUnimplemented("AddDemoUser")
}

func (unimplemented) AddEntityAccessRule(_ backend.EntityAccessRuleParams) error {
	return errUnimplemented("AddEntityAccessRule")
}

func (unimplemented) AddModuleRole(_ model.ID, _ string, _ string) error {
	return errUnimplemented("AddModuleRole")
}

func (unimplemented) AddUserRole(_ model.ID, _ string, _ []string, _ bool) error {
	return errUnimplemented("AddUserRole")
}

func (unimplemented) AlterUserRoleModuleRoles(_ model.ID, _ string, _ bool, _ []string) error {
	return errUnimplemented("AlterUserRoleModuleRoles")
}

func (unimplemented) BuildCreateAttributeObject(_ string, _ string, _ string, _ string) (interface{}, error) {
	var r0 interface{}
	return r0, errUnimplemented("BuildCreateAttributeObject")
}

func (unimplemented) BuildFilterWidget(_ backend.FilterWidgetSpec, _ string) (pages.Widget, error) {
	var r0 pages.Widget
	return r0, errUnimplemented("BuildFilterWidget")
}

func (unimplemented) Commit() error {
	return errUnimplemented("Commit")
}

func (unimplemented) Connect(_ string) error {
	return errUnimplemented("Connect")
}

func (unimplemented) ContentsDir() string {
	var r0 string
	return r0
}

func (unimplemented) CreateAgentEditorAgent(_ *agenteditor.Agent) error {
	return errUnimplemented("CreateAgentEditorAgent")
}

func (unimplemented) CreateAgentEditorConsumedMCPService(_ *agenteditor.ConsumedMCPService) error {
	return errUnimplemented("CreateAgentEditorConsumedMCPService")
}

func (unimplemented) CreateAgentEditorKnowledgeBase(_ *agenteditor.KnowledgeBase) error {
	return errUnimplemented("CreateAgentEditorKnowledgeBase")
}

func (unimplemented) CreateAgentEditorModel(_ *agenteditor.Model) error {
	return errUnimplemented("CreateAgentEditorModel")
}

func (unimplemented) CreateAssociation(_ model.ID, _ *domainmodel.Association) error {
	return errUnimplemented("CreateAssociation")
}

func (unimplemented) CreateBusinessEventService(_ *model.BusinessEventService) error {
	return errUnimplemented("CreateBusinessEventService")
}

func (unimplemented) CreateConstant(_ *model.Constant) error {
	return errUnimplemented("CreateConstant")
}

func (unimplemented) CreateConsumedODataService(_ *model.ConsumedODataService) error {
	return errUnimplemented("CreateConsumedODataService")
}

func (unimplemented) CreateConsumedRestService(_ *model.ConsumedRestService) error {
	return errUnimplemented("CreateConsumedRestService")
}

func (unimplemented) CreateCrossAssociation(_ model.ID, _ *domainmodel.CrossModuleAssociation) error {
	return errUnimplemented("CreateCrossAssociation")
}

func (unimplemented) CreateDataTransformer(_ *model.DataTransformer) error {
	return errUnimplemented("CreateDataTransformer")
}

func (unimplemented) CreateDatabaseConnection(_ *model.DatabaseConnection) error {
	return errUnimplemented("CreateDatabaseConnection")
}

func (unimplemented) CreateEntity(_ model.ID, _ *domainmodel.Entity) error {
	return errUnimplemented("CreateEntity")
}

func (unimplemented) CreateEnumeration(_ *model.Enumeration) error {
	return errUnimplemented("CreateEnumeration")
}

func (unimplemented) CreateExportMapping(_ *model.ExportMapping) error {
	return errUnimplemented("CreateExportMapping")
}

func (unimplemented) CreateFolder(_ *model.Folder) error {
	return errUnimplemented("CreateFolder")
}

func (unimplemented) CreateImageCollection(_ *types.ImageCollection) error {
	return errUnimplemented("CreateImageCollection")
}

func (unimplemented) CreateImportMapping(_ *model.ImportMapping) error {
	return errUnimplemented("CreateImportMapping")
}

func (unimplemented) CreateJavaAction(_ *javaactions.JavaAction) error {
	return errUnimplemented("CreateJavaAction")
}

func (unimplemented) CreateJavaScriptAction(_ *types.JavaScriptAction) error {
	return errUnimplemented("CreateJavaScriptAction")
}

func (unimplemented) CreateJsonStructure(_ *types.JsonStructure) error {
	return errUnimplemented("CreateJsonStructure")
}

func (unimplemented) CreateLayout(_ *pages.Layout) error {
	return errUnimplemented("CreateLayout")
}

func (unimplemented) CreateMicroflow(_ *microflows.Microflow) error {
	return errUnimplemented("CreateMicroflow")
}

func (unimplemented) CreateModule(_ *model.Module) error {
	return errUnimplemented("CreateModule")
}

func (unimplemented) CreateNanoflow(_ *microflows.Nanoflow) error {
	return errUnimplemented("CreateNanoflow")
}

func (unimplemented) CreatePage(_ *pages.Page) error {
	return errUnimplemented("CreatePage")
}

func (unimplemented) CreatePublishedODataService(_ *model.PublishedODataService) error {
	return errUnimplemented("CreatePublishedODataService")
}

func (unimplemented) CreatePublishedRestService(_ *model.PublishedRestService) error {
	return errUnimplemented("CreatePublishedRestService")
}

func (unimplemented) CreateSnippet(_ *pages.Snippet) error {
	return errUnimplemented("CreateSnippet")
}

func (unimplemented) CreateViewEntitySourceDocument(_ model.ID, _ string, _ string, _ string, _ string) (model.ID, error) {
	var r0 model.ID
	return r0, errUnimplemented("CreateViewEntitySourceDocument")
}

func (unimplemented) CreateWorkflow(_ *workflows.Workflow) error {
	return errUnimplemented("CreateWorkflow")
}

func (unimplemented) DeleteAgentEditorAgent(_ string) error {
	return errUnimplemented("DeleteAgentEditorAgent")
}

func (unimplemented) DeleteAgentEditorConsumedMCPService(_ string) error {
	return errUnimplemented("DeleteAgentEditorConsumedMCPService")
}

func (unimplemented) DeleteAgentEditorKnowledgeBase(_ string) error {
	return errUnimplemented("DeleteAgentEditorKnowledgeBase")
}

func (unimplemented) DeleteAgentEditorModel(_ string) error {
	return errUnimplemented("DeleteAgentEditorModel")
}

func (unimplemented) DeleteAssociation(_ model.ID, _ model.ID) error {
	return errUnimplemented("DeleteAssociation")
}

func (unimplemented) DeleteAttribute(_ model.ID, _ model.ID, _ model.ID) error {
	return errUnimplemented("DeleteAttribute")
}

func (unimplemented) DeleteBusinessEventService(_ model.ID) error {
	return errUnimplemented("DeleteBusinessEventService")
}

func (unimplemented) DeleteConstant(_ model.ID) error {
	return errUnimplemented("DeleteConstant")
}

func (unimplemented) DeleteConsumedODataService(_ model.ID) error {
	return errUnimplemented("DeleteConsumedODataService")
}

func (unimplemented) DeleteConsumedRestService(_ model.ID) error {
	return errUnimplemented("DeleteConsumedRestService")
}

func (unimplemented) DeleteCrossAssociation(_ model.ID, _ model.ID) error {
	return errUnimplemented("DeleteCrossAssociation")
}

func (unimplemented) DeleteDataTransformer(_ model.ID) error {
	return errUnimplemented("DeleteDataTransformer")
}

func (unimplemented) DeleteDatabaseConnection(_ model.ID) error {
	return errUnimplemented("DeleteDatabaseConnection")
}

func (unimplemented) DeleteEntity(_ model.ID, _ model.ID) error {
	return errUnimplemented("DeleteEntity")
}

func (unimplemented) DeleteEnumeration(_ model.ID) error {
	return errUnimplemented("DeleteEnumeration")
}

func (unimplemented) DeleteExportMapping(_ model.ID) error {
	return errUnimplemented("DeleteExportMapping")
}

func (unimplemented) DeleteFolder(_ model.ID) error {
	return errUnimplemented("DeleteFolder")
}

func (unimplemented) DeleteImageCollection(_ string) error {
	return errUnimplemented("DeleteImageCollection")
}

func (unimplemented) DeleteImportMapping(_ model.ID) error {
	return errUnimplemented("DeleteImportMapping")
}

func (unimplemented) DeleteJavaAction(_ model.ID) error {
	return errUnimplemented("DeleteJavaAction")
}

func (unimplemented) DeleteJavaScriptAction(_ model.ID) error {
	return errUnimplemented("DeleteJavaScriptAction")
}

func (unimplemented) DeleteJavaScriptSourceFile(_ string, _ string) error {
	return errUnimplemented("DeleteJavaScriptSourceFile")
}

func (unimplemented) DeleteJavaSourceFile(_ string, _ string) error {
	return errUnimplemented("DeleteJavaSourceFile")
}

func (unimplemented) DeleteJsonStructure(_ string) error {
	return errUnimplemented("DeleteJsonStructure")
}

func (unimplemented) DeleteLayout(_ model.ID) error {
	return errUnimplemented("DeleteLayout")
}

func (unimplemented) DeleteMicroflow(_ model.ID) error {
	return errUnimplemented("DeleteMicroflow")
}

func (unimplemented) DeleteModule(_ model.ID) error {
	return errUnimplemented("DeleteModule")
}

func (unimplemented) DeleteModuleWithCleanup(_ model.ID, _ string) error {
	return errUnimplemented("DeleteModuleWithCleanup")
}

func (unimplemented) DeleteNanoflow(_ model.ID) error {
	return errUnimplemented("DeleteNanoflow")
}

func (unimplemented) DeletePage(_ model.ID) error {
	return errUnimplemented("DeletePage")
}

func (unimplemented) DeletePublishedODataService(_ model.ID) error {
	return errUnimplemented("DeletePublishedODataService")
}

func (unimplemented) DeletePublishedRestService(_ model.ID) error {
	return errUnimplemented("DeletePublishedRestService")
}

func (unimplemented) DeleteSnippet(_ model.ID) error {
	return errUnimplemented("DeleteSnippet")
}

func (unimplemented) DeleteViewEntitySourceDocument(_ model.ID) error {
	return errUnimplemented("DeleteViewEntitySourceDocument")
}

func (unimplemented) DeleteViewEntitySourceDocumentByName(_ string, _ string) error {
	return errUnimplemented("DeleteViewEntitySourceDocumentByName")
}

func (unimplemented) DeleteWorkflow(_ model.ID) error {
	return errUnimplemented("DeleteWorkflow")
}

func (unimplemented) Disconnect() error {
	return errUnimplemented("Disconnect")
}

func (unimplemented) ExportJSON() ([]uint8, error) {
	var r0 []uint8
	return r0, errUnimplemented("ExportJSON")
}

func (unimplemented) FindAllCustomWidgetTypes(_ string) ([]*types.RawCustomWidgetType, error) {
	var r0 []*types.RawCustomWidgetType
	return r0, errUnimplemented("FindAllCustomWidgetTypes")
}

func (unimplemented) FindAllViewEntitySourceDocumentIDs(_ string, _ string) ([]model.ID, error) {
	var r0 []model.ID
	return r0, errUnimplemented("FindAllViewEntitySourceDocumentIDs")
}

func (unimplemented) FindCustomWidgetType(_ string) (*types.RawCustomWidgetType, error) {
	var r0 *types.RawCustomWidgetType
	return r0, errUnimplemented("FindCustomWidgetType")
}

func (unimplemented) FindViewEntitySourceDocumentID(_ string, _ string) (model.ID, error) {
	var r0 model.ID
	return r0, errUnimplemented("FindViewEntitySourceDocumentID")
}

func (unimplemented) GetConstant(_ model.ID) (*model.Constant, error) {
	var r0 *model.Constant
	return r0, errUnimplemented("GetConstant")
}

func (unimplemented) GetDomainModel(_ model.ID) (*domainmodel.DomainModel, error) {
	var r0 *domainmodel.DomainModel
	return r0, errUnimplemented("GetDomainModel")
}

func (unimplemented) GetDomainModelByID(_ model.ID) (*domainmodel.DomainModel, error) {
	var r0 *domainmodel.DomainModel
	return r0, errUnimplemented("GetDomainModelByID")
}

func (unimplemented) GetEnumeration(_ model.ID) (*model.Enumeration, error) {
	var r0 *model.Enumeration
	return r0, errUnimplemented("GetEnumeration")
}

func (unimplemented) GetExportMappingByQualifiedName(_ string, _ string) (*model.ExportMapping, error) {
	var r0 *model.ExportMapping
	return r0, errUnimplemented("GetExportMappingByQualifiedName")
}

func (unimplemented) GetImportMappingByQualifiedName(_ string, _ string) (*model.ImportMapping, error) {
	var r0 *model.ImportMapping
	return r0, errUnimplemented("GetImportMappingByQualifiedName")
}

func (unimplemented) GetJsonStructureByQualifiedName(_ string, _ string) (*types.JsonStructure, error) {
	var r0 *types.JsonStructure
	return r0, errUnimplemented("GetJsonStructureByQualifiedName")
}

func (unimplemented) GetLayout(_ model.ID) (*pages.Layout, error) {
	var r0 *pages.Layout
	return r0, errUnimplemented("GetLayout")
}

func (unimplemented) GetMendixVersion() (string, error) {
	var r0 string
	return r0, errUnimplemented("GetMendixVersion")
}

func (unimplemented) GetMicroflow(_ model.ID) (*microflows.Microflow, error) {
	var r0 *microflows.Microflow
	return r0, errUnimplemented("GetMicroflow")
}

func (unimplemented) GetModule(_ model.ID) (*model.Module, error) {
	var r0 *model.Module
	return r0, errUnimplemented("GetModule")
}

func (unimplemented) GetModuleByName(_ string) (*model.Module, error) {
	var r0 *model.Module
	return r0, errUnimplemented("GetModuleByName")
}

func (unimplemented) GetModuleSecurity(_ model.ID) (*security.ModuleSecurity, error) {
	var r0 *security.ModuleSecurity
	return r0, errUnimplemented("GetModuleSecurity")
}

func (unimplemented) GetModuleSettings(_ model.ID) (*types.ModuleSettings, error) {
	var r0 *types.ModuleSettings
	return r0, errUnimplemented("GetModuleSettings")
}

func (unimplemented) GetNanoflow(_ model.ID) (*microflows.Nanoflow, error) {
	var r0 *microflows.Nanoflow
	return r0, errUnimplemented("GetNanoflow")
}

func (unimplemented) GetNavigation() (*types.NavigationDocument, error) {
	var r0 *types.NavigationDocument
	return r0, errUnimplemented("GetNavigation")
}

func (unimplemented) GetPage(_ model.ID) (*pages.Page, error) {
	var r0 *pages.Page
	return r0, errUnimplemented("GetPage")
}

func (unimplemented) GetProjectRootID() (string, error) {
	var r0 string
	return r0, errUnimplemented("GetProjectRootID")
}

func (unimplemented) GetProjectSecurity() (*security.ProjectSecurity, error) {
	var r0 *security.ProjectSecurity
	return r0, errUnimplemented("GetProjectSecurity")
}

func (unimplemented) GetProjectSettings() (*model.ProjectSettings, error) {
	var r0 *model.ProjectSettings
	return r0, errUnimplemented("GetProjectSettings")
}

func (unimplemented) GetRawMicroflowByName(_ string) ([]uint8, error) {
	var r0 []uint8
	return r0, errUnimplemented("GetRawMicroflowByName")
}

func (unimplemented) GetRawUnit(_ model.ID) (map[string]interface{}, error) {
	var r0 map[string]interface{}
	return r0, errUnimplemented("GetRawUnit")
}

func (unimplemented) GetRawUnitByName(_ string, _ string) (*types.RawUnitInfo, error) {
	var r0 *types.RawUnitInfo
	return r0, errUnimplemented("GetRawUnitByName")
}

func (unimplemented) GetRawUnitBytes(_ model.ID) ([]uint8, error) {
	var r0 []uint8
	return r0, errUnimplemented("GetRawUnitBytes")
}

func (unimplemented) GetScheduledEvent(_ model.ID) (*model.ScheduledEvent, error) {
	var r0 *model.ScheduledEvent
	return r0, errUnimplemented("GetScheduledEvent")
}

func (unimplemented) GetUnitTypes() (map[string]int, error) {
	var r0 map[string]int
	return r0, errUnimplemented("GetUnitTypes")
}

func (unimplemented) GetWorkflow(_ model.ID) (*workflows.Workflow, error) {
	var r0 *workflows.Workflow
	return r0, errUnimplemented("GetWorkflow")
}

func (unimplemented) InvalidateCache() {
	panic(errUnimplemented("InvalidateCache"))
}

func (unimplemented) IsConnected() bool {
	var r0 bool
	return r0
}

func (unimplemented) IsRule(_ string) (bool, error) {
	var r0 bool
	return r0, errUnimplemented("IsRule")
}

func (unimplemented) ListAgentEditorAgents() ([]*agenteditor.Agent, error) {
	var r0 []*agenteditor.Agent
	return r0, errUnimplemented("ListAgentEditorAgents")
}

func (unimplemented) ListAgentEditorConsumedMCPServices() ([]*agenteditor.ConsumedMCPService, error) {
	var r0 []*agenteditor.ConsumedMCPService
	return r0, errUnimplemented("ListAgentEditorConsumedMCPServices")
}

func (unimplemented) ListAgentEditorKnowledgeBases() ([]*agenteditor.KnowledgeBase, error) {
	var r0 []*agenteditor.KnowledgeBase
	return r0, errUnimplemented("ListAgentEditorKnowledgeBases")
}

func (unimplemented) ListAgentEditorModels() ([]*agenteditor.Model, error) {
	var r0 []*agenteditor.Model
	return r0, errUnimplemented("ListAgentEditorModels")
}

func (unimplemented) ListAllUnitIDs() ([]string, error) {
	var r0 []string
	return r0, errUnimplemented("ListAllUnitIDs")
}

func (unimplemented) ListBuildingBlocks() ([]*pages.BuildingBlock, error) {
	var r0 []*pages.BuildingBlock
	return r0, errUnimplemented("ListBuildingBlocks")
}

func (unimplemented) ListBusinessEventServices() ([]*model.BusinessEventService, error) {
	var r0 []*model.BusinessEventService
	return r0, errUnimplemented("ListBusinessEventServices")
}

func (unimplemented) ListConstants() ([]*model.Constant, error) {
	var r0 []*model.Constant
	return r0, errUnimplemented("ListConstants")
}

func (unimplemented) ListConsumedODataServices() ([]*model.ConsumedODataService, error) {
	var r0 []*model.ConsumedODataService
	return r0, errUnimplemented("ListConsumedODataServices")
}

func (unimplemented) ListConsumedRestServices() ([]*model.ConsumedRestService, error) {
	var r0 []*model.ConsumedRestService
	return r0, errUnimplemented("ListConsumedRestServices")
}

func (unimplemented) ListDataTransformers() ([]*model.DataTransformer, error) {
	var r0 []*model.DataTransformer
	return r0, errUnimplemented("ListDataTransformers")
}

func (unimplemented) ListDatabaseConnections() ([]*model.DatabaseConnection, error) {
	var r0 []*model.DatabaseConnection
	return r0, errUnimplemented("ListDatabaseConnections")
}

func (unimplemented) ListDomainModels() ([]*domainmodel.DomainModel, error) {
	var r0 []*domainmodel.DomainModel
	return r0, errUnimplemented("ListDomainModels")
}

func (unimplemented) ListEnumerations() ([]*model.Enumeration, error) {
	var r0 []*model.Enumeration
	return r0, errUnimplemented("ListEnumerations")
}

func (unimplemented) ListExportMappings() ([]*model.ExportMapping, error) {
	var r0 []*model.ExportMapping
	return r0, errUnimplemented("ListExportMappings")
}

func (unimplemented) ListFolders() ([]*types.FolderInfo, error) {
	var r0 []*types.FolderInfo
	return r0, errUnimplemented("ListFolders")
}

func (unimplemented) ListImageCollections() ([]*types.ImageCollection, error) {
	var r0 []*types.ImageCollection
	return r0, errUnimplemented("ListImageCollections")
}

func (unimplemented) ListImportMappings() ([]*model.ImportMapping, error) {
	var r0 []*model.ImportMapping
	return r0, errUnimplemented("ListImportMappings")
}

func (unimplemented) ListJavaActions() ([]*types.JavaAction, error) {
	var r0 []*types.JavaAction
	return r0, errUnimplemented("ListJavaActions")
}

func (unimplemented) ListJavaActionsFull() ([]*javaactions.JavaAction, error) {
	var r0 []*javaactions.JavaAction
	return r0, errUnimplemented("ListJavaActionsFull")
}

func (unimplemented) ListJavaScriptActions() ([]*types.JavaScriptAction, error) {
	var r0 []*types.JavaScriptAction
	return r0, errUnimplemented("ListJavaScriptActions")
}

func (unimplemented) ListJsonStructures() ([]*types.JsonStructure, error) {
	var r0 []*types.JsonStructure
	return r0, errUnimplemented("ListJsonStructures")
}

func (unimplemented) ListLayouts() ([]*pages.Layout, error) {
	var r0 []*pages.Layout
	return r0, errUnimplemented("ListLayouts")
}

func (unimplemented) ListMicroflows() ([]*microflows.Microflow, error) {
	var r0 []*microflows.Microflow
	return r0, errUnimplemented("ListMicroflows")
}

func (unimplemented) ListModuleSecurity() ([]*security.ModuleSecurity, error) {
	var r0 []*security.ModuleSecurity
	return r0, errUnimplemented("ListModuleSecurity")
}

func (unimplemented) ListModuleSettings() ([]*types.ModuleSettings, error) {
	var r0 []*types.ModuleSettings
	return r0, errUnimplemented("ListModuleSettings")
}

func (unimplemented) ListModules() ([]*model.Module, error) {
	var r0 []*model.Module
	return r0, errUnimplemented("ListModules")
}

func (unimplemented) ListNanoflows() ([]*microflows.Nanoflow, error) {
	var r0 []*microflows.Nanoflow
	return r0, errUnimplemented("ListNanoflows")
}

func (unimplemented) ListNavigationDocuments() ([]*types.NavigationDocument, error) {
	var r0 []*types.NavigationDocument
	return r0, errUnimplemented("ListNavigationDocuments")
}

func (unimplemented) ListPageTemplates() ([]*pages.PageTemplate, error) {
	var r0 []*pages.PageTemplate
	return r0, errUnimplemented("ListPageTemplates")
}

func (unimplemented) ListPages() ([]*pages.Page, error) {
	var r0 []*pages.Page
	return r0, errUnimplemented("ListPages")
}

func (unimplemented) ListPublishedODataServices() ([]*model.PublishedODataService, error) {
	var r0 []*model.PublishedODataService
	return r0, errUnimplemented("ListPublishedODataServices")
}

func (unimplemented) ListPublishedRestServices() ([]*model.PublishedRestService, error) {
	var r0 []*model.PublishedRestService
	return r0, errUnimplemented("ListPublishedRestServices")
}

func (unimplemented) ListRawUnits(_ string) ([]*types.RawUnitInfo, error) {
	var r0 []*types.RawUnitInfo
	return r0, errUnimplemented("ListRawUnits")
}

func (unimplemented) ListRawUnitsByType(_ string) ([]*types.RawUnit, error) {
	var r0 []*types.RawUnit
	return r0, errUnimplemented("ListRawUnitsByType")
}

func (unimplemented) ListScheduledEvents() ([]*model.ScheduledEvent, error) {
	var r0 []*model.ScheduledEvent
	return r0, errUnimplemented("ListScheduledEvents")
}

func (unimplemented) ListSnippets() ([]*pages.Snippet, error) {
	var r0 []*pages.Snippet
	return r0, errUnimplemented("ListSnippets")
}

func (unimplemented) ListUnits() ([]*types.UnitInfo, error) {
	var r0 []*types.UnitInfo
	return r0, errUnimplemented("ListUnits")
}

func (unimplemented) ListWorkflows() ([]*workflows.Workflow, error) {
	var r0 []*workflows.Workflow
	return r0, errUnimplemented("ListWorkflows")
}

func (unimplemented) LoadWidgetTemplate(_ string, _ string) (backend.WidgetObjectBuilder, error) {
	var r0 backend.WidgetObjectBuilder
	return r0, errUnimplemented("LoadWidgetTemplate")
}

func (unimplemented) MoveConstant(_ *model.Constant) error {
	return errUnimplemented("MoveConstant")
}

func (unimplemented) MoveDatabaseConnection(_ *model.DatabaseConnection) error {
	return errUnimplemented("MoveDatabaseConnection")
}

func (unimplemented) MoveEntity(_ *domainmodel.Entity, _ model.ID, _ model.ID, _ string, _ string) ([]string, error) {
	var r0 []string
	return r0, errUnimplemented("MoveEntity")
}

func (unimplemented) MoveEnumeration(_ *model.Enumeration) error {
	return errUnimplemented("MoveEnumeration")
}

func (unimplemented) MoveExportMapping(_ *model.ExportMapping) error {
	return errUnimplemented("MoveExportMapping")
}

func (unimplemented) MoveFolder(_ model.ID, _ model.ID) error {
	return errUnimplemented("MoveFolder")
}

func (unimplemented) MoveImportMapping(_ *model.ImportMapping) error {
	return errUnimplemented("MoveImportMapping")
}

func (unimplemented) MoveMicroflow(_ *microflows.Microflow) error {
	return errUnimplemented("MoveMicroflow")
}

func (unimplemented) MoveNanoflow(_ *microflows.Nanoflow) error {
	return errUnimplemented("MoveNanoflow")
}

func (unimplemented) MovePage(_ *pages.Page) error {
	return errUnimplemented("MovePage")
}

func (unimplemented) MoveSnippet(_ *pages.Snippet) error {
	return errUnimplemented("MoveSnippet")
}

func (unimplemented) MoveViewEntitySourceDocument(_ string, _ model.ID, _ string) error {
	return errUnimplemented("MoveViewEntitySourceDocument")
}

func (unimplemented) OpenPageForMutation(_ model.ID) (backend.PageMutator, error) {
	var r0 backend.PageMutator
	return r0, errUnimplemented("OpenPageForMutation")
}

func (unimplemented) OpenWorkflowForMutation(_ model.ID) (backend.WorkflowMutator, error) {
	var r0 backend.WorkflowMutator
	return r0, errUnimplemented("OpenWorkflowForMutation")
}

func (unimplemented) ParseMicroflowBSON(_ []uint8, _ model.ID, _ model.ID) (*microflows.Microflow, error) {
	var r0 *microflows.Microflow
	return r0, errUnimplemented("ParseMicroflowBSON")
}

func (unimplemented) ParseMicroflowFromRaw(_ map[string]interface{}, _ model.ID, _ model.ID) *microflows.Microflow {
	var r0 *microflows.Microflow
	return r0
}

func (unimplemented) Path() string {
	var r0 string
	return r0
}

func (unimplemented) ProjectVersion() *types.ProjectVersion {
	var r0 *types.ProjectVersion
	return r0
}

func (unimplemented) ReadJavaActionByName(_ string) (*javaactions.JavaAction, error) {
	var r0 *javaactions.JavaAction
	return r0, errUnimplemented("ReadJavaActionByName")
}

func (unimplemented) ReadJavaScriptActionByName(_ string) (*types.JavaScriptAction, error) {
	var r0 *types.JavaScriptAction
	return r0, errUnimplemented("ReadJavaScriptActionByName")
}

func (unimplemented) ReadJavaSourceFile(_ string, _ string) (string, error) {
	var r0 string
	return r0, errUnimplemented("ReadJavaSourceFile")
}

func (unimplemented) ReconcileMemberAccesses(_ model.ID, _ string) (int, error) {
	var r0 int
	return r0, errUnimplemented("ReconcileMemberAccesses")
}

func (unimplemented) RemoveDemoUser(_ model.ID, _ string) error {
	return errUnimplemented("RemoveDemoUser")
}

func (unimplemented) RemoveEntityAccessRule(_ model.ID, _ string, _ []string) (int, error) {
	var r0 int
	return r0, errUnimplemented("RemoveEntityAccessRule")
}

func (unimplemented) RemoveFromAllowedRoles(_ model.ID, _ string) (bool, error) {
	var r0 bool
	return r0, errUnimplemented("RemoveFromAllowedRoles")
}

func (unimplemented) RemoveModuleRole(_ model.ID, _ string) error {
	return errUnimplemented("RemoveModuleRole")
}

func (unimplemented) RemoveModuleRoleFromAllUserRoles(_ model.ID, _ string) (int, error) {
	var r0 int
	return r0, errUnimplemented("RemoveModuleRoleFromAllUserRoles")
}

func (unimplemented) RemoveRoleFromAllEntities(_ model.ID, _ string) (int, error) {
	var r0 int
	return r0, errUnimplemented("RemoveRoleFromAllEntities")
}

func (unimplemented) RemoveUserRole(_ model.ID, _ string) error {
	return errUnimplemented("RemoveUserRole")
}

func (unimplemented) RenameDocumentByName(_ string, _ string, _ string) error {
	return errUnimplemented("RenameDocumentByName")
}

func (unimplemented) RenameJavaScriptSourceFile(_ string, _ string, _ string) error {
	return errUnimplemented("RenameJavaScriptSourceFile")
}

func (unimplemented) RenameJavaSourceFile(_ string, _ string, _ string) error {
	return errUnimplemented("RenameJavaSourceFile")
}

func (unimplemented) RenameReferences(_ string, _ string, _ bool) ([]types.RenameHit, error) {
	var r0 []types.RenameHit
	return r0, errUnimplemented("RenameReferences")
}

func (unimplemented) RevokeEntityMemberAccess(_ model.ID, _ string, _ []string, _ types.EntityAccessRevocation) (int, error) {
	var r0 int
	return r0, errUnimplemented("RevokeEntityMemberAccess")
}

func (unimplemented) SerializeClientAction(_ pages.ClientAction) (interface{}, error) {
	var r0 interface{}
	return r0, errUnimplemented("SerializeClientAction")
}

func (unimplemented) SerializeDataSource(_ pages.DataSource) (interface{}, error) {
	var r0 interface{}
	return r0, errUnimplemented("SerializeDataSource")
}

func (unimplemented) SerializeDataSourceToOpaque(_ pages.DataSource) interface{} {
	var r0 interface{}
	return r0
}

func (unimplemented) SerializeWidget(_ pages.Widget) (interface{}, error) {
	var r0 interface{}
	return r0, errUnimplemented("SerializeWidget")
}

func (unimplemented) SerializeWidgetToOpaque(_ pages.Widget) interface{} {
	var r0 interface{}
	return r0
}

func (unimplemented) SerializeWorkflowActivity(_ workflows.WorkflowActivity) (interface{}, error) {
	var r0 interface{}
	return r0, errUnimplemented("SerializeWorkflowActivity")
}

func (unimplemented) SetProjectDemoUsersEnabled(_ model.ID, _ bool) error {
	return errUnimplemented("SetProjectDemoUsersEnabled")
}

func (unimplemented) SetProjectSecurityLevel(_ model.ID, _ string) error {
	return errUnimplemented("SetProjectSecurityLevel")
}

func (unimplemented) UpdateAgentEditorAgent(_ *agenteditor.Agent) error {
	return errUnimplemented("UpdateAgentEditorAgent")
}

func (unimplemented) UpdateAgentEditorConsumedMCPService(_ *agenteditor.ConsumedMCPService) error {
	return errUnimplemented("UpdateAgentEditorConsumedMCPService")
}

func (unimplemented) UpdateAgentEditorKnowledgeBase(_ *agenteditor.KnowledgeBase) error {
	return errUnimplemented("UpdateAgentEditorKnowledgeBase")
}

func (unimplemented) UpdateAgentEditorModel(_ *agenteditor.Model) error {
	return errUnimplemented("UpdateAgentEditorModel")
}

func (unimplemented) UpdateAllowedRoles(_ model.ID, _ []string) error {
	return errUnimplemented("UpdateAllowedRoles")
}

func (unimplemented) UpdateAttribute(_ model.ID, _ model.ID, _ *domainmodel.Attribute) error {
	return errUnimplemented("UpdateAttribute")
}

func (unimplemented) UpdateBusinessEventService(_ *model.BusinessEventService) error {
	return errUnimplemented("UpdateBusinessEventService")
}

func (unimplemented) UpdateConstant(_ *model.Constant) error {
	return errUnimplemented("UpdateConstant")
}

func (unimplemented) UpdateConsumedODataService(_ *model.ConsumedODataService) error {
	return errUnimplemented("UpdateConsumedODataService")
}

func (unimplemented) UpdateConsumedRestService(_ *model.ConsumedRestService) error {
	return errUnimplemented("UpdateConsumedRestService")
}

func (unimplemented) UpdateDataTransformer(_ *model.DataTransformer) error {
	return errUnimplemented("UpdateDataTransformer")
}

func (unimplemented) UpdateDatabaseConnection(_ *model.DatabaseConnection) error {
	return errUnimplemented("UpdateDatabaseConnection")
}

func (unimplemented) UpdateDomainModel(_ *domainmodel.DomainModel) error {
	return errUnimplemented("UpdateDomainModel")
}

func (unimplemented) UpdateEntity(_ model.ID, _ *domainmodel.Entity) error {
	return errUnimplemented("UpdateEntity")
}

func (unimplemented) UpdateEnumeration(_ *model.Enumeration) error {
	return errUnimplemented("UpdateEnumeration")
}

func (unimplemented) UpdateEnumerationRefsInAllDomainModels(_ string, _ string) error {
	return errUnimplemented("UpdateEnumerationRefsInAllDomainModels")
}

func (unimplemented) UpdateExportMapping(_ *model.ExportMapping) error {
	return errUnimplemented("UpdateExportMapping")
}

func (unimplemented) UpdateImageCollection(_ *types.ImageCollection) error {
	return errUnimplemented("UpdateImageCollection")
}

func (unimplemented) UpdateImportMapping(_ *model.ImportMapping) error {
	return errUnimplemented("UpdateImportMapping")
}

func (unimplemented) UpdateJavaAction(_ *javaactions.JavaAction) error {
	return errUnimplemented("UpdateJavaAction")
}

func (unimplemented) UpdateJavaScriptAction(_ *types.JavaScriptAction) error {
	return errUnimplemented("UpdateJavaScriptAction")
}

func (unimplemented) UpdateJsonStructure(_ *types.JsonStructure) error {
	return errUnimplemented("UpdateJsonStructure")
}

func (unimplemented) UpdateLayout(_ *pages.Layout) error {
	return errUnimplemented("UpdateLayout")
}

func (unimplemented) UpdateMicroflow(_ *microflows.Microflow) error {
	return errUnimplemented("UpdateMicroflow")
}

func (unimplemented) UpdateModule(_ *model.Module) error {
	return errUnimplemented("UpdateModule")
}

func (unimplemented) UpdateModuleSettings(_ *types.ModuleSettings) error {
	return errUnimplemented("UpdateModuleSettings")
}

func (unimplemented) UpdateNanoflow(_ *microflows.Nanoflow) error {
	return errUnimplemented("UpdateNanoflow")
}

func (unimplemented) UpdateNavigationProfile(_ model.ID, _ string, _ types.NavigationProfileSpec) error {
	return errUnimplemented("UpdateNavigationProfile")
}

func (unimplemented) UpdateOqlQueriesForMovedEntity(_ string, _ string) (int, error) {
	var r0 int
	return r0, errUnimplemented("UpdateOqlQueriesForMovedEntity")
}

func (unimplemented) UpdatePage(_ *pages.Page) error {
	return errUnimplemented("UpdatePage")
}

func (unimplemented) UpdateProjectSettings(_ *model.ProjectSettings) error {
	return errUnimplemented("UpdateProjectSettings")
}

func (unimplemented) UpdatePublishedODataService(_ *model.PublishedODataService) error {
	return errUnimplemented("UpdatePublishedODataService")
}

func (unimplemented) UpdatePublishedRestService(_ *model.PublishedRestService) error {
	return errUnimplemented("UpdatePublishedRestService")
}

func (unimplemented) UpdatePublishedRestServiceRoles(_ model.ID, _ []string) error {
	return errUnimplemented("UpdatePublishedRestServiceRoles")
}

func (unimplemented) UpdateQualifiedNameInAllUnits(_ string, _ string) (int, error) {
	var r0 int
	return r0, errUnimplemented("UpdateQualifiedNameInAllUnits")
}

func (unimplemented) UpdateRawUnit(_ string, _ []uint8) error {
	return errUnimplemented("UpdateRawUnit")
}

func (unimplemented) UpdateSnippet(_ *pages.Snippet) error {
	return errUnimplemented("UpdateSnippet")
}

func (unimplemented) UpdateWorkflow(_ *workflows.Workflow) error {
	return errUnimplemented("UpdateWorkflow")
}

func (unimplemented) Version() types.MPRVersion {
	var r0 types.MPRVersion
	return r0
}

func (unimplemented) WriteJavaScriptSourceFile(_ string, _ string, _ string, _ []*types.JavaActionParameter, _ types.CodeActionReturnType) error {
	return errUnimplemented("WriteJavaScriptSourceFile")
}

func (unimplemented) WriteJavaSourceFile(_ string, _ string, _ string, _ []*types.JavaActionParameter, _ types.CodeActionReturnType, _ []string, _ string) error {
	return errUnimplemented("WriteJavaSourceFile")
}
